/* Okeymoney — Textos en español (idioma por defecto y fuente de verdad). */
(function () {
  'use strict';
  App.i18n.register({
    title: 'Okeymoney',
    appName: 'Okeymoney',

    agent: {
      persona: 'Persona',
      empresa: 'Empresa',
      banco: 'Banco'
    },

    meta: {
      description: 'Aprende a manejar tu dinero: cuánto tienes, cuánto gastas y cuánto ahorras.'
    },

    tabs: {
      home: 'Mi dinero',
      goals: 'Mis metas',
      learn: 'Aprender'
    },

    home: {
      saludo: 'Hola. ¿Qué quieres hacer hoy?',
      moreGoals: '+{n} más',
      anchorAria: 'Ir a {theme}',
      anchorNavAria: 'Ir a un bloque',
      balanceLabel: 'Tienes',
      editBalanceAria: 'Cambiar cuánto dinero tienes',
      editHint: 'Toca para cambiar cuánto dinero tienes',
      setBalanceTitle: '¿Cuánto dinero tienes?',
      setBalanceInstruction: 'Cuenta tu dinero y escribe cuánto tienes ahora.',
      catalogueTitle: 'Aprende con Okeymoney',
      practiceBalance: 'Tokens disponibles',
      inlineExpense: 'Registrar un gasto',
      inlineExpenseDetail: 'Practica una compra real con euros.',
      movementsTitle: 'Movimientos recientes',
      movementsEmpty: 'Todavía no hay movimientos.',
      insightsTitle: 'Mi compás financiero',
      insightsEmpty: 'Cuando registres movimientos, aquí verás qué está pasando con tu dinero.',
      insightsSummary: 'Has recibido {income}, gastado {expenses} y guardado {saving}.',
      insightsTopCategory: 'Tu categoría de gasto principal es {category}: {amount}.',
      insightsCommitments: 'Pagos previstos anotados: {amount}.',
      statementTitle: 'Mi foto financiera',
      statementNote: 'Es una orientación sencilla: los pagos previstos no son una deuda bancaria automática.',
      statementAssets: 'Activos',
      statementAssetsDetail: 'Dinero disponible + ahorro en metas',
      statementLiabilities: 'Pasivos previstos',
      statementLiabilitiesDetail: 'Pagos que has anotado para recordar',
      statementIncome: 'Ingresos',
      statementExpenses: 'Gastos',
      statementRecordedDetail: 'Total registrado',
      statementPosition: 'Posición orientativa:',
      statementDeficit: 'Tu saldo actual está por debajo de cero. Revisa los gastos y pide apoyo si lo necesitas.',
      controlTitle: 'Control de mis finanzas',
      controlNote: 'La contabilidad dice qué pasó. Este control te ayuda a decidir qué hacer ahora.',
      controlBalance: 'Saldo ahora',
      controlCommitted: 'Comprometido',
      controlAvailable: 'Disponible después de compromisos',
      controlLastPlan: 'Última compra planificada:',
      controlPlanDetail: 'presupuesto {budget}, precio {price}, diferencia {difference}',
      controlWarning: 'Tus compromisos previstos superan el saldo actual. Revisa fechas o importes.',
      controlAction: 'Planificar otra compra',
      cycleTitle: 'Mi ciclo financiero',
      cycleIntro: 'Sigue este orden: decide, recibe, guarda y usa tu dinero.',
      cycleDone: 'Paso practicado',
      cycle: {
        budgetTitle: 'Presupuestar',
        budgetDetail: 'Decide cuánto puedes gastar.',
        budgetAction: 'Abrir presupuesto',
        incomeTitle: 'Ingresar',
        incomeDetail: 'Anota cuándo entra dinero.',
        incomeAction: 'Registrar un ingreso',
        savingTitle: 'Ahorrar',
        savingDetail: 'Separa una cantidad para una meta.',
        savingAction: 'Abrir ahorro',
        spendingTitle: 'Gastar',
        spendingDetail: 'Registra lo que compras.',
        spendingAction: 'Registrar un gasto'
      },
      nextStep: {
        eyebrow: 'Hoy',
        title: 'Tu siguiente paso',
        balanceDetail: 'Empieza por contar cuánto dinero tienes ahora.',
        balanceAction: 'Anotar mi saldo',
        goalDetail: 'Ya conoces tu saldo. Elige algo para ahorrar.',
        goalAction: 'Crear una meta',
        expenseDetail: 'Practica una compra y mira cómo cambia tu saldo.',
        expenseAction: 'Registrar un gasto',
        budgetDetail: 'Empieza decidiendo cuánto puedes gastar.',
        budgetAction: 'Preparar un presupuesto',
        incomeDetail: 'Después, anota el dinero que entra.',
        incomeAction: 'Registrar un ingreso',
        savingDetail: 'Ahora separa una cantidad para ahorrar.',
        savingAction: 'Empezar a ahorrar',
        note: 'Puedes parar cuando quieras. Todo queda en tu dispositivo.'
      }
    },

    blocks: {
      didactic: {
        title: 'Aprende sobre tu dinero',
        intro: 'Ideas sencillas para entender y manejar mejor tu dinero.',
        cta: 'Ahora, prueba lo que has aprendido',
        lessonPhase: 'Fase 1 · Descubre',
        testPhase: 'Fase 2 · Ponlo en práctica',
        testPhaseDetail: 'Ahora prueba esta idea con una actividad.',
        testLink: 'Probar: {title}',
        lessons: {
          moneyTitle: 'Conoce el valor de tu dinero',
          moneyDetail: 'Aprende a reconocer monedas, billetes y lo que vale cada uno.',
          choicesTitle: 'Elige lo que necesitas',
          choicesDetail: 'Distingue entre lo que necesitas y lo que te apetece.',
          budgetTitle: 'Organiza tus compras',
          budgetDetail: 'Ordena lo que quieres comprar antes de gastar.',
          changeTitle: 'Paga y comprueba tu cambio',
          changeDetail: 'Mira que la vuelta que recibes sea correcta.',
          savingTitle: 'Guarda dinero para algo que quieres',
          savingDetail: 'Aparta poco a poco una cantidad para alcanzar una meta.',
          safetyTitle: 'Cuida tu dinero',
          safetyDetail: 'Aprende a reconocer riesgos y a pedir ayuda cuando lo necesites.',
          documentsTitle: 'Sigue el camino de una compra',
          documentsDetail: 'Descubre qué pasa desde que haces un pedido hasta que lo pagas.',
          assetsTitle: 'Mira cómo está tu dinero',
          assetsDetail: 'Distingue lo que tienes, lo que debes y el dinero que entra y sale.',
          accountingTitle: 'Apunta y ordena tus movimientos',
          accountingDetail: 'Anotar lo que pasa te ayuda a saber cómo va tu dinero y decidir mejor.',
          assetLifecycleTitle: 'Cuida tus cosas y su valor',
          assetLifecycleDetail: 'Descubre cómo pierden valor con el tiempo y qué hacer cuando dejan de servirte.',
          returnRiskTitle: 'Valora lo que puedes ganar y perder',
          returnRiskDetail: 'Compara una posible ganancia con el riesgo de perder dinero.',
          investmentOperationsTitle: 'Aprende qué pasa al invertir',
          investmentOperationsDetail: 'Reconoce qué ocurre cuando compras, vendes o cambias una inversión.',
          bankProductsTitle: 'Conoce tus tarjetas y cuentas',
          bankProductsDetail: 'Descubre cuándo usas tu saldo, un crédito o dinero que has reservado.',
          housingTitle: 'Elige dónde vivir: ¿alquilar o comprar?',
          housingDetail: 'Compara gastos, compromisos y libertad antes de decidir.'
        }
      },
      test: {
        title: 'Pon a prueba lo que sabes',
        intro: 'Cada unidad termina con una actividad. Practica con situaciones y gana Tokens.',
        walletLabel: 'Tokens de práctica',
        rewardHint: 'Cada actividad suma Tokens una vez.',
        indexIntro: 'Cada unidad tiene su propia actividad. Usa este índice para volver a la que quieras.',
        indexHint: 'Ir a la unidad'
      },
      simulation: {
        title: 'Simula situaciones reales con dinero',
        intro: 'Practica compras, gastos, ahorro y decisiones cotidianas con dinero en euros, en un espacio seguro.',
        balanceTitle: 'Mi saldo',
        balanceDetail: 'Toca para actualizar cuánto dinero tienes.',
        goalsTitle: 'Mis metas',
        goalsDetail: 'Ahorra poco a poco para algo que quieres.',
        expenseTitle: 'Registrar un gasto',
        expenseDetail: 'Practica una compra real con dinero en euros.',
        changeTitle: 'Comprueba la vuelta',
        changeDetail: 'Paga, calcula la vuelta y comprueba el resultado.',
        safetyTitle: 'Comprueba si es seguro',
        safetyDetail: 'Decide qué hacer antes de enviar dinero.',
        rightsTitle: 'Conoce tus derechos',
        rightsDetail: 'Practica cómo reclamar y pedir comprobantes.',
        communicationTitle: 'Habla claro sobre dinero',
        communicationDetail: 'Ensaya preguntas, límites y pedir ayuda.',
        emergencyTitle: 'Responde a un imprevisto',
        emergencyDetail: 'Toma decisiones seguras cuando algo cambia.',
        purchaseTitle: 'Del pedido al pago',
        purchaseDetail: 'Practica pedido, albarán, factura y pago.',
        depreciationTitle: 'Calcula la depreciación',
        depreciationDetail: 'Estima cuánto valor conserva un bien con el paso del tiempo.',
        depreciationQuestion: '¿Cuánto valor conserva este bien?',
        depreciationHint: 'Reparte la pérdida entre los meses de vida útil y conserva el valor residual.',
        depreciationFormula: 'Valor actual = precio − ((precio − valor residual) × meses usados ÷ vida útil)',
        depreciationScenarios: {
          phoneScene: 'Un teléfono costó {price}. Se usa durante {elapsed} de sus {life} meses de vida útil. Su valor residual es {residual}.',
          laptopScene: 'Un portátil costó {price}. Han pasado {elapsed} de sus {life} meses de vida útil y conserva un valor residual de {residual}.',
          bikeScene: 'Una bicicleta costó {price}. Han pasado {elapsed} de sus {life} meses de vida útil y conserva un valor residual de {residual}.'
        },
        obsolescenceTitle: 'Decide ante la obsolescencia',
        obsolescenceDetail: 'Compara reparar, reutilizar o sustituir antes de gastar.',
        obsolescenceQuestion: '¿Qué decisión protege mejor tu dinero?',
        obsolescenceHint: 'Comprueba si aún recibe soporte, si se puede reparar y cuánto cuesta cada opción.',
        obsolescenceScenarios: {
          phoneScene: 'Tu teléfono todavía funciona, pero las actualizaciones de seguridad terminarán el año que viene.',
          phoneUnsafe: 'Lo cambio hoy sin comparar alternativas.',
          phoneSafe: 'Compruebo soporte, reparación y coste de sustituirlo antes de decidir.',
          laptopScene: 'Tu portátil va lento para una tarea, aunque todavía sirve para otras cosas.',
          laptopUnsafe: 'Compro otro sin probar una reparación o darle otro uso.',
          laptopSafe: 'Comparo reparar, reutilizarlo para otra tarea y comprar uno nuevo.',
          applianceScene: 'Un electrodoméstico falla y ya no encuentras piezas de repuesto.',
          applianceUnsafe: 'Compro el primero que veo sin revisar consumo ni garantía.',
          applianceSafe: 'Comparo reparación, consumo, garantía y sustitución antes de pagar.'
        },
        returnTitle: 'Calcula la rentabilidad',
        returnDetail: 'Calcula cuánto puede crecer una cantidad en un ejemplo.',
        returnQuestion: '¿Cuánto ganarías en este ejemplo?',
        returnHint: 'Multiplica la cantidad por el porcentaje y expresa el resultado en euros.',
        returnFormula: 'Ganancia = cantidad × porcentaje',
        returnScenarios: {
          savingsScene: 'Imagina que guardas {principal} durante un año con una rentabilidad bruta del {rate}%.',
          bondScene: 'Imagina que colocas {principal} durante un año con una rentabilidad bruta del {rate}%.',
          diversifiedScene: 'Imagina una inversión diversificada de {principal} durante un año con una rentabilidad bruta del {rate}%.'
        },
        riskTitle: 'Compara rentabilidad y riesgo',
        riskDetail: 'Mira el plazo, la liquidez y la diversificación antes de decidir.',
        riskQuestion: '¿Qué decisión encaja mejor con el objetivo?',
        riskHint: 'Una rentabilidad posible no es segura: revisa plazo, disponibilidad y si repartes el riesgo.',
        riskScenarios: {
          emergencyScene: 'Necesitas 300 € para una emergencia que puede ocurrir este mes.',
          emergencyUnsafe: 'Busco la mayor rentabilidad aunque pueda perder o no disponer del dinero.',
          emergencySafe: 'Priorizo que el dinero esté disponible y tenga poco riesgo.',
          diversifyScene: 'Quieres invertir 600 € y solo te ofrecen una empresa o varias opciones repartidas.',
          diversifyUnsafe: 'Pongo todo en una sola empresa porque promete más rentabilidad.',
          diversifySafe: 'Comparo costes y reparto el dinero para no depender de una sola empresa.',
          horizonScene: 'Tu objetivo está a dos meses y no puedes aceptar grandes cambios de valor.',
          horizonUnsafe: 'Elijo una opción muy variable porque el porcentaje esperado es alto.',
          horizonSafe: 'Elijo una opción acorde al plazo y acepto menos rentabilidad potencial.'
        },
        investmentTitle: 'Reconoce operaciones de inversión',
        investmentDetail: 'Distingue comprar, vender, cobrar un rendimiento y traspasar.',
        investmentQuestion: '¿Qué operación describe mejor la situación?',
        investmentHint: 'Fíjate en si entra dinero, sale dinero o cambia el producto donde está invertido.',
        investmentScenarios: {
          buyScene: 'Tienes 100 € disponibles y los colocas en un fondo después de revisar sus condiciones.',
          buyWrong: 'Es un reembolso o una venta.',
          buyCorrect: 'Es una compra o aportación a una inversión.',
          sellScene: 'Necesitas dinero y solicitas recuperar una parte del fondo.',
          sellWrong: 'Es una aportación nueva al fondo.',
          sellCorrect: 'Es una venta o reembolso.',
          returnScene: 'La inversión genera 4 € y la entidad los abona en tu cuenta.',
          returnWrong: 'Es el dinero que aportaste inicialmente.',
          returnCorrect: 'Es el cobro de un rendimiento o dividendo.',
          transferScene: 'Mueves tu inversión de un producto a otro sin retirarla a tu cuenta.',
          transferWrong: 'Es una compra nueva con dinero que acabas de recibir.',
          transferCorrect: 'Es un traspaso entre productos de inversión.'
        },
        bankProductsTitle: 'Reconoce tarjetas y cuentas',
        bankProductsDetail: 'Distingue cuándo se usa el saldo propio, el crédito o el ahorro.',
        bankProductsQuestion: '¿Qué tarjeta o cuenta describe mejor la situación?',
        bankProductsHint: 'Fíjate en si el dinero ya es tuyo, si te lo prestan o si está reservado para ahorrar.',
        bankProductsScenarios: {
          debitScene: 'Pagas 18 € con una tarjeta y el importe sale en el momento del saldo de tu cuenta.',
          debitWrong: 'Es una tarjeta de crédito: lo pagaré más adelante.',
          debitCorrect: 'Es una tarjeta de débito: usa el saldo de tu cuenta.',
          creditScene: 'Pagas 18 € con una tarjeta y la entidad te cobra después según el contrato.',
          creditWrong: 'Es una tarjeta de débito: siempre sale al instante del saldo.',
          creditCorrect: 'Es una tarjeta de crédito: la entidad adelanta el pago y después lo cobra.',
          prepaidScene: 'Cargas 30 € en una tarjeta y solo puedes gastar hasta esa cantidad.',
          prepaidWrong: 'Es crédito: puedo gastar aunque no haya cargado dinero.',
          prepaidCorrect: 'Es una tarjeta prepago: gastas el saldo que has cargado.',
          currentScene: 'Quieres recibir ingresos, pagar recibos y usar una tarjeta para el día a día.',
          currentWrong: 'Es una cuenta de ahorro pensada solo para guardar dinero.',
          currentCorrect: 'Es una cuenta corriente: sirve para pagos y movimientos habituales.',
          savingsScene: 'Quieres separar 200 € para una meta y no necesitas usarlos cada semana.',
          savingsWrong: 'Es una cuenta corriente para pagar recibos diarios.',
          savingsCorrect: 'Es una cuenta de ahorro: ayuda a separar dinero para una reserva o meta.'
        },
        housingTitle: 'Compara alquiler y propiedad',
        housingDetail: 'Revisa costes, compromisos, mantenimiento y plazo.',
        housingQuestion: '¿Qué decisión analiza mejor esta situación?',
        housingHint: 'No mires solo la cuota: revisa pagos iniciales, gastos recurrentes, mantenimiento y cuánto tiempo estarás allí.',
        housingScenarios: {
          rentScene: 'Quieres vivir en una ciudad durante dos años y quizá cambiar de lugar después.',
          rentWrong: 'Elijo comprar sin calcular entrada, préstamo, mantenimiento ni tiempo de permanencia.',
          rentCorrect: 'Comparo un alquiler y sus gastos, valorando la flexibilidad de poder cambiar.',
          ownScene: 'Quieres quedarte muchos años y tienes ahorros para los gastos iniciales de una compra.',
          ownWrong: 'Solo miro la cuota mensual y olvido préstamo, impuestos, seguro y mantenimiento.',
          ownCorrect: 'Calculo el coste total de ser propietario y compruebo que la cuota cabe en mi presupuesto.',
          costsScene: 'Comparas un alquiler de 850 € al mes con una compra que exige entrada, préstamo y reparaciones.',
          costsWrong: 'Concluyo que comprar siempre es más barato porque al final la vivienda es mía.',
          costsCorrect: 'Pongo en la misma tabla entrada, cuotas, gastos, mantenimiento y tiempo previsto.',
          flexibilityScene: 'Tu trabajo puede trasladarte y no sabes cuánto tiempo seguirás en la zona.',
          flexibilityWrong: 'Firmo una deuda larga sin revisar qué pasaría si necesito mudarme.',
          flexibilityCorrect: 'Valoro la flexibilidad del alquiler y reviso todas las condiciones antes de firmar.',
          longTermScene: 'Tienes ingresos estables, un fondo para imprevistos y un plan de vivienda a largo plazo.',
          longTermWrong: 'Doy por hecho que comprar es mejor para cualquiera sin revisar riesgos ni presupuesto.',
          longTermCorrect: 'Comparo ambas opciones con mis ingresos, riesgos, gastos y horizonte personal.'
        },
        planTitle: 'Planifica una compra',
        planDetail: 'Elige un presupuesto antes de gastar.',
        planBudgetTitle: '¿Cuánto puedes gastar?',
        planBudgetInstruction: 'Escribe un presupuesto para tu compra.',
        planChoiceTitle: 'Elige una compra',
        planChoiceInstruction: 'Mira el precio y decide con calma.',
        planRemaining: 'Después te quedarían {balance}.',
        planOverBudget: 'Esta compra supera tu presupuesto.',
        planOverBalance: 'Esta compra supera el dinero que tienes ahora.',
        planRecord: 'Registrar este gasto',
        planBack: 'Elegir otra compra',
        planItems: {
          bread: 'Pan · 2,00 €',
          bus: 'Billete de bus · 1,50 €',
          medicine: 'Medicina · 6,50 €',
          game: 'Juego · 12,00 €'
        },
        changeQuestion: 'Escribe cuánto dinero te tienen que devolver.',
        changeHint: 'Resta el precio de la compra al dinero que entregas.',
        simulationCorrect: 'Muy bien. Has comprobado la situación.',
        simulationFinished: 'Has practicado una situación real con euros.',
        safetyQuestion: '¿Qué harías antes de enviar o devolver el dinero?',
        safetyHint: 'Para y comprueba la petición por otro medio.',
        changeScenarios: {
          bakery: 'Pagas 5,00 € por una compra de 2,30 €.',
          pharmacy: 'Pagas 10,00 € por una compra de 6,50 €.',
          market: 'Pagas 20,00 € por una compra de 12,70 €.'
        },
        safetyScenarios: {
          bizumScene: 'Recibes un Bizum inesperado de 25 € y te piden devolverlo.',
          bizumUnsafe: 'Devuelvo el dinero al número que me escribe.',
          bizumSafe: 'Compruebo el movimiento en mi banco y contacto con el banco.',
          smsScene: 'Recibes un SMS: “Tu banco necesita tus claves. Entra aquí”.',
          smsUnsafe: 'Abro el enlace y escribo mis claves.',
          smsSafe: 'No abro el enlace. Entro en la app oficial o llamo al banco.',
          familyScene: 'Un mensaje urgente pide 50 € y dice ser de un familiar.',
          familyUnsafe: 'Envío el dinero enseguida para ayudar.',
          familySafe: 'Llamo a esa persona usando un número que ya conozco.'
        },
        rightsQuestion: '¿Qué respuesta protege mejor tus derechos?',
        rightsHint: 'Pide información, guarda el comprobante y reclama por un canal oficial.',
        rightsScenarios: {
          returnScene: 'Una tienda no te informa de cómo devolver un producto de 18 € con un defecto.',
          returnUnsafe: 'Me voy sin preguntar para no molestar.',
          returnSafe: 'Pido la política de devolución y guardo el ticket.',
          receiptScene: 'Pagas 18 € y no te entregan un recibo.',
          receiptUnsafe: 'Me marcho sin comprobar nada.',
          receiptSafe: 'Pido el recibo y reviso que el importe sea correcto.',
          chargeScene: 'En tu cuenta aparece un cobro de 42 € que no reconoces.',
          chargeUnsafe: 'Lo ignoro y sigo usando la cuenta.',
          chargeSafe: 'Aviso al banco y guardo los datos del movimiento.'
        },
        communicationQuestion: '¿Qué forma de hablar te ayuda a decidir?',
        communicationHint: 'Pregunta con calma, di que necesitas tiempo y pide apoyo si lo necesitas.',
        communicationScenarios: {
          priceScene: 'No entiendes cuánto cuesta un servicio de 30 € antes de contratarlo.',
          priceUnsafe: 'Acepto sin preguntar para terminar rápido.',
          priceSafe: 'Pido el precio total y qué incluye antes de aceptar.',
          noScene: 'Alguien insiste para que compres algo que no quieres.',
          noUnsafe: 'Acepto aunque no me convenza.',
          noSafe: 'Digo que no y me tomo tiempo para pensarlo.',
          helpScene: 'Una decisión de dinero te parece confusa.',
          helpUnsafe: 'Oculto el problema y decido a ciegas.',
          helpSafe: 'Se lo cuento a alguien de confianza y pido ayuda.'
        },
        emergencyQuestion: '¿Cuál es el primer paso más seguro?',
        emergencyHint: 'Para, protege tus datos y busca apoyo antes de pagar o compartir información.',
        emergencyScenarios: {
          cardScene: 'No encuentras tu tarjeta y crees que la has perdido.',
          cardUnsafe: 'Espero varios días por si aparece.',
          cardSafe: 'La bloqueo desde la app o llamo al banco cuanto antes.',
          repairScene: 'Se rompe algo importante y te piden pagar una reparación urgente.',
          repairUnsafe: 'Pago lo primero que me piden sin comparar.',
          repairSafe: 'Pido presupuesto y consulto a alguien antes de pagar.',
          urgentScene: 'Llega un gasto inesperado de 90 € y este mes vas justo de dinero.',
          urgentUnsafe: 'Pido un préstamo rápido sin leer las condiciones.',
          urgentSafe: 'Reviso prioridades, hablo con alguien y busco opciones seguras.'
        },
        purchaseIntro: 'Una compra puede tener cuatro momentos. El dinero solo sale al pagar.',
        purchaseNext: 'Siguiente documento',
        purchasePay: 'Confirmar pago de {amount}',
        purchasePaid: 'Pago registrado. El gasto aparece en tus movimientos.',
        purchaseAfter: 'Después del pago tendrías {balance}.',
        purchaseOverBalance: 'El pago es mayor que tu saldo actual. Revísalo antes de confirmar.',
        purchaseStages: {
          orderTitle: '1. Pedido',
          orderDetail: 'Pides el producto o servicio. Todavía no has recibido nada ni pagado.',
          deliveryTitle: '2. Albarán',
          deliveryDetail: 'Compruebas que lo recibido coincide con lo que pediste.',
          invoiceTitle: '3. Factura',
          invoiceDetail: 'La factura indica qué debes pagar, cuánto y a quién.',
          paymentTitle: '4. Pago',
          paymentDetail: 'Pagas después de revisar el pedido, lo recibido y la factura.'
        },
        purchaseScenarios: {
          backpack: 'Una mochila cuesta 24,00 €.',
          shoes: 'Unas zapatillas cuestan 36,00 €.',
          repair: 'Una reparación necesaria cuesta 90,00 €.'
        }
      }
    },

    expense: {
      categoryTitle: '¿En qué gastaste?',
      categoryInstruction: 'Elige un dibujo.',
      amountTitle: '¿Cuánto gastaste?',
      amountInstruction: 'Escribe el precio.',
      confirmTitle: 'Revisa tu gasto',
      confirmInstruction: 'Si está bien, guárdalo.',
      saveButton: '✅ Guardar gasto',
      savedMessage: '¡Gasto guardado!',
      afterExpense: 'Después de este gasto tendrás {balance}.',
      overBalance: 'Este gasto es mayor que tu saldo. Revisa el importe si quieres.',
      savedWithBalance: '¡Gasto guardado! Ahora tienes {balance}.',
      balanceSavedWithValue: 'Saldo actualizado. Ahora tienes {balance}.'
    },

    income: {
      title: '¿De dónde viene el dinero?',
      instruction: 'Elige una opción.',
      amountTitle: '¿Cuánto dinero has recibido?',
      amountInstruction: 'Escribe la cantidad.',
      saveButton: '✅ Guardar ingreso',
      savedWithBalance: 'Dinero guardado. Ahora tienes {balance}.',
      sources: {
        allowance: 'Dinero de bolsillo',
        work: 'Trabajo',
        gift: 'Regalo',
        refund: 'Devolución'
      }
    },

    commitments: {
      title: 'Pagos previstos',
      detail: 'Apunta pagos que tendrás que recordar.',
      newButton: '+ Añadir pago previsto',
      empty: 'Todavía no tienes pagos previstos.',
      nameTitle: '¿Qué pago quieres recordar?',
      nameInstruction: 'Escribe un nombre corto.',
      namePlaceholder: 'Por ejemplo: teléfono',
      nameAria: 'Nombre del pago previsto',
      dueDateLabel: '¿Para qué día lo necesitas? (opcional)',
      dueDateAria: 'Fecha del pago previsto',
      dueDate: 'Para el {date}',
      overdue: 'Fecha pasada: revísalo',
      amountTitle: '¿Cuánto cuesta?',
      amountInstruction: 'Escribe el importe aproximado.',
      savedMessage: 'Pago previsto guardado.'
    },

    settings: {
      openButton: 'Ajustes y datos',
      title: 'Ajustes y datos',
      intro: 'Controla cómo lees la app y guarda una copia de tus datos en este dispositivo.',
      textSizeTitle: 'Tamaño del texto',
      textSizeInstruction: 'Elige el tamaño que te resulte más cómodo.',
      textSizeNormal: 'Normal',
      textSizeLarge: 'Grande',
      textSizeExtraLarge: 'Muy grande',
      backupTitle: 'Copia de tus datos',
      backupInstruction: 'Descarga una copia o restaura una copia anterior. La copia se queda en tu dispositivo.',
      exportButton: '⬇️ Descargar copia',
      importLabel: '⬆️ Restaurar copia',
      exportedMessage: 'Copia descargada.',
      exportUnavailable: 'Este navegador no permite descargar la copia.',
      importConfirm: 'Restaurar la copia sustituirá los datos actuales. ¿Quieres continuar?',
      importError: 'No se ha podido restaurar esa copia.',
      resetTitle: 'Borrar datos',
      resetInstruction: 'Borra el saldo, metas, movimientos, Tokens y preferencias de este dispositivo.',
      resetButton: 'Borrar todos mis datos',
      resetConfirm: 'Se borrarán todos tus datos de Okeymoney en este dispositivo. ¿Seguro que quieres continuar?'
    },

    categories: {
      food: 'Comida',
      fun: 'Ocio',
      transport: 'Transporte',
      clothes: 'Ropa',
      health: 'Salud',
      other: 'Otros'
    },

    goals: {
      title: 'Mis metas',
      newButton: '+ Nueva meta',
      empty: 'Todavía no tienes ninguna meta. ¡Crea la primera!',
      newTitle: '¿Qué quieres conseguir?',
      newInstruction: 'Elige un dibujo y escribe el nombre.',
      namePlaceholder: 'Por ejemplo: un juego',
      nameAria: 'Nombre de tu meta',
      targetTitle: '¿Cuánto cuesta?',
      targetInstruction: 'Escribe el precio.',
      addTitle: '¿Cuánto quieres guardar?',
      addInstruction: 'Escribe la cantidad.',
      availableBalance: 'Puedes guardar hasta {balance} sin dejar tu saldo en negativo.',
      overBalance: 'Esa cantidad es mayor que el dinero disponible.',
      addButton: '+ Añadir dinero',
      progressText: '{saved} de {target}',
      achievedBadge: '🏆 ¡Meta conseguida!',
      savedMessage: '¡Meta creada!',
      addedMessage: '¡Dinero guardado!',
      savedWithBalance: '¡Meta creada! Tu saldo sigue siendo {balance}.',
      addedWithBalance: '¡Dinero guardado! Ahora tienes {balance}.'
    },

    learn: {
      title: 'Aprender',
      comingSoon: 'Muy pronto podrás practicar aquí con juegos sobre el dinero.',
      walletLabel: 'Tu monedero de práctica',
      intro: 'Gana 🪙 practicando con actividades. Tu monedero de práctica es independiente del dinero real.',
      stateDone: '✓ Hecha',
      stateAvailable: '▶ Empezar',
      stateLocked: '🔒 Pronto',
      themes: {
        concepts: 'Conceptos básicos',
        daily: 'Vida cotidiana',
        safety: 'Seguridad'
      },
      activityTitle: {
        'concepts-money':  'Descubre cuánto vale cada moneda',
        'needs-vs-wants':  '¿Lo necesitas o lo quieres?',
        'budget-first':    '¿Qué te conviene comprar primero?',
        'go-shopping':     'Haz tu compra',
        'change-back':     'Comprueba tu cambio',
        'my-shopping-day': 'Organiza tu compra del día',
        'safe-money':      'Protege tu dinero'
      },
      activityDesc: {
        'concepts-money':  'Aprende a reconocer monedas y billetes por su valor.',
        'needs-vs-wants':  'Piensa si algo te hace falta o simplemente te apetece.',
        'budget-first':    'Ordena tus compras cuando el dinero es limitado.',
        'go-shopping':     'Haz una compra pequeña sin salirte del presupuesto.',
        'change-back':     'Comprueba cuánto dinero deben devolverte al pagar.',
        'my-shopping-day': 'Practica todo junto en una compra completa.',
        'safe-money':      'Aprende a reconocer transferencias extrañas y estafas.'
      }
    },

    wizard: {
      closeAria: 'Cerrar y no guardar'
    },

    keypad: {
      deleteDigit: 'Borrar el último dígito',
      clear: 'Borrar todo'
    },

    offline: {
      title: 'Sin conexión',
      heading: 'Sin conexión',
      body: 'No hemos podido cargar esta página. Comprueba tu conexión a Internet y vuelve a intentarlo.',
      homeLink: 'Volver a Okeymoney',
      metaDescription: 'Okeymoney está sin conexión: comprueba tu conexión a Internet y vuelve a intentarlo.'
    }
  }, 'es');
})();
