/* Okeymoney — English texts (parity with strings.es.js, checked by scripts/check.js). */
(function () {
  'use strict';
  App.i18n.register({
    title: 'Okeymoney',
    appName: 'Okeymoney',

    core: {
      config: 'Settings'
    },

    agent: {
      persona: 'Person',
      empresa: 'Shop',
      banco: 'Bank'
    },

    meta: {
      description: 'Your everyday money: what you have, what you spend, and what you want to achieve.'
    },

    tabs: {
      home: 'My money',
      goals: 'My goals',
      learn: 'See'
    },

    home: {
      saludo: 'Hi. What do you want to do today?',
      moreGoals: '+{n} more',
      anchorAria: 'Jump to {theme}',
      anchorNavAria: 'Jump to a part',
      balanceLabel: 'You have',
      editBalanceAria: 'Change how much money you have',
      editHint: 'Tap to change how much money you have',
      setBalanceTitle: 'How much money do you have?',
      setBalanceInstruction: 'Count your money and write how much you have now.',
      catalogueTitle: 'Your money',
      practiceBalance: 'Points available',
      inlineExpense: 'Add an expense',
      inlineExpenseDetail: 'Note a purchase and see how your balance changes.',
      movementsTitle: 'Recent movements',
      movementsEmpty: 'There are no movements yet.',
      insightsTitle: 'How your money is doing',
      insightsEmpty: 'After you note something down, this will show how your money is doing.',
      insightsSummary: 'You received {income}, spent {expenses} and saved {saving}.',
      insightsTopCategory: 'You have spent most on {category}: {amount}.',
      insightsCommitments: 'Payments you have noted: {amount}.',
      statementTitle: 'Your money at a glance',
      statementNote: 'Payments you note are not charged automatically.',
      statementAssets: 'Money you have',
      statementAssetsDetail: 'Money available and money saved in goals',
      statementLiabilities: 'Payments you noted',
      statementLiabilitiesDetail: 'Payments you noted to remember',
      statementIncome: 'Income',
      statementExpenses: 'Expenses',
      statementRecordedDetail: 'Recorded total',
      statementPosition: 'Money left:',
      statementDeficit: 'Your current balance is below zero. Review spending and ask for support if you need it.',
      controlTitle: 'Keep your money under control',
      controlNote: 'See what you have and what you have set aside.',
      controlBalance: 'Balance now',
      controlCommitted: 'Payments you noted',
      controlAvailable: 'Left after paying',
      controlLastPlan: 'Last purchase you prepared:',
      controlPlanDetail: 'limit {budget}, price {price}, difference {difference}',
      controlWarning: 'The payments you noted are higher than the money you have. Review the dates or amounts.',
      controlAction: 'Prepare another purchase',
      cycleTitle: 'Choose an action',
      cycleIntro: 'Note what comes in and out, or save money for a goal.',
      cycleDone: 'Done',
      cycle: {
        budgetTitle: 'Set aside money for your bills',
        budgetDetail: 'Save what you need for the month first.',
        budgetAction: 'Note a payment',
        incomeTitle: 'Note the money you receive',
        incomeDetail: 'Write down when money comes in.',
        incomeAction: 'Note money received',
        savingTitle: 'Save for something you want',
        savingDetail: 'Set money aside for a goal.',
        savingAction: 'Create a goal',
        spendingTitle: 'Note what you buy',
        spendingDetail: 'Write down what you spend your money on.',
        spendingAction: 'Note a purchase'
      },
      nextStep: {
        eyebrow: 'Today',
        title: 'Start here',
        balanceDetail: 'Count how much money you have now.',
        balanceAction: 'Add my balance',
        goalDetail: 'Choose something you want to save for.',
        goalAction: 'Create a goal',
        expenseDetail: 'Note a purchase and see how your balance changes.',
        expenseAction: 'Add an expense',
        budgetDetail: 'Set aside what you need for this month.',
        budgetAction: 'Prepare my budget',
        incomeDetail: 'Note the money you receive.',
        incomeAction: 'Record income',
        savingDetail: 'Set money aside for a goal.',
        savingAction: 'Save for a goal',
        note: 'You can stop at any time. Everything stays on your device.'
      }
    },

    blocks: {
      path: {
        didacticTitle: 'Your money, every day',
        didacticEyebrow: 'EVERYDAY SITUATIONS',
        didacticIntro: 'See what to do before you buy, pay or set money aside.',
        didacticCta: 'Organise my money',
        simulationEyebrow: 'PRACTICAL ACTIONS',
        simulationTitle: 'What you can do with your money',
        simulationIntro: 'Here you note your balance, what comes in and what you spend.',
        practicePhase: 'Try these situations',
        activityLink: '{title}',
        guideEyebrow: 'EVERYDAY DECISIONS',
        units: {
          money: { title: 'Count how much money you have', detail: 'Check your balance before buying or paying.', body: 'Before you buy or pay, count how much money you have available.' },
          choices: { title: 'Think before buying', detail: 'Tell apart what you need and what you want.', body: 'Before buying, pause and decide what you really need.' },
          budget: { title: 'Do not run out of money', detail: 'Put what you need first before spending.', body: 'When money cannot cover everything, decide what comes first.' },
          change: { title: 'Make sure you get the right change', detail: 'Check the price, payment and change.', body: 'Check the price, what you give and the change you receive.' },
          safety: { title: 'Avoid money scams', detail: 'Check messages and requests before moving money.', body: 'If something feels urgent or strange, pause and check who is asking.' }
        }
      },
      didactic: {
        activityProgress: '{done} of {total} situations tried',
        title: 'Your money, every day',
        eyebrow: 'Everyday situations',
        intro: 'See what to do in everyday money situations.',
        cta: 'See how to organise it',
        testLink: '{title}',
        openLink: 'See',
        detailBack: 'Back to the options',
        lessons: {
          moneyTitle: 'What you have',
          moneyDetail: 'Coins, notes and what each one is worth.',
          moneyBody: 'Before you buy, look at how much money you have. Count your coins and notes. Check that you have enough to pay.',
          moneyStep1: 'Count the coins and notes.',
          moneyStep2: 'Look at the value of each one.',
          moneyStep3: 'Add the values to know your balance.',
          moneyExample: 'You have a €2 coin and a €1 coin. You have €3 in total.',
          choicesTitle: 'What you need and what you want',
          choicesDetail: 'What you need and what you feel like buying.',
          choicesBody: 'Shops have many things you might like. Think about what you need. This helps you choose calmly.',
          choicesStep1: 'Ask if you need it today.',
          choicesStep2: 'If it can wait, it is a want.',
          choicesStep3: 'Cover what you need first.',
          choicesExample: 'Food for today is a need. A new game can wait.',
          budgetTitle: 'What you can spend',
          budgetDetail: 'What comes first when you cannot pay for everything.',
          budgetBody: 'Sometimes money cannot cover everything. Pay for what you need first. Leave the rest for later.',
          budgetStep1: 'Look at how much money you have.',
          budgetStep2: 'Write down payments that cannot wait.',
          budgetStep3: 'Use what remains for other spending.',
          budgetExample: 'If you have €20 and need to pay €12 for transport, you have €8 left for other things.',
          beforeBuyingTitle: 'Before you buy',
          beforeBuyingDetail: 'What to check before saying “yes”.',
          beforeBuyingBody: 'Before you tap your card or hand over money, pause for a moment. Ask whether you need it, can afford it and have compared other options.',
          beforeBuyingStep1: 'Pause and look at the price.',
          beforeBuyingStep2: 'Ask whether you need it and can afford it.',
          beforeBuyingStep3: 'Compare before deciding.',
          beforeBuyingExample: 'You see headphones on sale. You wait, compare the price and decide whether you really need them.',
          changeTitle: 'When you pay',
          changeDetail: 'What changes in your balance and whether the change is right.',
          changeBody: 'When you pay, your balance changes. Check the price, what you give and the change you receive so you know the calculation is right.',
          changeStep1: 'Look at the price.',
          changeStep2: 'Subtract the price from what you give.',
          changeStep3: 'Check that the change matches.',
          changeExample: 'You pay €5 for something that costs €2.30. The change should be €2.70.',
          savingTitle: 'What you want to achieve',
          savingDetail: 'How much you need and how to set it aside over time.',
          savingBody: 'A goal might be a gift, a phone or anything else you want to get. Decide what it costs, how much you can set aside and check your progress.',
          savingStep1: 'Choose something you want to get.',
          savingStep2: 'Look at how much it costs.',
          savingStep3: 'Set a little aside and check your progress.',
          savingExample: 'You want €20 headphones. You set aside €5. You already have one quarter.',
          safetyTitle: 'When something does not add up',
          safetyDetail: 'What to do when a message, call or request feels unusual.',
          safetyBody: 'An urgent message or request for money may not be what it seems. Pause, do not share your passwords and check who is asking through a trusted channel.',
          safetyStep1: 'Pause. Do not answer in a rush.',
          safetyStep2: 'Do not share passwords or codes.',
          safetyStep3: 'Check who is asking through another channel.',
          safetyExample: 'You get an urgent message from the bank. You do not click the link. You call a number you already know.',
          documentsTitle: 'When you buy something',
          documentsDetail: 'What happens from ordering something to paying for it.',
          documentsBody: 'A purchase has several moments. You order, receive and pay. Keep the papers so you remember what you bought and paid.',
          documentsStep1: 'Ask for what you want to buy.',
          documentsStep2: 'Check what arrives and the document.',
          documentsStep3: 'Keep the proof after paying.',
          documentsExample: 'You order a backpack. You check it arrives safely, look at the invoice and keep the receipt.',
          assetsTitle: 'What you have and what you owe',
          assetsDetail: 'The money you have, owe, receive and spend.',
          assetsBody: 'To understand your situation, look at what you have and what you owe. Also count money you expect to receive and payments you will need to make.',
          accountingTitle: 'What comes in and goes out',
          accountingDetail: 'What has happened to your money and what you can decide now.',
          accountingBody: 'Writing down money coming in and going out leaves a useful trail. When you review it, you know what happened. This helps you decide calmly.',
          assetLifecycleTitle: 'Things you buy also change',
          assetLifecycleDetail: 'What happens to the value of your things over time.',
          assetLifecycleBody: 'Things you buy can last, break or lose value. Before replacing something, see whether you can repair it, reuse it or keep using it.',
          returnRiskTitle: 'When your money could grow',
          returnRiskDetail: 'What you could gain, what you could lose, and for how long.',
          returnRiskBody: 'A possible gain always comes with conditions and risks. Before deciding, think about when you will need the money and how much you could lose.',
          investmentOperationsTitle: 'Moving money when you invest',
          investmentOperationsDetail: 'What happens when you buy, sell or move an investment.',
          investmentOperationsBody: 'When you invest, money can enter, leave or move somewhere else. Knowing what happened helps you understand your notes.',
          bankProductsTitle: 'Cards and accounts',
          bankProductsDetail: 'Where the money comes from and when you pay it.',
          bankProductsBody: 'Not all cards and accounts work in the same way. Before using one, check whether you pay from your balance, borrowed money or money you had set aside.',
          housingTitle: 'Where to live',
          housingDetail: 'What changes between renting and buying: money, payments and freedom.',
          housingBody: 'Choosing a home is not only about the monthly payment. Compare the upfront money, monthly costs, maintenance and how long you plan to stay.'
        }
      },
      guide: {
        title: 'More ideas for caring for your money',
        intro: 'Small decisions that help your money work with you each day.',
        techniqueEyebrow: 'When money comes in',
        techniqueTitle: 'Set aside what you need first',
        techniqueDetail: 'Separate money for housing, food, transport and bills.',
        principlesTitle: 'Habits for caring for your money',
        principles: {
          fixedTitle: 'Pay bills first',
          fixedDetail: 'Pay your bills before other spending.',
          saveTitle: 'Save something when money comes in',
          saveDetail: 'Set some money aside when money arrives.',
          pauseTitle: 'Pause before buying',
          pauseDetail: 'Compare and decide if you need it.',
          reduceTitle: 'Cut costs you do not use',
          reduceDetail: 'Review subscriptions and repeated costs.',
          marginTitle: 'Keep money for surprises',
          marginDetail: 'Do not spend your whole balance.',
          reviewTitle: 'Check your money each week',
          reviewDetail: 'Review what came in, went out and what is next.'
        },
        roadmapTitle: 'When you manage your money',
        roadmap: {
          organiseTitle: 'When you receive money',
          organiseDetail: 'Write down what comes in, goes out and needs paying.',
          planTitle: 'When you decide',
          planDetail: 'Set aside what you need and limit other spending.',
          improveTitle: 'When you review',
          improveDetail: 'Review your money and change the plan if needed.'
        }
      },
      test: {
        title: 'Everyday situations',
        intro: 'Decide what you would do in familiar situations.',
        walletLabel: 'Points',
        rewardHint: 'Each situation adds points once.',
        indexIntro: 'Choose a situation and try it at your pace.',
        indexHint: 'See topic'
      },
      simulation: {
        title: 'What you can do with your money',
        eyebrow: 'Practical actions',
        intro: 'Record your balance, income, spending and goals.',
        groups: {
          organise: 'Before spending',
          buy: 'When buying',
          check: 'To stay safe'
        },
        balanceTitle: 'My balance',
        balanceDetail: 'Tap to update how much money you have.',
        goalsTitle: 'My goals',
        goalsDetail: 'Save little by little for something you want.',
        expenseTitle: 'Add an expense',
        expenseDetail: 'Note a real purchase with euro money.',
        changeTitle: 'Check your change',
        changeDetail: 'Pay, work out the change and check the result.',
        safetyTitle: 'Check if it is safe',
        safetyDetail: 'Decide what to do before sending money.',
        rightsTitle: 'Know your rights',
        rightsDetail: 'Ask for receipts and make a claim.',
        communicationTitle: 'Talk clearly about money',
        communicationDetail: 'Rehearse questions, boundaries and asking for help.',
        emergencyTitle: 'Handle an unexpected problem',
        emergencyDetail: 'Make safe choices when plans suddenly change.',
        purchaseTitle: 'From order to payment',
        purchaseDetail: 'Review a purchase before you pay.',
        depreciationTitle: 'How much is something still worth?',
        depreciationDetail: 'Calculate how much value something loses over time.',
        depreciationQuestion: 'How much is this item still worth?',
        depreciationHint: 'Spread the loss across the months of use. Keep the value it still has.',
        depreciationFormula: 'Current value = price − ((price − value left) × months used ÷ months of use)',
        depreciationScenarios: {
          phoneScene: 'A phone cost {price}. It has been used for {elapsed} of its {life} months of use. It is still worth {residual}.',
          laptopScene: 'A laptop cost {price}. {elapsed} of its {life} months of use have passed. It is still worth {residual}.',
          bikeScene: 'A bicycle cost {price}. {elapsed} of its {life} months of use have passed. It is still worth {residual}.'
        },
        obsolescenceTitle: 'When something stops being useful',
        obsolescenceDetail: 'Compare repair, reuse and replacement before spending.',
        obsolescenceQuestion: 'Which decision best protects your money?',
        obsolescenceHint: 'Check support, repairability and the cost of each option.',
        obsolescenceScenarios: {
          phoneScene: 'Your phone still works, but security updates will end next year.',
          phoneUnsafe: 'I replace it today without comparing alternatives.',
          phoneSafe: 'I check support, repair and replacement costs before deciding.',
          laptopScene: 'Your laptop is slow for one task, although it still works for other things.',
          laptopUnsafe: 'I buy another one without trying a repair or a new use.',
          laptopSafe: 'I compare repair, reusing it for another task and buying new.',
          applianceScene: 'An appliance fails and replacement parts are no longer available.',
          applianceUnsafe: 'I buy the first one I see without checking energy use or warranty.',
          applianceSafe: 'I compare repair, energy use, warranty and replacement before paying.'
        },
        returnTitle: 'When your money can grow',
        returnDetail: 'Calculate how an amount could grow in an example.',
        returnQuestion: 'How much would you gain in this example?',
        returnHint: 'Multiply the amount by the percentage and give the result in euros.',
        returnFormula: 'Gain = amount × percentage',
        returnScenarios: {
          savingsScene: 'Imagine keeping {principal} for one year and gaining {rate}%.',
          bondScene: 'Imagine putting {principal} aside for one year and gaining {rate}%.',
          diversifiedScene: 'Imagine sharing {principal} between several companies for one year and gaining {rate}%.'
        },
        riskTitle: 'Earning more can also mean more risk',
        riskDetail: 'Think about when you will need the money and whether you can use it.',
        riskQuestion: 'Which decision best fits the goal?',
        riskHint: 'A possible gain is not certain. Think about when you will need the money and do not put it all in one place.',
        riskScenarios: {
          emergencyScene: 'You need €300 for an emergency that could happen this month.',
          emergencyUnsafe: 'I try to earn more even if I could lose the money or be unable to use it.',
          emergencySafe: 'I prioritise access to the money and low risk.',
          diversifyScene: 'You want to put €600 in one company or share it between several.',
          diversifyUnsafe: 'I put it all in one company because it promises to earn more.',
          diversifySafe: 'I compare costs and spread the money so I do not depend on one company.',
          horizonScene: 'Your goal is in two months and you cannot accept large changes in value.',
          horizonUnsafe: 'I choose a very volatile option because the expected percentage is high.',
          horizonSafe: 'I choose an option that fits the time I have and accept earning less.'
        },
        investmentTitle: 'What happens when you invest',
        investmentDetail: 'Tell apart buying, selling, collecting a gain and moving the money.',
        investmentQuestion: 'Which operation best describes the situation?',
        investmentHint: 'Notice whether money enters, leaves or changes the product holding the investment.',
        investmentScenarios: {
          buyScene: 'You have €100 available and place it in a fund after checking its conditions.',
          buyWrong: 'It is getting money back or selling.',
          buyCorrect: 'It is a purchase: you put money into an investment.',
          sellScene: 'You need money and ask to recover part of the fund.',
          sellWrong: 'It is putting new money into the fund.',
          sellCorrect: 'It is a sale: you get some money back.',
          returnScene: 'The investment generates €4 and the provider pays it into your account.',
          returnWrong: 'It is the money you originally contributed.',
          returnCorrect: 'It is a gain paid into your account.',
          transferScene: 'You move your investment from one product to another without withdrawing it to your account.',
          transferWrong: 'It is a new purchase with money you have just received.',
          transferCorrect: 'It is moving the money from one investment to another.'
        },
        bankProductsTitle: 'Cards and accounts',
        bankProductsDetail: 'Tell apart where the money comes from and when it is paid.',
        bankProductsQuestion: 'Which card or account best describes the situation?',
        bankProductsHint: 'Notice whether the money is yours, borrowed or set aside for saving.',
        bankProductsScenarios: {
          debitScene: 'You pay €18 with a card. The money leaves your account now.',
          debitWrong: 'It is a credit card: I will pay it later.',
          debitCorrect: 'It is a debit card: it uses the balance in your account.',
          creditScene: 'You pay €18 with a card and the provider charges you later under the agreement.',
          creditWrong: 'It is a debit card: it always leaves the balance immediately.',
          creditCorrect: 'It is a credit card: the provider advances the payment and charges you later.',
          prepaidScene: 'You load €30 onto a card and can only spend up to that amount.',
          prepaidWrong: 'It is credit: I can spend even when I have not loaded money.',
          prepaidCorrect: 'It is a prepaid card: you spend the balance you loaded.',
          currentScene: 'You want to receive income, pay bills and use a card for everyday spending.',
          currentWrong: 'It is a savings account meant only for putting money aside.',
          currentCorrect: 'It is an account for receiving money and paying for everyday things.',
          savingsScene: 'You want to set aside €200 for a goal and do not need it every week.',
          savingsWrong: 'It is a current account for paying daily bills.',
          savingsCorrect: 'It is a savings account: it helps set money aside for a reserve or goal.'
        },
        housingTitle: 'Renting or buying a home',
        housingDetail: 'Compare the upfront money, payments and how long you want to stay.',
        housingQuestion: 'Which decision analyses the situation best?',
        housingHint: 'Do not look only at the monthly payment: review upfront costs, recurring costs, maintenance and how long you will stay.',
        housingScenarios: {
          rentScene: 'You want to live in a city for two years and may move somewhere else afterwards.',
          rentWrong: 'I buy without calculating the deposit, loan, maintenance or time I will stay.',
          rentCorrect: 'I compare rent and its costs, considering the flexibility to move.',
          ownScene: 'You want to stay for many years and have savings for the upfront costs of buying.',
          ownWrong: 'I only look at the monthly payment and forget the loan, taxes, insurance and maintenance.',
          ownCorrect: 'I calculate the total cost of owning and check the payment fits my budget.',
          costsScene: 'You compare €850 monthly rent with a purchase that needs a deposit, loan and repairs.',
          costsWrong: 'I decide buying is always cheaper because the home will be mine eventually.',
          costsCorrect: 'I put the deposit, payments, costs, maintenance and time horizon in one comparison.',
          flexibilityScene: 'Your work may relocate you and you do not know how long you will stay in the area.',
          flexibilityWrong: 'I take on long debt without checking what happens if I need to move.',
          flexibilityCorrect: 'I value renting flexibility and review every condition before signing.',
          longTermScene: 'You have stable income, an emergency fund and a long-term housing plan.',
          longTermWrong: 'I assume owning is best for everyone without checking risks or budget.',
          longTermCorrect: 'I compare both options with my income, risks, costs and how long I will live there.'
        },
        planTitle: 'Plan a purchase',
        planDetail: 'Choose a budget before you spend.',
        planBudgetTitle: 'How much can you spend?',
        planBudgetInstruction: 'Write the limit you have for your purchase.',
        planChoiceTitle: 'Choose a purchase',
        planChoiceInstruction: 'Look at the price and category, then decide calmly.',
        planRemaining: 'Afterwards you would have {balance}.',
        planOverBudget: 'This purchase is over your budget.',
        planOverBalance: 'This purchase is higher than the money you have now.',
        planRecord: 'Record this expense',
        planBack: 'Choose another purchase',
        planItems: {
          bread: 'Bread · €2.00',
          bus: 'Bus ticket · €1.50',
          medicine: 'Medicine · €6.50',
          game: 'Game · €12.00'
        },
        changeQuestion: 'Write how much money you should get back.',
        changeHint: 'Subtract the purchase price from the money you give.',
        simulationCorrect: 'Well done. You checked the situation.',
        simulationFinished: 'You reviewed a real euro situation.',
        safetyQuestion: 'What would you do before sending or returning money?',
        safetyHint: 'Pause and check the request another way.',
        changeScenarios: {
          bakery: 'You pay €5.00 for a purchase costing €2.30.',
          pharmacy: 'You pay €10.00 for a purchase costing €6.50.',
          market: 'You pay €20.00 for a purchase costing €12.70.'
        },
        safetyScenarios: {
          bizumScene: 'You receive an unexpected €25 transfer and someone asks you to return it.',
          bizumUnsafe: 'I return the money to the number that messages me.',
          bizumSafe: 'I check the payment in my bank and contact the bank.',
          smsScene: 'You receive a text: “Your bank needs your login. Tap here”.',
          smsUnsafe: 'I open the link and type my login.',
          smsSafe: 'I do not open it. I use the official app or call the bank.',
          familyScene: 'An urgent message asks for €50 and says it is a family member.',
          familyUnsafe: 'I send the money straight away to help.',
          familySafe: 'I call the person using a number I already know.'
        },
        rightsQuestion: 'Which response best protects your rights?',
        rightsHint: 'Ask for information, keep proof and use an official complaints channel.',
        rightsScenarios: {
          returnScene: 'A shop does not explain how to return a faulty €18 product.',
          returnUnsafe: 'I leave without asking so I do not bother anyone.',
          returnSafe: 'I ask about the return policy and keep the receipt.',
          receiptScene: 'You pay €18 and are not given a receipt.',
          receiptUnsafe: 'I leave without checking anything.',
          receiptSafe: 'I ask for the receipt and check the amount is right.',
          chargeScene: 'Your account shows a €42 payment you do not recognise.',
          chargeUnsafe: 'I ignore it and keep using the account.',
          chargeSafe: 'I tell the bank and keep the payment details.'
        },
        communicationQuestion: 'Which way of talking helps you decide?',
        communicationHint: 'Ask calmly, say you need time and seek support when needed.',
        communicationScenarios: {
          priceScene: 'You do not understand the €30 price of a service before signing up.',
          priceUnsafe: 'I accept without asking to finish quickly.',
          priceSafe: 'I ask for the total price and what it includes first.',
          noScene: 'Someone keeps pushing you to buy something you do not want.',
          noUnsafe: 'I agree even though I am unsure.',
          noSafe: 'I say no and take time to think.',
          helpScene: 'A money decision feels confusing.',
          helpUnsafe: 'I hide the problem and decide blindly.',
          helpSafe: 'I tell someone I trust and ask for help.'
        },
        emergencyQuestion: 'What is the safest first step?',
        emergencyHint: 'Pause, protect your data and get support before paying or sharing information.',
        emergencyScenarios: {
          cardScene: 'You cannot find your bank card and think it is lost.',
          cardUnsafe: 'I wait a few days in case it turns up.',
          cardSafe: 'I freeze it in the app or call the bank straight away.',
          repairScene: 'Something important breaks and you are asked to pay for an urgent repair.',
          repairUnsafe: 'I pay the first price I am given without comparing.',
          repairSafe: 'I ask for a quote and check with someone before paying.',
          urgentScene: 'An unexpected €90 bill arrives and money is tight this month.',
          urgentUnsafe: 'I take a fast loan without reading the terms.',
          urgentSafe: 'I review priorities, talk to someone and look for safe options.'
        },
        purchaseIntro: 'A purchase can have four moments. Money only leaves when you pay.',
        purchaseNext: 'Next document',
        purchasePay: 'Confirm payment of {amount}',
        purchasePaid: 'Payment recorded. The expense is in your movements.',
        purchaseAfter: 'After the payment you would have {balance}.',
        purchaseOverBalance: 'This payment is higher than your current balance. Check it before confirming.',
        purchaseStages: {
          orderTitle: '1. Order',
          orderDetail: 'You request the product or service. You have not received or paid for it yet.',
          deliveryTitle: '2. What you receive',
          deliveryDetail: 'You check that what arrived matches what you ordered.',
          invoiceTitle: '3. Invoice',
          invoiceDetail: 'The invoice says what you must pay, how much and to whom.',
          paymentTitle: '4. Payment',
          paymentDetail: 'You pay after checking the order, what arrived and the invoice.'
        },
        purchaseScenarios: {
          backpack: 'A backpack costs €24.00.',
          shoes: 'A pair of shoes costs €36.00.',
          repair: 'A necessary repair costs €90.00.'
        }
      }
    },

    expense: {
      categoryTitle: 'What kind of spending is it?',
      categoryInstruction: 'Choose a category and see whether it is essential or optional.',
      amountTitle: 'How much did you spend?',
      amountInstruction: 'Write the price.',
      confirmTitle: 'Check your expense',
      confirmInstruction: 'If it looks right, save it.',
      saveButton: '✅ Save expense',
      savedMessage: 'Expense saved!',
      afterExpense: 'After this expense you will have {balance}.',
      overBalance: 'This expense is higher than your balance. Check the amount if you want.',
      savedWithBalance: 'Expense saved! You now have {balance}.',
      balanceSavedWithValue: 'Balance updated. You now have {balance}.'
    },

    income: {
      title: 'Where does the money come from?',
      instruction: 'Choose an option.',
      amountTitle: 'How much money did you receive?',
      amountInstruction: 'Write the amount.',
      saveButton: '✅ Save income',
      savedWithBalance: 'Money saved. You now have {balance}.',
      sources: {
        allowance: 'Pocket money',
        work: 'Work',
        gift: 'Gift',
        refund: 'Refund'
      }
    },

    commitments: {
      title: 'Planned payments',
      detail: 'Note payments you need to remember.',
      newButton: '+ Add planned payment',
      empty: "You don't have any planned payments yet.",
      nameTitle: 'Which payment do you want to remember?',
      nameInstruction: 'Write a short name.',
      namePlaceholder: 'For example: phone',
      nameAria: 'Planned payment name',
      dueDateLabel: 'When do you need it? (optional)',
      dueDateAria: 'Planned payment date',
      dueDate: 'Due {date}',
      overdue: 'Past date: review it',
      amountTitle: 'How much does it cost?',
      amountInstruction: 'Write the approximate amount.',
      savedMessage: 'Planned payment saved.'
    },

    settings: {
      openButton: 'Settings and data',
      title: 'Settings and data',
      intro: 'Choose how to read the app and keep a copy of your data on this device.',
      textSizeTitle: 'Text size',
      textSizeInstruction: 'Choose the size that feels most comfortable.',
      textSizeNormal: 'Normal',
      textSizeLarge: 'Large',
      textSizeExtraLarge: 'Extra large',
      backupTitle: 'Your data copy',
      backupInstruction: 'Download a copy or restore an earlier copy. The copy stays on your device.',
      exportButton: '⬇️ Download copy',
      importLabel: '⬆️ Restore copy',
      exportedMessage: 'Copy downloaded.',
      exportUnavailable: 'This browser cannot download the copy.',
      importConfirm: 'Restoring the copy will replace your current data. Continue?',
      importError: 'That copy could not be restored.',
      resetTitle: 'Delete data',
      resetInstruction: 'Delete the balance, goals, notes, points and preferences on this device.',
      resetButton: 'Delete all my data',
      resetConfirm: 'All your Okeymoney data on this device will be deleted. Are you sure?'
    },

    categories: {
      food: 'Food',
      fun: 'Fun',
      transport: 'Transport',
      clothes: 'Clothes',
      health: 'Health',
      other: 'Other',
      classification: {
        essential: 'Essential',
        discretionary: 'Optional'
      }
    },

    goals: {
      iconLabel: 'Icon {n}',
      title: 'My goals',
      newButton: '+ New goal',
      empty: "You don't have any goals yet. Create the first one!",
      newTitle: 'What do you want to get?',
      newInstruction: 'Choose a picture and write its name.',
      namePlaceholder: 'For example: a game',
      nameAria: 'Your goal name',
      targetTitle: 'How much does it cost?',
      targetInstruction: 'Write the price.',
      addTitle: 'How much do you want to save?',
      addInstruction: 'Write the amount.',
      availableBalance: 'You can save up to {balance} without making your balance negative.',
      overBalance: 'That amount is higher than the money available.',
      addButton: '+ Add money',
      progressText: '{saved} of {target}',
      achievedBadge: '🏆 Goal reached!',
      savedMessage: 'Goal created!',
      addedMessage: 'Money saved!',
      savedWithBalance: 'Goal created! Your balance is still {balance}.',
      addedWithBalance: 'Money saved! You now have {balance}.'
    },

    learn: {
      title: 'See',
      comingSoon: "Soon you'll be able to see money situations here.",
      walletLabel: 'Your points',
      intro: 'Look at situations and try decisions. Points are not real money.',
      stateDone: '✓ Seen',
      stateAvailable: '▶ See',
      stateLocked: '🔒 Soon',
      themes: {
        concepts: 'Basic concepts',
        daily: 'Everyday life',
        safety: 'Safety'
      },
      activityTitle: {
        "save-step-by-step": "Save towards a goal",
        "compare-prices": "Compare before paying",
        "monthly-payments": "Organise your payments",
        'concepts-money':  'Count your money',
        'needs-vs-wants':  'Do you need it or want it?',
        'budget-first':    'What is best to buy first?',
        'before-buying':   'Four questions before buying',
        'go-shopping':     'Make your purchase',
        'change-back':     'Check your change',
        'my-shopping-day': 'Plan your shopping day',
        'safe-money':      'Keep your money safe'
      },
      activityDesc: {
        'concepts-money':  'Look at, count, and change coins and banknotes.',
        'needs-vs-wants':  'Think about whether something is needed or simply wanted.',
        'budget-first':    'Put your purchases in order when money is limited.',
        'before-buying':   'Slow down impulse purchases and decide more calmly.',
        'go-shopping':     'Make a small purchase without going over budget.',
        'change-back':     'Check how much money you should get back.',
        'my-shopping-day': 'Do everything together in a full shop.',
        'safe-money':      'Spot unusual transfers and scams.'
      }
    },

    wizard: {
      closeAria: 'Close without saving'
    },

    keypad: {
      deleteDigit: 'Delete last digit',
      clear: 'Clear'
    },

    offline: {
      title: 'Offline',
      heading: 'Offline',
      body: "We couldn't load this page. Check your internet connection and try again.",
      homeLink: 'Back to Okeymoney',
      metaDescription: "Okeymoney is offline: check your internet connection and try again."
    }
  }, 'en');
})();
