/* Okeymoney — English texts (parity with strings.es.js, checked by scripts/check.js). */
(function () {
  'use strict';
  App.i18n.register({
    title: 'Okeymoney',
    appName: 'Okeymoney',

    agent: {
      persona: 'Person',
      empresa: 'Shop',
      banco: 'Bank'
    },

    meta: {
      description: 'Learn to manage your money: how much you have, how much you spend, and how much you save.'
    },

    tabs: {
      home: 'My money',
      goals: 'My goals',
      learn: 'Learn',
      newExpenseAria: 'Add an expense'
    },

    home: {
      saludo: 'Hi. What do you want to do today?',
      moreGoals: '+{n} more',
      anchorAria: 'Jump to {theme}',
      anchorNavAria: 'Jump to a block',
      balanceLabel: 'You have',
      editBalanceAria: 'Change how much money you have',
      editHint: 'Tap to change how much money you have',
      setBalanceTitle: 'How much money do you have?',
      setBalanceInstruction: 'Count your money and write how much you have now.',
      catalogueTitle: 'Learn with Okeymoney',
      practiceBalance: 'Tokens available',
      inlineExpense: 'Add an expense',
      inlineExpenseDetail: 'Practise a real purchase with euros.',
      movementsTitle: 'Recent movements',
      movementsEmpty: 'There are no movements yet.',
      insightsTitle: 'My money compass',
      insightsEmpty: 'After you record movements, this will show what is happening with your money.',
      insightsSummary: 'You received {income}, spent {expenses} and saved {saving}.',
      insightsTopCategory: 'Your main spending category is {category}: {amount}.',
      insightsCommitments: 'Planned payments noted: {amount}.',
      statementTitle: 'My money picture',
      statementNote: 'A simple guide: planned payments are not automatic bank debt.',
      statementAssets: 'Assets',
      statementAssetsDetail: 'Available money + savings in goals',
      statementLiabilities: 'Expected liabilities',
      statementLiabilitiesDetail: 'Payments you noted to remember',
      statementIncome: 'Income',
      statementExpenses: 'Expenses',
      statementRecordedDetail: 'Recorded total',
      statementPosition: 'Guidance position:',
      statementDeficit: 'Your current balance is below zero. Review spending and ask for support if you need it.',
      controlTitle: 'Control my finances',
      controlNote: 'Accounting tells you what happened. This control helps you decide what to do now.',
      controlBalance: 'Balance now',
      controlCommitted: 'Committed',
      controlAvailable: 'Available after commitments',
      controlLastPlan: 'Last planned purchase:',
      controlPlanDetail: 'budget {budget}, price {price}, difference {difference}',
      controlWarning: 'Your planned commitments are higher than your current balance. Review dates or amounts.',
      controlAction: 'Plan another purchase',
      cycleTitle: 'My money cycle',
      cycleIntro: 'Follow this order: decide, receive, save and use your money.',
      cycleDone: 'Step practised',
      cycle: {
        budgetTitle: 'Budget',
        budgetDetail: 'Decide how much you can spend.',
        budgetAction: 'Open budget',
        incomeTitle: 'Receive',
        incomeDetail: 'Record when money comes in.',
        incomeAction: 'Record income',
        savingTitle: 'Save',
        savingDetail: 'Set an amount aside for a goal.',
        savingAction: 'Open saving',
        spendingTitle: 'Spend',
        spendingDetail: 'Record what you buy.',
        spendingAction: 'Record spending'
      },
      nextStep: {
        eyebrow: 'Today',
        title: 'Your next step',
        balanceDetail: 'Start by counting how much money you have now.',
        balanceAction: 'Add my balance',
        goalDetail: 'You know your balance. Choose something to save for.',
        goalAction: 'Create a goal',
        expenseDetail: 'Practise a purchase and see how your balance changes.',
        expenseAction: 'Add an expense',
        budgetDetail: 'Start by deciding how much you can spend.',
        budgetAction: 'Prepare a budget',
        incomeDetail: 'Then record the money that comes in.',
        incomeAction: 'Record income',
        savingDetail: 'Now set an amount aside to save.',
        savingAction: 'Start saving',
        note: 'You can stop at any time. Everything stays on your device.'
      }
    },

    blocks: {
      didactic: {
        title: 'Learn step by step',
        intro: 'Understand money before you practise.',
        cta: 'Next, check what you know',
        lessons: {
          moneyTitle: 'Understand money',
          moneyDetail: 'Recognise coins, notes and their value.',
          choicesTitle: 'Think before choosing',
          choicesDetail: 'Tell apart what you need from what you want.',
          budgetTitle: 'Plan your money',
          budgetDetail: 'Put your purchases in order before spending.',
          changeTitle: 'Pay and check your change',
          changeDetail: 'Check that you get the right change back.',
          savingTitle: 'Save for a goal',
          savingDetail: 'Keep a little for something you want to get.',
          safetyTitle: 'Keep your money safe',
          safetyDetail: 'Learn to spot risks and ask for help.',
          documentsTitle: 'Follow the documents',
          documentsDetail: 'Understand what happens between ordering and paying.',
          assetsTitle: 'Read your money picture',
          assetsDetail: 'Tell apart what you have, what you owe, what comes in and what goes out.',
          accountingTitle: 'Record and organise',
          accountingDetail: 'Accounting records facts; control helps you decide.',
          assetLifecycleTitle: 'Care for the life of your things',
          assetLifecycleDetail: 'Calculate when they lose value and decide what to do when they become obsolete.',
          returnRiskTitle: 'Return and risk',
          returnRiskDetail: 'Compare what you could gain with what you could lose.',
          investmentOperationsTitle: 'Investment operations',
          investmentOperationsDetail: 'Recognise what happens when you buy, sell or move an investment.',
          bankProductsTitle: 'Bank cards and accounts',
          bankProductsDetail: 'Tell apart using your balance, credit or money you are putting aside.',
          housingTitle: 'Housing: rent or own',
          housingDetail: 'Compare costs, commitments and flexibility before deciding.'
        }
      },
      test: {
        title: 'Check what you know',
        intro: 'Answer situations and earn Tokens as you practise.',
        walletLabel: 'Practice Tokens',
        rewardHint: 'Each activity adds Tokens once.'
      },
      simulation: {
        title: 'Simulate real money situations',
        intro: 'Practise shopping, spending, saving and everyday decisions with euro money in a safe space.',
        balanceTitle: 'My balance',
        balanceDetail: 'Tap to update how much money you have.',
        goalsTitle: 'My goals',
        goalsDetail: 'Save little by little for something you want.',
        expenseTitle: 'Add an expense',
        expenseDetail: 'Practise a real purchase with euro money.',
        changeTitle: 'Check your change',
        changeDetail: 'Pay, work out the change and check the result.',
        safetyTitle: 'Check if it is safe',
        safetyDetail: 'Decide what to do before sending money.',
        rightsTitle: 'Know your rights',
        rightsDetail: 'Practise asking for receipts and making a claim.',
        communicationTitle: 'Talk clearly about money',
        communicationDetail: 'Rehearse questions, boundaries and asking for help.',
        emergencyTitle: 'Handle an unexpected problem',
        emergencyDetail: 'Make safe choices when plans suddenly change.',
        purchaseTitle: 'From order to payment',
        purchaseDetail: 'Practise order, delivery note, invoice and payment.',
        depreciationTitle: 'Calculate depreciation',
        depreciationDetail: 'Estimate how much value an item keeps over time.',
        depreciationQuestion: 'How much value does this item keep?',
        depreciationHint: 'Spread the loss across its useful-life months and keep the residual value.',
        depreciationFormula: 'Current value = price − ((price − residual value) × months used ÷ useful life)',
        depreciationScenarios: {
          phoneScene: 'A phone cost {price}. It has been used for {elapsed} of its {life} useful-life months. Its residual value is {residual}.',
          laptopScene: 'A laptop cost {price}. {elapsed} of its {life} useful-life months have passed, and it keeps a residual value of {residual}.',
          bikeScene: 'A bicycle cost {price}. {elapsed} of its {life} useful-life months have passed, and it keeps a residual value of {residual}.'
        },
        obsolescenceTitle: 'Decide when something is obsolete',
        obsolescenceDetail: 'Compare repair, reuse and replacement before spending.',
        obsolescenceQuestion: 'Which decision best protects your money?',
        obsolescenceHint: 'Check support, repairability and the cost of each option.',
        obsolescenceScenarios: {
          phoneScene: 'Your phone still works, but security updates will end next year.',
          phoneUnsafe: 'I replace it today without comparing alternatives.',
          phoneSafe: 'I check support, repair and replacement costs before deciding.',
          laptopScene: 'Your laptop is slow for one task, although it still works for other things.',
          laptopUnsafe: 'I buy another one without trying a repair or a new use.',
          laptopSafe: 'I compare repair, reusing it for another task and buying new.',
          applianceScene: 'An appliance fails and replacement parts are no longer available.',
          applianceUnsafe: 'I buy the first one I see without checking energy use or warranty.',
          applianceSafe: 'I compare repair, energy use, warranty and replacement before paying.'
        },
        returnTitle: 'Calculate a return',
        returnDetail: 'Calculate how an amount could grow in an example.',
        returnQuestion: 'How much would you gain in this example?',
        returnHint: 'Multiply the amount by the percentage and give the result in euros.',
        returnFormula: 'Gain = amount × percentage',
        returnScenarios: {
          savingsScene: 'Imagine keeping {principal} for one year with a gross return of {rate}%.',
          bondScene: 'Imagine placing {principal} for one year with a gross return of {rate}%.',
          diversifiedScene: 'Imagine a diversified investment of {principal} for one year with a gross return of {rate}%.'
        },
        riskTitle: 'Compare return and risk',
        riskDetail: 'Check the time horizon, access to money and diversification before deciding.',
        riskQuestion: 'Which decision best fits the goal?',
        riskHint: 'A possible return is not guaranteed: check the time, access and whether risk is spread.',
        riskScenarios: {
          emergencyScene: 'You need €300 for an emergency that could happen this month.',
          emergencyUnsafe: 'I chase the highest return even if I could lose or be unable to access the money.',
          emergencySafe: 'I prioritise access to the money and low risk.',
          diversifyScene: 'You want to invest €600 and can choose one company or several spread-out options.',
          diversifyUnsafe: 'I put it all in one company because it promises a higher return.',
          diversifySafe: 'I compare costs and spread the money so I do not depend on one company.',
          horizonScene: 'Your goal is in two months and you cannot accept large changes in value.',
          horizonUnsafe: 'I choose a very volatile option because the expected percentage is high.',
          horizonSafe: 'I choose an option that fits the time horizon and accept less potential return.'
        },
        investmentTitle: 'Recognise investment operations',
        investmentDetail: 'Tell apart buying, selling, collecting a return and transferring.',
        investmentQuestion: 'Which operation best describes the situation?',
        investmentHint: 'Notice whether money enters, leaves or changes the product holding the investment.',
        investmentScenarios: {
          buyScene: 'You have €100 available and place it in a fund after checking its conditions.',
          buyWrong: 'It is a redemption or a sale.',
          buyCorrect: 'It is a purchase or contribution to an investment.',
          sellScene: 'You need money and ask to recover part of the fund.',
          sellWrong: 'It is a new contribution to the fund.',
          sellCorrect: 'It is a sale or redemption.',
          returnScene: 'The investment generates €4 and the provider pays it into your account.',
          returnWrong: 'It is the money you originally contributed.',
          returnCorrect: 'It is collecting a return or dividend.',
          transferScene: 'You move your investment from one product to another without withdrawing it to your account.',
          transferWrong: 'It is a new purchase with money you have just received.',
          transferCorrect: 'It is a transfer between investment products.'
        },
        bankProductsTitle: 'Recognise cards and accounts',
        bankProductsDetail: 'Tell apart using your balance, credit or savings.',
        bankProductsQuestion: 'Which card or account best describes the situation?',
        bankProductsHint: 'Notice whether the money is yours, borrowed or set aside for saving.',
        bankProductsScenarios: {
          debitScene: 'You pay €18 with a card and the amount leaves your account balance straight away.',
          debitWrong: 'It is a credit card: I will pay it later.',
          debitCorrect: 'It is a debit card: it uses the balance in your account.',
          creditScene: 'You pay €18 with a card and the provider charges you later under the agreement.',
          creditWrong: 'It is a debit card: it always leaves the balance immediately.',
          creditCorrect: 'It is a credit card: the provider advances the payment and charges you later.',
          prepaidScene: 'You load €30 onto a card and can only spend up to that amount.',
          prepaidWrong: 'It is credit: I can spend even when I have not loaded money.',
          prepaidCorrect: 'It is a prepaid card: you spend the balance you loaded.',
          currentScene: 'You want to receive income, pay bills and use a card for everyday spending.',
          currentWrong: 'It is a savings account meant only for putting money aside.',
          currentCorrect: 'It is a current account for regular payments and money movements.',
          savingsScene: 'You want to set aside €200 for a goal and do not need it every week.',
          savingsWrong: 'It is a current account for paying daily bills.',
          savingsCorrect: 'It is a savings account: it helps set money aside for a reserve or goal.'
        },
        housingTitle: 'Compare renting and owning',
        housingDetail: 'Review costs, commitments, maintenance and time horizon.',
        housingQuestion: 'Which decision analyses the situation best?',
        housingHint: 'Do not look only at the monthly payment: review upfront costs, recurring costs, maintenance and how long you will stay.',
        housingScenarios: {
          rentScene: 'You want to live in a city for two years and may move somewhere else afterwards.',
          rentWrong: 'I buy without calculating the deposit, loan, maintenance or time I will stay.',
          rentCorrect: 'I compare rent and its costs, considering the flexibility to move.',
          ownScene: 'You want to stay for many years and have savings for the upfront costs of buying.',
          ownWrong: 'I only look at the monthly payment and forget the loan, taxes, insurance and maintenance.',
          ownCorrect: 'I calculate the total cost of owning and check the payment fits my budget.',
          costsScene: 'You compare €850 monthly rent with a purchase that needs a deposit, loan and repairs.',
          costsWrong: 'I decide buying is always cheaper because the home will be mine eventually.',
          costsCorrect: 'I put the deposit, payments, costs, maintenance and time horizon in one comparison.',
          flexibilityScene: 'Your work may relocate you and you do not know how long you will stay in the area.',
          flexibilityWrong: 'I take on long debt without checking what happens if I need to move.',
          flexibilityCorrect: 'I value renting flexibility and review every condition before signing.',
          longTermScene: 'You have stable income, an emergency fund and a long-term housing plan.',
          longTermWrong: 'I assume owning is best for everyone without checking risks or budget.',
          longTermCorrect: 'I compare both options with my income, risks, costs and personal horizon.'
        },
        planTitle: 'Plan a purchase',
        planDetail: 'Choose a budget before you spend.',
        planBudgetTitle: 'How much can you spend?',
        planBudgetInstruction: 'Write a budget for your purchase.',
        planChoiceTitle: 'Choose a purchase',
        planChoiceInstruction: 'Look at the price and decide calmly.',
        planRemaining: 'Afterwards you would have {balance}.',
        planOverBudget: 'This purchase is over your budget.',
        planOverBalance: 'This purchase is higher than the money you have now.',
        planRecord: 'Record this expense',
        planBack: 'Choose another purchase',
        planItems: {
          bread: 'Bread · €2.00',
          bus: 'Bus ticket · €1.50',
          medicine: 'Medicine · €6.50',
          game: 'Game · €12.00'
        },
        changeQuestion: 'Write how much money you should get back.',
        changeHint: 'Subtract the purchase price from the money you give.',
        simulationCorrect: 'Well done. You checked the situation.',
        simulationFinished: 'You practised a real euro situation.',
        safetyQuestion: 'What would you do before sending or returning money?',
        safetyHint: 'Pause and check the request another way.',
        changeScenarios: {
          bakery: 'You pay €5.00 for a purchase costing €2.30.',
          pharmacy: 'You pay €10.00 for a purchase costing €6.50.',
          market: 'You pay €20.00 for a purchase costing €12.70.'
        },
        safetyScenarios: {
          bizumScene: 'You receive an unexpected €25 transfer and someone asks you to return it.',
          bizumUnsafe: 'I return the money to the number that messages me.',
          bizumSafe: 'I check the payment in my bank and contact the bank.',
          smsScene: 'You receive a text: “Your bank needs your login. Tap here”.',
          smsUnsafe: 'I open the link and type my login.',
          smsSafe: 'I do not open it. I use the official app or call the bank.',
          familyScene: 'An urgent message asks for €50 and says it is a family member.',
          familyUnsafe: 'I send the money straight away to help.',
          familySafe: 'I call the person using a number I already know.'
        },
        rightsQuestion: 'Which response best protects your rights?',
        rightsHint: 'Ask for information, keep proof and use an official complaints channel.',
        rightsScenarios: {
          returnScene: 'A shop does not explain how to return a faulty €18 product.',
          returnUnsafe: 'I leave without asking so I do not bother anyone.',
          returnSafe: 'I ask about the return policy and keep the receipt.',
          receiptScene: 'You pay €18 and are not given a receipt.',
          receiptUnsafe: 'I leave without checking anything.',
          receiptSafe: 'I ask for the receipt and check the amount is right.',
          chargeScene: 'Your account shows a €42 payment you do not recognise.',
          chargeUnsafe: 'I ignore it and keep using the account.',
          chargeSafe: 'I tell the bank and keep the payment details.'
        },
        communicationQuestion: 'Which way of talking helps you decide?',
        communicationHint: 'Ask calmly, say you need time and seek support when needed.',
        communicationScenarios: {
          priceScene: 'You do not understand the €30 price of a service before signing up.',
          priceUnsafe: 'I accept without asking to finish quickly.',
          priceSafe: 'I ask for the total price and what it includes first.',
          noScene: 'Someone keeps pushing you to buy something you do not want.',
          noUnsafe: 'I agree even though I am unsure.',
          noSafe: 'I say no and take time to think.',
          helpScene: 'A money decision feels confusing.',
          helpUnsafe: 'I hide the problem and decide blindly.',
          helpSafe: 'I tell someone I trust and ask for help.'
        },
        emergencyQuestion: 'What is the safest first step?',
        emergencyHint: 'Pause, protect your data and get support before paying or sharing information.',
        emergencyScenarios: {
          cardScene: 'You cannot find your bank card and think it is lost.',
          cardUnsafe: 'I wait a few days in case it turns up.',
          cardSafe: 'I freeze it in the app or call the bank straight away.',
          repairScene: 'Something important breaks and you are asked to pay for an urgent repair.',
          repairUnsafe: 'I pay the first price I am given without comparing.',
          repairSafe: 'I ask for a quote and check with someone before paying.',
          urgentScene: 'An unexpected €90 bill arrives and money is tight this month.',
          urgentUnsafe: 'I take a fast loan without reading the terms.',
          urgentSafe: 'I review priorities, talk to someone and look for safe options.'
        },
        purchaseIntro: 'A purchase can have four moments. Money only leaves when you pay.',
        purchaseNext: 'Next document',
        purchasePay: 'Confirm payment of {amount}',
        purchasePaid: 'Payment recorded. The expense is in your movements.',
        purchaseAfter: 'After the payment you would have {balance}.',
        purchaseOverBalance: 'This payment is higher than your current balance. Check it before confirming.',
        purchaseStages: {
          orderTitle: '1. Order',
          orderDetail: 'You request the product or service. You have not received or paid for it yet.',
          deliveryTitle: '2. Delivery note',
          deliveryDetail: 'You check that what arrived matches what you ordered.',
          invoiceTitle: '3. Invoice',
          invoiceDetail: 'The invoice says what you must pay, how much and to whom.',
          paymentTitle: '4. Payment',
          paymentDetail: 'You pay after checking the order, what arrived and the invoice.'
        },
        purchaseScenarios: {
          backpack: 'A backpack costs €24.00.',
          shoes: 'A pair of shoes costs €36.00.',
          repair: 'A necessary repair costs €90.00.'
        }
      }
    },

    expense: {
      categoryTitle: 'What did you spend on?',
      categoryInstruction: 'Choose a picture.',
      amountTitle: 'How much did you spend?',
      amountInstruction: 'Write the price.',
      confirmTitle: 'Check your expense',
      confirmInstruction: 'If it looks right, save it.',
      saveButton: '✅ Save expense',
      savedMessage: 'Expense saved!',
      afterExpense: 'After this expense you will have {balance}.',
      overBalance: 'This expense is higher than your balance. Check the amount if you want.',
      savedWithBalance: 'Expense saved! You now have {balance}.',
      balanceSavedWithValue: 'Balance updated. You now have {balance}.'
    },

    income: {
      title: 'Where does the money come from?',
      instruction: 'Choose an option.',
      amountTitle: 'How much money did you receive?',
      amountInstruction: 'Write the amount.',
      saveButton: '✅ Save income',
      savedWithBalance: 'Money saved. You now have {balance}.',
      sources: {
        allowance: 'Pocket money',
        work: 'Work',
        gift: 'Gift',
        refund: 'Refund'
      }
    },

    commitments: {
      title: 'Planned payments',
      detail: 'Note payments you need to remember.',
      newButton: '+ Add planned payment',
      empty: "You don't have any planned payments yet.",
      nameTitle: 'Which payment do you want to remember?',
      nameInstruction: 'Write a short name.',
      namePlaceholder: 'For example: phone',
      nameAria: 'Planned payment name',
      dueDateLabel: 'When do you need it? (optional)',
      dueDateAria: 'Planned payment date',
      dueDate: 'Due {date}',
      overdue: 'Past date: review it',
      amountTitle: 'How much does it cost?',
      amountInstruction: 'Write the approximate amount.',
      savedMessage: 'Planned payment saved.'
    },

    settings: {
      openButton: 'Settings and data',
      title: 'Settings and data',
      intro: 'Choose how to read the app and keep a copy of your data on this device.',
      textSizeTitle: 'Text size',
      textSizeInstruction: 'Choose the size that feels most comfortable.',
      textSizeNormal: 'Normal',
      textSizeLarge: 'Large',
      textSizeExtraLarge: 'Extra large',
      backupTitle: 'Your data copy',
      backupInstruction: 'Download a copy or restore an earlier copy. The copy stays on your device.',
      exportButton: '⬇️ Download copy',
      importLabel: '⬆️ Restore copy',
      exportedMessage: 'Copy downloaded.',
      exportUnavailable: 'This browser cannot download the copy.',
      importConfirm: 'Restoring the copy will replace your current data. Continue?',
      importError: 'That copy could not be restored.',
      resetTitle: 'Delete data',
      resetInstruction: 'Delete the balance, goals, movements, Tokens and preferences on this device.',
      resetButton: 'Delete all my data',
      resetConfirm: 'All your Okeymoney data on this device will be deleted. Are you sure?'
    },

    categories: {
      food: 'Food',
      fun: 'Fun',
      transport: 'Transport',
      clothes: 'Clothes',
      health: 'Health',
      other: 'Other'
    },

    goals: {
      title: 'My goals',
      newButton: '+ New goal',
      empty: "You don't have any goals yet. Create the first one!",
      newTitle: 'What do you want to get?',
      newInstruction: 'Choose a picture and write its name.',
      namePlaceholder: 'For example: a game',
      nameAria: 'Your goal name',
      targetTitle: 'How much does it cost?',
      targetInstruction: 'Write the price.',
      addTitle: 'How much do you want to save?',
      addInstruction: 'Write the amount.',
      availableBalance: 'You can save up to {balance} without making your balance negative.',
      overBalance: 'That amount is higher than the money available.',
      addButton: '+ Add money',
      progressText: '{saved} of {target}',
      achievedBadge: '🏆 Goal reached!',
      savedMessage: 'Goal created!',
      addedMessage: 'Money saved!',
      savedWithBalance: 'Goal created! Your balance is still {balance}.',
      addedWithBalance: 'Money saved! You now have {balance}.'
    },

    learn: {
      title: 'Learn',
      comingSoon: "Soon you'll be able to practise here with games about money.",
      walletLabel: 'Your practice wallet',
      intro: 'Earn 🪙 by practising activities. Your practice wallet is separate from your real money.',
      stateDone: '✓ Done',
      stateAvailable: '▶ Start',
      stateLocked: '🔒 Soon',
      themes: {
        concepts: 'Basic concepts',
        daily: 'Everyday life',
        safety: 'Safety'
      },
      activityTitle: {
        'concepts-money':  'What is money?',
        'needs-vs-wants':  'Need or want',
        'budget-first':    'What do I buy first?',
        'go-shopping':     'Go shopping',
        'change-back':     'Working out change',
        'my-shopping-day': 'My shopping day',
        'safe-money':      'My money is safe'
      },
      activityDesc: {
        'concepts-money':  'Identify coins and banknotes by their value.',
        'needs-vs-wants':  'Tell apart what you need from what you want.',
        'budget-first':    'Decide what to buy first with a limited budget.',
        'go-shopping':     'Make a small purchase with a budget.',
        'change-back':     'Calculate how much change you should get.',
        'my-shopping-day': 'Practise everything together in a full shop.',
        'safe-money':      'Recognise strange transfers and scams, and what to do.'
      }
    },

    wizard: {
      closeAria: 'Close without saving'
    },

    keypad: {
      deleteDigit: 'Delete last digit',
      clear: 'Clear'
    },

    offline: {
      title: 'Offline',
      heading: 'Offline',
      body: "We couldn't load this page. Check your internet connection and try again.",
      homeLink: 'Back to Okeymoney',
      metaDescription: "Okeymoney is offline: check your internet connection and try again."
    }
  }, 'en');
})();
