/* Okeymoney — Textos en español (idioma por defecto y fuente de verdad). */
(function () {
  'use strict';
  App.i18n.register({
    title: 'Okeymoney',
    appName: 'Okeymoney',

    core: {
      config: 'Configuración'
    },

    agent: {
      persona: 'Persona',
      empresa: 'Empresa',
      banco: 'Banco'
    },

    meta: {
      description: 'Tu dinero de cada día: lo que tienes, lo que gastas y lo que quieres conseguir.'
    },

    tabs: {
      home: 'Mi dinero',
      goals: 'Mis metas',
      learn: 'Ver'
    },

    home: {
      saludo: 'Hola. ¿Qué quieres hacer hoy?',
      moreGoals: '+{n} más',
      anchorAria: 'Ir a {theme}',
      anchorNavAria: 'Ir a una parte',
      balanceLabel: 'Tienes',
      editBalanceAria: 'Cambiar cuánto dinero tienes',
      editHint: 'Toca para cambiar cuánto dinero tienes',
      setBalanceTitle: '¿Cuánto dinero tienes?',
      setBalanceInstruction: 'Cuenta tu dinero y escribe cuánto tienes ahora.',
      catalogueTitle: 'Tu dinero',
      practiceBalance: 'Puntos disponibles',
      inlineExpense: 'Registrar un gasto',
      inlineExpenseDetail: 'Anota una compra y mira cómo cambia tu saldo.',
      movementsTitle: 'Movimientos recientes',
      movementsEmpty: 'Todavía no hay movimientos.',
      insightsTitle: 'Así va tu dinero',
      insightsEmpty: 'Cuando anotes algo, aquí verás cómo va tu dinero.',
      insightsSummary: 'Has recibido {income}, gastado {expenses} y guardado {saving}.',
      insightsTopCategory: 'Has gastado más en {category}: {amount}.',
      insightsCommitments: 'Pagos que has apuntado: {amount}.',
      statementTitle: 'Tu dinero de un vistazo',
      statementNote: 'Los pagos que apuntas no se cobran solos.',
      statementAssets: 'Dinero que tienes',
      statementAssetsDetail: 'Dinero disponible y dinero guardado en metas',
      statementLiabilities: 'Pagos apuntados',
      statementLiabilitiesDetail: 'Pagos que has anotado para recordar',
      statementIncome: 'Ingresos',
      statementExpenses: 'Gastos',
      statementRecordedDetail: 'Total registrado',
      statementPosition: 'Dinero que te queda:',
      statementDeficit: 'Tu saldo actual está por debajo de cero. Revisa los gastos y pide apoyo si lo necesitas.',
      controlTitle: 'Tu dinero, bajo control',
      controlNote: 'Mira lo que tienes y lo que ya has reservado.',
      controlBalance: 'Saldo ahora',
      controlCommitted: 'Pagos apuntados',
      controlAvailable: 'Te quedará después de pagar',
      controlLastPlan: 'Última compra que preparaste:',
      controlPlanDetail: 'límite {budget}, precio {price}, diferencia {difference}',
      controlWarning: 'Los pagos que has apuntado son mayores que el dinero que tienes. Revisa las fechas o las cantidades.',
      controlAction: 'Preparar otra compra',
      cycleTitle: 'Elige una acción',
      cycleIntro: 'Apunta lo que entra y sale, o guarda dinero para una meta.',
      cycleDone: 'Hecho',
      cycle: {
        budgetTitle: 'Aparta el dinero de tus pagos',
        budgetDetail: 'Guarda primero lo que necesitas para el mes.',
        budgetAction: 'Apuntar un pago',
        incomeTitle: 'Apunta el dinero que recibes',
        incomeDetail: 'Escribe cuándo entra el dinero.',
        incomeAction: 'Anotar dinero recibido',
        savingTitle: 'Guarda para algo que quieres',
        savingDetail: 'Separa dinero para una meta.',
        savingAction: 'Crear una meta',
        spendingTitle: 'Apunta lo que compras',
        spendingDetail: 'Escribe en qué gastas el dinero.',
        spendingAction: 'Anotar una compra'
      },
      nextStep: {
        eyebrow: 'Hoy',
        title: 'Empieza por aquí',
        balanceDetail: 'Cuenta cuánto dinero tienes ahora.',
        balanceAction: 'Anotar mi saldo',
        goalDetail: 'Elige algo para lo que quieras ahorrar.',
        goalAction: 'Crear una meta',
        expenseDetail: 'Anota una compra y mira cómo cambia tu saldo.',
        expenseAction: 'Registrar un gasto',
        budgetDetail: 'Aparta lo que necesitas para este mes.',
        budgetAction: 'Preparar mi presupuesto',
        incomeDetail: 'Anota el dinero que recibes.',
        incomeAction: 'Registrar un ingreso',
        savingDetail: 'Guarda una cantidad para una meta.',
        savingAction: 'Guardar para una meta',
        note: 'Puedes parar cuando quieras. Todo queda en tu dispositivo.'
      }
    },

    blocks: {
      path: {
        didacticTitle: 'Tu dinero, en el día a día',
        didacticEyebrow: 'SITUACIONES COTIDIANAS',
        didacticIntro: 'Mira qué hacer antes de comprar, pagar o guardar dinero.',
        didacticCta: 'Organizar mi dinero',
        simulationEyebrow: 'ACCIONES PRÁCTICAS',
        simulationTitle: 'Lo que puedes hacer con tu dinero',
        simulationIntro: 'Aquí apuntas tu saldo, lo que recibes y lo que gastas.',
        practicePhase: 'Prueba estas situaciones',
        activityLink: '{title}',
        guideEyebrow: 'DECISIONES COTIDIANAS',
        units: {
          money: { title: 'Cuenta cuánto dinero tienes', detail: 'Comprueba tu saldo antes de comprar o pagar.', body: 'Antes de comprar o pagar, cuenta cuánto dinero tienes disponible.' },
          choices: { title: 'Antes de comprar, piénsalo', detail: 'Distingue lo que necesitas de lo que quieres.', body: 'Antes de comprar, para y decide qué necesitas de verdad.' },
          budget: { title: 'No te quedes sin dinero', detail: 'Ordena lo que necesitas antes de gastar.', body: 'Cuando el dinero no llega para todo, decide qué va primero.' },
          change: { title: 'Que no te cobren de más', detail: 'Comprueba el precio, el pago y la vuelta.', body: 'Comprueba el precio, lo que entregas y la vuelta que recibes.' },
          safety: { title: 'Evita engaños con tu dinero', detail: 'Comprueba mensajes y peticiones antes de mover dinero.', body: 'Si algo parece urgente o raro, para y comprueba quién te lo pide.' }
        }
      },
      didactic: {
        activityProgress: '{done} de {total} situaciones hechas',
        title: 'Tu dinero, en el día a día',
        eyebrow: 'Situaciones cotidianas',
        intro: 'Mira qué hacer en situaciones habituales con dinero.',
        cta: 'Ver cómo organizarte',
        testLink: '{title}',
        openLink: 'Ver',
        detailBack: 'Volver a las opciones',
        lessons: {
          moneyTitle: 'Lo que tienes',
          moneyDetail: 'Monedas, billetes y cuánto vale cada uno.',
          moneyBody: 'Antes de comprar, mira cuánto dinero tienes. Cuenta tus monedas y billetes. Comprueba que llevas lo que cuesta.',
          moneyStep1: 'Cuenta las monedas y los billetes.',
          moneyStep2: 'Mira el valor de cada uno.',
          moneyStep3: 'Suma los valores para saber tu saldo.',
          moneyExample: 'Tienes una moneda de 2 € y otra de 1 €. En total tienes 3 €.',
          choicesTitle: 'Lo que necesitas y lo que quieres',
          choicesDetail: 'Lo que te hace falta y lo que te apetece comprar.',
          choicesBody: 'En una tienda hay muchas cosas que pueden gustarte. Piensa qué necesitas. Así eliges con calma.',
          choicesStep1: 'Pregunta si te hace falta para hoy.',
          choicesStep2: 'Si puede esperar, es un deseo.',
          choicesStep3: 'Primero cubre lo que necesitas.',
          choicesExample: 'La comida para hoy es una necesidad. Un juego nuevo puede esperar.',
          budgetTitle: 'Lo que puedes gastar',
          budgetDetail: 'Qué va primero cuando no puedes pagarlo todo.',
          budgetBody: 'A veces el dinero no llega para todo. Paga primero lo necesario. Deja para después lo que puede esperar.',
          budgetStep1: 'Mira cuánto dinero tienes.',
          budgetStep2: 'Apunta los pagos que no pueden esperar.',
          budgetStep3: 'Usa lo que queda para otros gastos.',
          budgetExample: 'Si tienes 20 € y necesitas pagar 12 € de transporte, te quedan 8 € para otras cosas.',
          beforeBuyingTitle: 'Antes de comprar',
          beforeBuyingDetail: 'Lo que conviene revisar antes de decir «sí».',
          beforeBuyingBody: 'Antes de sacar la tarjeta o entregar el dinero, para un momento. Pregúntate si lo necesitas, si puedes pagarlo y si has comparado otras opciones.',
          beforeBuyingStep1: 'Para y mira el precio.',
          beforeBuyingStep2: 'Pregunta si lo necesitas y si puedes pagarlo.',
          beforeBuyingStep3: 'Compara antes de decidir.',
          beforeBuyingExample: 'Ves unos auriculares en oferta. Esperas, comparas el precio y decides si de verdad los necesitas.',
          changeTitle: 'Cuando pagas',
          changeDetail: 'Qué cambia en tu saldo y si la vuelta es correcta.',
          changeBody: 'Cuando pagas, tu saldo cambia. Comprueba el precio, lo que entregas y la vuelta que recibes para saber que la cuenta está bien.',
          changeStep1: 'Mira cuánto cuesta.',
          changeStep2: 'Resta el precio a lo que entregas.',
          changeStep3: 'Comprueba que la vuelta coincide.',
          changeExample: 'Pagas 5 € por algo que cuesta 2,30 €. La vuelta debe ser 2,70 €.',
          savingTitle: 'Lo que quieres conseguir',
          savingDetail: 'Cuánto necesitas y cómo apartarlo poco a poco.',
          savingBody: 'Una meta puede ser un regalo, un teléfono o cualquier cosa que quieras conseguir. Decide cuánto cuesta, cuánto puedes apartar y revisa cómo avanzas.',
          savingStep1: 'Elige algo que quieras conseguir.',
          savingStep2: 'Mira cuánto cuesta.',
          savingStep3: 'Aparta un poco y revisa tu avance.',
          savingExample: 'Quieres unos auriculares de 20 €. Apartas 5 €. Ya tienes una cuarta parte.',
          safetyTitle: 'Cuando algo no cuadra',
          safetyDetail: 'Qué hacer ante un mensaje, una llamada o una petición extraña.',
          safetyBody: 'Un mensaje urgente o una petición de dinero no siempre es lo que parece. Para, no compartas tus claves y comprueba quién te lo pide por un canal conocido.',
          safetyStep1: 'Para. No respondas con prisa.',
          safetyStep2: 'No compartas claves ni códigos.',
          safetyStep3: 'Comprueba quién te lo pide por otro canal.',
          safetyExample: 'Recibes un mensaje urgente del banco. No pinchas el enlace. Llamas al número que ya conoces.',
          documentsTitle: 'Cuando haces una compra',
          documentsDetail: 'Qué ocurre desde que pides algo hasta que lo pagas.',
          documentsBody: 'Una compra pasa por varios momentos. Pides, recibes y pagas. Guarda los papeles para recordar qué compraste y cuánto pagaste.',
          documentsStep1: 'Pide lo que quieres comprar.',
          documentsStep2: 'Comprueba lo que recibes y el documento.',
          documentsStep3: 'Guarda el comprobante después de pagar.',
          documentsExample: 'Pides una mochila. Compruebas que llega bien, miras la factura y guardas el recibo.',
          assetsTitle: 'Lo que tienes y lo que debes',
          assetsDetail: 'El dinero que tienes, el que debes y el que entra y sale.',
          assetsBody: 'Para hacerte una idea de tu situación, mira lo que tienes y lo que debes. También cuenta el dinero que esperas recibir y los pagos que tendrás que hacer.',
          accountingTitle: 'Lo que entra y lo que sale',
          accountingDetail: 'Lo que ha pasado con tu dinero y lo que puedes decidir ahora.',
          accountingBody: 'Anotar el dinero que entra y sale te deja una pista. Al revisarla, sabes qué ha pasado. Así decides con más calma.',
          assetLifecycleTitle: 'Lo que compras también cambia',
          assetLifecycleDetail: 'Qué pasa con el valor de tus cosas con el paso del tiempo.',
          assetLifecycleBody: 'Las cosas que compras pueden durar, estropearse o perder valor. Antes de sustituirlas, mira si puedes repararlas, reutilizarlas o seguir usándolas.',
          returnRiskTitle: 'Cuando tu dinero busca crecer',
          returnRiskDetail: 'Qué puedes ganar, qué puedes perder y durante cuánto tiempo.',
          returnRiskBody: 'Una posible ganancia siempre va acompañada de condiciones y riesgos. Antes de decidir, piensa cuándo necesitarás el dinero y cuánto podrías perder.',
          investmentOperationsTitle: 'Mover dinero al invertir',
          investmentOperationsDetail: 'Qué pasa al comprar, vender o mover una inversión.',
          investmentOperationsBody: 'Al invertir, el dinero puede entrar, salir o cambiar de sitio. Saber qué ha pasado te ayuda a entender tus apuntes.',
          bankProductsTitle: 'Tarjetas y cuentas',
          bankProductsDetail: 'De dónde sale el dinero y cuándo lo pagas.',
          bankProductsBody: 'No todas las tarjetas ni todas las cuentas funcionan igual. Antes de usarlas, comprueba si pagas con tu saldo, con dinero prestado o con dinero que habías reservado.',
          housingTitle: 'Dónde vivir',
          housingDetail: 'Qué cambia entre alquilar y comprar: dinero, pagos y libertad.',
          housingBody: 'Elegir una vivienda no es solo mirar una cuota. Compara el dinero inicial, los pagos de cada mes, el mantenimiento y cuánto tiempo quieres quedarte.'
        }
      },
      guide: {
        title: 'Más ideas para cuidar tu dinero',
        intro: 'Decisiones pequeñas para que tu dinero te acompañe cada día.',
        techniqueEyebrow: 'Cuando te llega el dinero',
        techniqueTitle: 'Aparta primero lo que necesitas',
        techniqueDetail: 'Separa el dinero de vivienda, comida, transporte y recibos.',
        principlesTitle: 'Hábitos para cuidar tu dinero',
        principles: {
          fixedTitle: 'Paga primero los recibos',
          fixedDetail: 'Paga tus recibos antes de otros gastos.',
          saveTitle: 'Guarda algo al recibir dinero',
          saveDetail: 'Aparta una cantidad cuando entra dinero.',
          pauseTitle: 'Espera antes de comprar',
          pauseDetail: 'Compara y decide si lo necesitas.',
          reduceTitle: 'Quita gastos que no usas',
          reduceDetail: 'Revisa suscripciones y gastos repetidos.',
          marginTitle: 'Guarda algo para imprevistos',
          marginDetail: 'No gastes todo el saldo.',
          reviewTitle: 'Mira tu dinero cada semana',
          reviewDetail: 'Revisa qué entró, qué salió y qué viene.'
        },
        roadmapTitle: 'Cuando manejas tu dinero',
        roadmap: {
          organiseTitle: 'Cuando recibes dinero',
          organiseDetail: 'Apunta lo que recibes, gastas y tienes que pagar.',
          planTitle: 'Cuando decides',
          planDetail: 'Aparta lo necesario y pon un límite a otros gastos.',
          improveTitle: 'Cuando revisas',
          improveDetail: 'Revisa tu dinero y cambia el plan si hace falta.'
        }
      },
      test: {
        title: 'Situaciones de cada día',
        intro: 'Decide qué harías en situaciones habituales.',
        walletLabel: 'Puntos',
        rewardHint: 'Cada situación suma puntos una vez.',
        indexIntro: 'Elige una situación y pruébala a tu ritmo.',
        indexHint: 'Ver tema'
      },
      simulation: {
        title: 'Lo que puedes hacer con tu dinero',
        eyebrow: 'Acciones prácticas',
        intro: 'Apunta tu saldo, tus ingresos, tus gastos y tus metas.',
        groups: {
          organise: 'Antes de gastar',
          buy: 'Al comprar',
          check: 'Para protegerte'
        },
        balanceTitle: 'Mi saldo',
        balanceDetail: 'Toca para actualizar cuánto dinero tienes.',
        goalsTitle: 'Mis metas',
        goalsDetail: 'Ahorra poco a poco para algo que quieres.',
        expenseTitle: 'Registrar un gasto',
        expenseDetail: 'Anota una compra real con dinero en euros.',
        changeTitle: 'Comprueba la vuelta',
        changeDetail: 'Paga, calcula la vuelta y comprueba el resultado.',
        safetyTitle: 'Comprueba si es seguro',
        safetyDetail: 'Decide qué hacer antes de enviar dinero.',
        rightsTitle: 'Conoce tus derechos',
        rightsDetail: 'Reclama y pide tus comprobantes.',
        communicationTitle: 'Habla claro sobre dinero',
        communicationDetail: 'Ensaya preguntas, límites y pedir ayuda.',
        emergencyTitle: 'Responde a un imprevisto',
        emergencyDetail: 'Toma decisiones seguras cuando algo cambia.',
        purchaseTitle: 'Del pedido al pago',
        purchaseDetail: 'Revisa una compra antes de pagar.',
        depreciationTitle: 'Cuánto vale aún una cosa',
        depreciationDetail: 'Calcula cuánto valor pierde una cosa con el tiempo.',
        depreciationQuestion: '¿Cuánto vale aún esta cosa?',
        depreciationHint: 'Reparte la pérdida entre los meses de uso. Conserva el valor que aún tiene.',
        depreciationFormula: 'Valor actual = precio − ((precio − valor que queda) × meses usados ÷ meses de uso)',
        depreciationScenarios: {
          phoneScene: 'Un teléfono costó {price}. Se ha usado {elapsed} de sus {life} meses de uso. Aún vale {residual}.',
          laptopScene: 'Un portátil costó {price}. Han pasado {elapsed} de sus {life} meses de uso. Aún vale {residual}.',
          bikeScene: 'Una bicicleta costó {price}. Han pasado {elapsed} de sus {life} meses de uso. Aún vale {residual}.'
        },
        obsolescenceTitle: 'Cuando una cosa deja de servir',
        obsolescenceDetail: 'Compara reparar, reutilizar o sustituir antes de gastar.',
        obsolescenceQuestion: '¿Qué decisión protege mejor tu dinero?',
        obsolescenceHint: 'Comprueba si aún recibe soporte, si se puede reparar y cuánto cuesta cada opción.',
        obsolescenceScenarios: {
          phoneScene: 'Tu teléfono todavía funciona, pero las actualizaciones de seguridad terminarán el año que viene.',
          phoneUnsafe: 'Lo cambio hoy sin comparar alternativas.',
          phoneSafe: 'Compruebo soporte, reparación y coste de sustituirlo antes de decidir.',
          laptopScene: 'Tu portátil va lento para una tarea, aunque todavía sirve para otras cosas.',
          laptopUnsafe: 'Compro otro sin probar una reparación o darle otro uso.',
          laptopSafe: 'Comparo reparar, reutilizarlo para otra tarea y comprar uno nuevo.',
          applianceScene: 'Un electrodoméstico falla y ya no encuentras piezas de repuesto.',
          applianceUnsafe: 'Compro el primero que veo sin revisar consumo ni garantía.',
          applianceSafe: 'Comparo reparación, consumo, garantía y sustitución antes de pagar.'
        },
        returnTitle: 'Cuando tu dinero puede crecer',
        returnDetail: 'Calcula cuánto puede crecer una cantidad en un ejemplo.',
        returnQuestion: '¿Cuánto ganarías en este ejemplo?',
        returnHint: 'Multiplica la cantidad por el porcentaje y expresa el resultado en euros.',
        returnFormula: 'Ganancia = cantidad × porcentaje',
        returnScenarios: {
          savingsScene: 'Imagina que guardas {principal} durante un año y ganas un {rate}%.',
          bondScene: 'Imagina que pones {principal} durante un año y ganas un {rate}%.',
          diversifiedScene: 'Imagina que repartes {principal} entre varias empresas durante un año y ganas un {rate}%.'
        },
        riskTitle: 'Ganar más también puede tener riesgo',
        riskDetail: 'Piensa cuándo necesitarás el dinero y si podrás usarlo.',
        riskQuestion: '¿Qué decisión encaja mejor con el objetivo?',
        riskHint: 'Una ganancia posible no es segura. Mira cuándo necesitarás el dinero y no lo pongas todo en un solo sitio.',
        riskScenarios: {
          emergencyScene: 'Necesitas 300 € para una emergencia que puede ocurrir este mes.',
          emergencyUnsafe: 'Busco ganar más aunque pueda perder el dinero o no poder usarlo.',
          emergencySafe: 'Priorizo que el dinero esté disponible y tenga poco riesgo.',
          diversifyScene: 'Quieres poner 600 € en una empresa o repartirlos entre varias.',
          diversifyUnsafe: 'Pongo todo en una sola empresa porque promete ganar más.',
          diversifySafe: 'Comparo costes y reparto el dinero para no depender de una sola empresa.',
          horizonScene: 'Tu objetivo está a dos meses y no puedes aceptar grandes cambios de valor.',
          horizonUnsafe: 'Elijo una opción muy variable porque el porcentaje esperado es alto.',
          horizonSafe: 'Elijo una opción que encaja con el tiempo que tengo y acepto ganar menos.'
        },
        investmentTitle: 'Qué pasa cuando inviertes',
        investmentDetail: 'Distingue comprar, vender, cobrar una ganancia y mover el dinero.',
        investmentQuestion: '¿Qué operación describe mejor la situación?',
        investmentHint: 'Fíjate en si entra dinero, sale dinero o cambia el producto donde está invertido.',
        investmentScenarios: {
          buyScene: 'Tienes 100 € disponibles y los colocas en un fondo después de revisar sus condiciones.',
          buyWrong: 'Es recuperar dinero o vender.',
          buyCorrect: 'Es una compra: pones dinero en una inversión.',
          sellScene: 'Necesitas dinero y solicitas recuperar una parte del fondo.',
          sellWrong: 'Es poner dinero nuevo en el fondo.',
          sellCorrect: 'Es una venta: recuperas parte del dinero.',
          returnScene: 'La inversión genera 4 € y la entidad los abona en tu cuenta.',
          returnWrong: 'Es el dinero que aportaste inicialmente.',
          returnCorrect: 'Es una ganancia que llega a tu cuenta.',
          transferScene: 'Mueves tu inversión de un producto a otro sin retirarla a tu cuenta.',
          transferWrong: 'Es una compra nueva con dinero que acabas de recibir.',
          transferCorrect: 'Es mover el dinero de una inversión a otra.'
        },
        bankProductsTitle: 'Tarjetas y cuentas',
        bankProductsDetail: 'Distingue de dónde sale el dinero y cuándo se paga.',
        bankProductsQuestion: '¿Qué tarjeta o cuenta describe mejor la situación?',
        bankProductsHint: 'Fíjate en si el dinero ya es tuyo, si te lo prestan o si está reservado para ahorrar.',
        bankProductsScenarios: {
          debitScene: 'Pagas 18 € con una tarjeta. El dinero sale ahora de tu cuenta.',
          debitWrong: 'Es una tarjeta de crédito: lo pagaré más adelante.',
          debitCorrect: 'Es una tarjeta de débito: usa el saldo de tu cuenta.',
          creditScene: 'Pagas 18 € con una tarjeta y la entidad te cobra después según el contrato.',
          creditWrong: 'Es una tarjeta de débito: siempre sale al instante del saldo.',
          creditCorrect: 'Es una tarjeta de crédito: la entidad adelanta el pago y después lo cobra.',
          prepaidScene: 'Cargas 30 € en una tarjeta y solo puedes gastar hasta esa cantidad.',
          prepaidWrong: 'Es crédito: puedo gastar aunque no haya cargado dinero.',
          prepaidCorrect: 'Es una tarjeta prepago: gastas el saldo que has cargado.',
          currentScene: 'Quieres recibir ingresos, pagar recibos y usar una tarjeta para el día a día.',
          currentWrong: 'Es una cuenta de ahorro pensada solo para guardar dinero.',
          currentCorrect: 'Es una cuenta para recibir dinero y pagar en el día a día.',
          savingsScene: 'Quieres separar 200 € para una meta y no necesitas usarlos cada semana.',
          savingsWrong: 'Es una cuenta corriente para pagar recibos diarios.',
          savingsCorrect: 'Es una cuenta de ahorro: ayuda a separar dinero para una reserva o meta.'
        },
        housingTitle: 'Alquilar o comprar una vivienda',
        housingDetail: 'Compara el dinero inicial, los pagos y el tiempo que quieres quedarte.',
        housingQuestion: '¿Qué decisión analiza mejor esta situación?',
        housingHint: 'No mires solo la cuota: revisa pagos iniciales, gastos recurrentes, mantenimiento y cuánto tiempo estarás allí.',
        housingScenarios: {
          rentScene: 'Quieres vivir en una ciudad durante dos años y quizá cambiar de lugar después.',
          rentWrong: 'Elijo comprar sin calcular entrada, préstamo, mantenimiento ni tiempo de permanencia.',
          rentCorrect: 'Comparo un alquiler y sus gastos, valorando la flexibilidad de poder cambiar.',
          ownScene: 'Quieres quedarte muchos años y tienes ahorros para los gastos iniciales de una compra.',
          ownWrong: 'Solo miro la cuota mensual y olvido préstamo, impuestos, seguro y mantenimiento.',
          ownCorrect: 'Calculo el coste total de ser propietario y compruebo que la cuota cabe en mi presupuesto.',
          costsScene: 'Comparas un alquiler de 850 € al mes con una compra que exige entrada, préstamo y reparaciones.',
          costsWrong: 'Concluyo que comprar siempre es más barato porque al final la vivienda es mía.',
          costsCorrect: 'Pongo en la misma tabla entrada, cuotas, gastos, mantenimiento y tiempo previsto.',
          flexibilityScene: 'Tu trabajo puede trasladarte y no sabes cuánto tiempo seguirás en la zona.',
          flexibilityWrong: 'Firmo una deuda larga sin revisar qué pasaría si necesito mudarme.',
          flexibilityCorrect: 'Valoro la flexibilidad del alquiler y reviso todas las condiciones antes de firmar.',
          longTermScene: 'Tienes ingresos estables, un fondo para imprevistos y un plan de vivienda a largo plazo.',
          longTermWrong: 'Doy por hecho que comprar es mejor para cualquiera sin revisar riesgos ni presupuesto.',
          longTermCorrect: 'Comparo ambas opciones con mis ingresos, riesgos, gastos y el tiempo que viviré allí.'
        },
        planTitle: 'Planifica una compra',
        planDetail: 'Elige un presupuesto antes de gastar.',
        planBudgetTitle: '¿Cuánto puedes gastar?',
        planBudgetInstruction: 'Escribe el límite que tienes para tu compra.',
        planChoiceTitle: 'Elige una compra',
        planChoiceInstruction: 'Mira el precio, su categoría y decide con calma.',
        planRemaining: 'Después te quedarían {balance}.',
        planOverBudget: 'Esta compra supera tu presupuesto.',
        planOverBalance: 'Esta compra supera el dinero que tienes ahora.',
        planRecord: 'Registrar este gasto',
        planBack: 'Elegir otra compra',
        planItems: {
          bread: 'Pan · 2,00 €',
          bus: 'Billete de bus · 1,50 €',
          medicine: 'Medicina · 6,50 €',
          game: 'Juego · 12,00 €'
        },
        changeQuestion: 'Escribe cuánto dinero te tienen que devolver.',
        changeHint: 'Resta el precio de la compra al dinero que entregas.',
        simulationCorrect: 'Muy bien. Has comprobado la situación.',
        simulationFinished: 'Has revisado una situación real con euros.',
        safetyQuestion: '¿Qué harías antes de enviar o devolver el dinero?',
        safetyHint: 'Para y comprueba la petición por otro medio.',
        changeScenarios: {
          bakery: 'Pagas 5,00 € por una compra de 2,30 €.',
          pharmacy: 'Pagas 10,00 € por una compra de 6,50 €.',
          market: 'Pagas 20,00 € por una compra de 12,70 €.'
        },
        safetyScenarios: {
          bizumScene: 'Recibes un Bizum inesperado de 25 € y te piden devolverlo.',
          bizumUnsafe: 'Devuelvo el dinero al número que me escribe.',
          bizumSafe: 'Compruebo el movimiento en mi banco y contacto con el banco.',
          smsScene: 'Recibes un SMS: “Tu banco necesita tus claves. Entra aquí”.',
          smsUnsafe: 'Abro el enlace y escribo mis claves.',
          smsSafe: 'No abro el enlace. Entro en la app oficial o llamo al banco.',
          familyScene: 'Un mensaje urgente pide 50 € y dice ser de un familiar.',
          familyUnsafe: 'Envío el dinero enseguida para ayudar.',
          familySafe: 'Llamo a esa persona usando un número que ya conozco.'
        },
        rightsQuestion: '¿Qué respuesta protege mejor tus derechos?',
        rightsHint: 'Pide información, guarda el comprobante y reclama por un canal oficial.',
        rightsScenarios: {
          returnScene: 'Una tienda no te informa de cómo devolver un producto de 18 € con un defecto.',
          returnUnsafe: 'Me voy sin preguntar para no molestar.',
          returnSafe: 'Pido la política de devolución y guardo el ticket.',
          receiptScene: 'Pagas 18 € y no te entregan un recibo.',
          receiptUnsafe: 'Me marcho sin comprobar nada.',
          receiptSafe: 'Pido el recibo y reviso que el importe sea correcto.',
          chargeScene: 'En tu cuenta aparece un cobro de 42 € que no reconoces.',
          chargeUnsafe: 'Lo ignoro y sigo usando la cuenta.',
          chargeSafe: 'Aviso al banco y guardo los datos del movimiento.'
        },
        communicationQuestion: '¿Qué forma de hablar te ayuda a decidir?',
        communicationHint: 'Pregunta con calma, di que necesitas tiempo y pide apoyo si lo necesitas.',
        communicationScenarios: {
          priceScene: 'No entiendes cuánto cuesta un servicio de 30 € antes de contratarlo.',
          priceUnsafe: 'Acepto sin preguntar para terminar rápido.',
          priceSafe: 'Pido el precio total y qué incluye antes de aceptar.',
          noScene: 'Alguien insiste para que compres algo que no quieres.',
          noUnsafe: 'Acepto aunque no me convenza.',
          noSafe: 'Digo que no y me tomo tiempo para pensarlo.',
          helpScene: 'Una decisión de dinero te parece confusa.',
          helpUnsafe: 'Oculto el problema y decido a ciegas.',
          helpSafe: 'Se lo cuento a alguien de confianza y pido ayuda.'
        },
        emergencyQuestion: '¿Cuál es el primer paso más seguro?',
        emergencyHint: 'Para, protege tus datos y busca apoyo antes de pagar o compartir información.',
        emergencyScenarios: {
          cardScene: 'No encuentras tu tarjeta y crees que la has perdido.',
          cardUnsafe: 'Espero varios días por si aparece.',
          cardSafe: 'La bloqueo desde la app o llamo al banco cuanto antes.',
          repairScene: 'Se rompe algo importante y te piden pagar una reparación urgente.',
          repairUnsafe: 'Pago lo primero que me piden sin comparar.',
          repairSafe: 'Pido presupuesto y consulto a alguien antes de pagar.',
          urgentScene: 'Llega un gasto inesperado de 90 € y este mes vas justo de dinero.',
          urgentUnsafe: 'Pido un préstamo rápido sin leer las condiciones.',
          urgentSafe: 'Reviso prioridades, hablo con alguien y busco opciones seguras.'
        },
        purchaseIntro: 'Una compra puede tener cuatro momentos. El dinero solo sale al pagar.',
        purchaseNext: 'Siguiente documento',
        purchasePay: 'Confirmar pago de {amount}',
        purchasePaid: 'Pago registrado. El gasto aparece en tus movimientos.',
        purchaseAfter: 'Después del pago tendrías {balance}.',
        purchaseOverBalance: 'El pago es mayor que tu saldo actual. Revísalo antes de confirmar.',
        purchaseStages: {
          orderTitle: '1. Pedido',
          orderDetail: 'Pides el producto o servicio. Todavía no has recibido nada ni pagado.',
          deliveryTitle: '2. Lo que recibes',
          deliveryDetail: 'Compruebas que lo recibido coincide con lo que pediste.',
          invoiceTitle: '3. Factura',
          invoiceDetail: 'La factura indica qué debes pagar, cuánto y a quién.',
          paymentTitle: '4. Pago',
          paymentDetail: 'Pagas después de revisar el pedido, lo recibido y la factura.'
        },
        purchaseScenarios: {
          backpack: 'Una mochila cuesta 24,00 €.',
          shoes: 'Unas zapatillas cuestan 36,00 €.',
          repair: 'Una reparación necesaria cuesta 90,00 €.'
        }
      }
    },

    expense: {
      categoryTitle: '¿Qué tipo de gasto es?',
      categoryInstruction: 'Elige una categoría y decide si es necesario o puede esperar.',
      amountTitle: '¿Cuánto gastaste?',
      amountInstruction: 'Escribe el precio.',
      confirmTitle: 'Revisa tu gasto',
      confirmInstruction: 'Si está bien, guárdalo.',
      saveButton: '✅ Guardar gasto',
      savedMessage: '¡Gasto guardado!',
      afterExpense: 'Después de este gasto tendrás {balance}.',
      overBalance: 'Este gasto es mayor que tu saldo. Revisa el importe si quieres.',
      savedWithBalance: '¡Gasto guardado! Ahora tienes {balance}.',
      balanceSavedWithValue: 'Saldo actualizado. Ahora tienes {balance}.'
    },

    income: {
      title: '¿De dónde viene el dinero?',
      instruction: 'Elige una opción.',
      amountTitle: '¿Cuánto dinero has recibido?',
      amountInstruction: 'Escribe la cantidad.',
      saveButton: '✅ Guardar ingreso',
      savedWithBalance: 'Dinero guardado. Ahora tienes {balance}.',
      sources: {
        allowance: 'Dinero de bolsillo',
        work: 'Trabajo',
        gift: 'Regalo',
        refund: 'Devolución'
      }
    },

    commitments: {
      title: 'Pagos previstos',
      detail: 'Apunta pagos que tendrás que recordar.',
      newButton: '+ Añadir pago previsto',
      empty: 'Todavía no tienes pagos previstos.',
      nameTitle: '¿Qué pago quieres recordar?',
      nameInstruction: 'Escribe un nombre corto.',
      namePlaceholder: 'Por ejemplo: teléfono',
      nameAria: 'Nombre del pago previsto',
      dueDateLabel: '¿Para qué día lo necesitas? (opcional)',
      dueDateAria: 'Fecha del pago previsto',
      dueDate: 'Para el {date}',
      overdue: 'Fecha pasada: revísalo',
      amountTitle: '¿Cuánto cuesta?',
      amountInstruction: 'Escribe el importe aproximado.',
      savedMessage: 'Pago previsto guardado.'
    },

    settings: {
      openButton: 'Ajustes y datos',
      title: 'Ajustes y datos',
      intro: 'Controla cómo lees la app y guarda una copia de tus datos en este dispositivo.',
      textSizeTitle: 'Tamaño del texto',
      textSizeInstruction: 'Elige el tamaño que te resulte más cómodo.',
      textSizeNormal: 'Normal',
      textSizeLarge: 'Grande',
      textSizeExtraLarge: 'Muy grande',
      backupTitle: 'Copia de tus datos',
      backupInstruction: 'Descarga una copia o restaura una copia anterior. La copia se queda en tu dispositivo.',
      exportButton: '⬇️ Descargar copia',
      importLabel: '⬆️ Restaurar copia',
      exportedMessage: 'Copia descargada.',
      exportUnavailable: 'Este navegador no permite descargar la copia.',
      importConfirm: 'Restaurar la copia sustituirá los datos actuales. ¿Quieres continuar?',
      importError: 'No se ha podido restaurar esa copia.',
      resetTitle: 'Borrar datos',
      resetInstruction: 'Borra el saldo, las metas, los apuntes, los puntos y las preferencias de este dispositivo.',
      resetButton: 'Borrar todos mis datos',
      resetConfirm: 'Se borrarán todos tus datos de Okeymoney en este dispositivo. ¿Seguro que quieres continuar?'
    },

    categories: {
      food: 'Comida',
      fun: 'Ocio',
      transport: 'Transporte',
      clothes: 'Ropa',
      health: 'Salud',
      other: 'Otros',
      classification: {
        essential: 'Necesario',
        discretionary: 'Puede esperar'
      }
    },

    goals: {
      iconLabel: 'Icono {n}',
      title: 'Mis metas',
      newButton: '+ Nueva meta',
      empty: 'Todavía no tienes ninguna meta. ¡Crea la primera!',
      newTitle: '¿Qué quieres conseguir?',
      newInstruction: 'Elige un dibujo y escribe el nombre.',
      namePlaceholder: 'Por ejemplo: un juego',
      nameAria: 'Nombre de tu meta',
      targetTitle: '¿Cuánto cuesta?',
      targetInstruction: 'Escribe el precio.',
      addTitle: '¿Cuánto quieres guardar?',
      addInstruction: 'Escribe la cantidad.',
      availableBalance: 'Puedes guardar hasta {balance} sin dejar tu saldo en negativo.',
      overBalance: 'Esa cantidad es mayor que el dinero disponible.',
      addButton: '+ Añadir dinero',
      progressText: '{saved} de {target}',
      achievedBadge: '🏆 ¡Meta conseguida!',
      savedMessage: '¡Meta creada!',
      addedMessage: '¡Dinero guardado!',
      savedWithBalance: '¡Meta creada! Tu saldo sigue siendo {balance}.',
      addedWithBalance: '¡Dinero guardado! Ahora tienes {balance}.'
    },

    learn: {
      title: 'Ver',
      comingSoon: 'Muy pronto podrás ver aquí situaciones sobre el dinero.',
      walletLabel: 'Tus puntos',
      intro: 'Mira situaciones y prueba decisiones. Los puntos no son dinero real.',
      stateDone: '✓ Visto',
      stateAvailable: '▶ Ver',
      stateLocked: '🔒 Pronto',
      themes: {
        concepts: 'Conceptos básicos',
        daily: 'Vida cotidiana',
        safety: 'Seguridad'
      },
      activityTitle: {
        "save-step-by-step": "Ahorra para una meta",
        "compare-prices": "Compara antes de pagar",
        "monthly-payments": "Organiza tus pagos",
        'concepts-money':  'Cuenta tu dinero',
        'needs-vs-wants':  '¿Lo necesitas o lo quieres?',
        'budget-first':    '¿Qué te conviene comprar primero?',
        'before-buying':   'Cuatro preguntas antes de comprar',
        'go-shopping':     'Haz tu compra',
        'change-back':     'Comprueba tu cambio',
        'my-shopping-day': 'Organiza tu compra del día',
        'safe-money':      'Protege tu dinero'
      },
      activityDesc: {
        'concepts-money':  'Mira, cuenta y cambia monedas y billetes.',
        'needs-vs-wants':  'Piensa si algo te hace falta o simplemente te apetece.',
        'budget-first':    'Ordena tus compras cuando el dinero es limitado.',
        'before-buying':   'Frena las compras impulsivas y decide con más calma.',
        'go-shopping':     'Haz una compra pequeña sin salirte del presupuesto.',
        'change-back':     'Comprueba cuánto dinero deben devolverte al pagar.',
        'my-shopping-day': 'Haz todo junto en una compra completa.',
        'safe-money':      'Reconoce transferencias extrañas y estafas.'
      }
    },

    wizard: {
      closeAria: 'Cerrar y no guardar'
    },

    keypad: {
      deleteDigit: 'Borrar el último dígito',
      clear: 'Borrar todo'
    },

    offline: {
      title: 'Sin conexión',
      heading: 'Sin conexión',
      body: 'No hemos podido cargar esta página. Comprueba tu conexión a Internet y vuelve a intentarlo.',
      homeLink: 'Volver a Okeymoney',
      metaDescription: 'Okeymoney está sin conexión: comprueba tu conexión a Internet y vuelve a intentarlo.'
    }
  }, 'es');
})();
