/* tools/go-shopping — Ir a la tienda.
   Each case: you have a budget and 4 items to consider. Pick the 2 that
   fit. 3 options (which pair to take), socratic, +20 tokens on completion. */
(function () {
  'use strict';
  App.activity.run({
    slug: 'go-shopping',
    rewardCents: 2000,
    cases: [
      { id: 's1',
        instructionKey: 's1instr',
        sceneKey: 'reviewScene1',
        options: ['opPanManzana', 'opPanJugo', 'opFrutaJuego'],
        correctIndex: 0,
        hintKey: 's1pista', explanationKey: 's1expl' },
      { id: 's2',
        instructionKey: 's2instr',
        sceneKey: 'reviewScene2',
        options: ['opTiritasLibro', 'opComidaJuego', 'opComidaTiritas'],
        correctIndex: 2,
        hintKey: 's2pista', explanationKey: 's2expl' },
      { id: 's3',
        instructionKey: 's3instr',
        sceneKey: 'reviewScene3',
        options: ['opTransComida', 'opAguaAbrigo', 'opAbrigoComida'],
        correctIndex: 0,
        hintKey: 's3pista', explanationKey: 's3expl' },
      { id: 's4',
        instructionKey: 's4instr',
        sceneKey: 'reviewScene4',
        options: ['opMediLibro', 'opAuricularesFruta', 'opFrutaLibro'],
        correctIndex: 0,
        hintKey: 's4pista', explanationKey: 's4expl' },
      { id: 's5',
        instructionKey: 's5instr',
        sceneKey: 'reviewScene5',
        options: ['opComidaTiritas2', 'opParaguasComida', 'opAbrigoTiritas'],
        correctIndex: 0,
        hintKey: 's5pista', explanationKey: 's5expl' },
      { id: 's6',
        instructionKey: 's6instr',
        sceneKey: 'reviewScene6',
        options: ['opZapatillasLibro', 'opLibroTiritas2', 'opJuegoZapatillas'],
        correctIndex: 1,
        hintKey: 's6pista', explanationKey: 's6expl' },
      { id: 's7',
        instructionKey: 's7instr',
        sceneKey: 'reviewScene7',
        options: ['opComidaAgua', 'opMovilTiritas', 'opPanMovil'],
        correctIndex: 0,
        hintKey: 's7pista', explanationKey: 's7expl' },
      { id: 's8',
        instructionKey: 's8instr',
        sceneKey: 'reviewScene8',
        options: ['opAbrigoTiritas2', 'opPanAuriculares', 'opTiritasPan'],
        correctIndex: 2,
        hintKey: 's8pista', explanationKey: 's8expl' }
    ]
  });
})();
