/* tools/go-shopping — Ir a la tienda.
   Each case: you have a budget and 4 items to consider. Pick the 2 that
   fit. 3 options (which pair to take), socratic, +20 tokens on completion. */
(function () {
  'use strict';
  App.activity.run({
    slug: 'go-shopping',
    rewardCents: 2000,
    casos: [
      { id: 's1',
        instruccionKey: 's1instr',
        sceneKey: 'reviewScene1',
        opciones: ['opPanManzana', 'opPanJugo', 'opFrutaJuego'],
        correctaIndex: 0,
        pistaKey: 's1pista', explicacionKey: 's1expl' },
      { id: 's2',
        instruccionKey: 's2instr',
        sceneKey: 'reviewScene2',
        opciones: ['opTiritasLibro', 'opComidaJuego', 'opComidaTiritas'],
        correctaIndex: 2,
        pistaKey: 's2pista', explicacionKey: 's2expl' },
      { id: 's3',
        instruccionKey: 's3instr',
        sceneKey: 'reviewScene3',
        opciones: ['opTransComida', 'opAguaAbrigo', 'opAbrigoComida'],
        correctaIndex: 0,
        pistaKey: 's3pista', explicacionKey: 's3expl' },
      { id: 's4',
        instruccionKey: 's4instr',
        sceneKey: 'reviewScene4',
        opciones: ['opMediLibro', 'opAuricularesFruta', 'opFrutaLibro'],
        correctaIndex: 0,
        pistaKey: 's4pista', explicacionKey: 's4expl' },
      { id: 's5',
        instruccionKey: 's5instr',
        sceneKey: 'reviewScene5',
        opciones: ['opComidaTiritas2', 'opParaguasComida', 'opAbrigoTiritas'],
        correctaIndex: 0,
        pistaKey: 's5pista', explicacionKey: 's5expl' },
      { id: 's6',
        instruccionKey: 's6instr',
        sceneKey: 'reviewScene6',
        opciones: ['opZapatillasLibro', 'opLibroTiritas2', 'opJuegoZapatillas'],
        correctaIndex: 1,
        pistaKey: 's6pista', explicacionKey: 's6expl' },
      { id: 's7',
        instruccionKey: 's7instr',
        sceneKey: 'reviewScene7',
        opciones: ['opComidaAgua', 'opMovilTiritas', 'opPanMovil'],
        correctaIndex: 0,
        pistaKey: 's7pista', explicacionKey: 's7expl' },
      { id: 's8',
        instruccionKey: 's8instr',
        sceneKey: 'reviewScene8',
        opciones: ['opAbrigoTiritas2', 'opPanAuriculares', 'opTiritasPan'],
        correctaIndex: 2,
        pistaKey: 's8pista', explicacionKey: 's8expl' }
    ]
  });
})();
