App.i18n.register({
  "title": "Make your purchase",
  "metaDescription": "Make a small purchase with a budget.",
  "objetivo": "At the shop, choose a basket that fits your budget.",
  "instruccion": "Choose what to put in the basket.",
  "didacticTitle": "Add it up before filling the basket",
  "didacticBody": "Add the prices. Compare the total with your money.",
  "didacticExampleLabel": "Example",
  "didacticExample": "With €10, a €7 shop fits your budget.",
  "didacticContinue": "Try situations",
  "opPanManzana": "🥖 Bread + 🍎 Apple",
  "opPanJugo": "🥖 Bread + 🧃 Juice",
  "opFrutaJuego": "🍎 Apple + 🎮 Game",
  "opTiritasLibro": "🩹 Plasters + 📚 Book",
  "opComidaJuego": "🍜 Food + 🎮 Game",
  "opComidaTiritas": "🍜 Food + 🩹 Plasters",
  "opTransComida": "🚌 Bus + 🍞 Bread",
  "opAguaAbrigo": "💧 Water + 🧥 Coat",
  "opAbrigoComida": "🧥 Coat + 🍞 Bread",
  "opMediLibro": "💊 Medicine + 📚 Book",
  "opAuricularesFruta": "🎧 Headphones + 🍎 Fruit",
  "opFrutaLibro": "🍎 Fruit + 📚 Book",
  "opComidaTiritas2": "🍜 Food + 🩹 Plasters",
  "opParaguasComida": "☂️ Umbrella + 🍜 Food",
  "opAbrigoTiritas": "🧥 Coat + 🩹 Plasters",
  "opZapatillasLibro": "👟 Shoes + 📚 Book",
  "opLibroTiritas2": "📚 Book + 🩹 Plasters",
  "opJuegoZapatillas": "🎮 Game + 👟 Shoes",
  "opComidaAgua": "🍞 Bread + 💧 Water",
  "opMovilTiritas": "📱 Phone + 🩹 Plasters",
  "opPanMovil": "🍞 Bread + 📱 Phone",
  "opAbrigoTiritas2": "🧥 Coat + 🩹 Plasters",
  "opPanAuriculares": "🍞 Bread + 🎧 Headphones",
  "opTiritasPan": "🩹 Plasters + 🍞 Bread",
  "s1instr": "You have 3 € to spend. What do you put in the basket?",
  "s1pista": "Check the total: only one pair fits.",
  "s1expl": "Bread + apple adds up to exactly 3 € and fits the budget.",
  "s2instr": "You have 10 € to spend. What do you put in the basket?",
  "s2pista": "Care and food first.",
  "s2expl": "Food + plasters: what is needed.",
  "s3instr": "You have 8 € to spend. What do you put in the basket?",
  "s3pista": "You need to get home and eat.",
  "s3expl": "Bus + bread lets you travel and eat.",
  "s4instr": "You have 13 € to spend. What do you put in the basket?",
  "s4pista": "Health and study: add both prices.",
  "s4expl": "Medicine + book adds up to 13 €.",
  "s5instr": "You have 12 € to spend. What do you put in the basket?",
  "s5pista": "Food and health.",
  "s5expl": "Food + plasters: the essentials.",
  "s6instr": "You have 20 € to spend. What do you put in the basket?",
  "s6pista": "Add both prices. You have €20.",
  "s6expl": "Book and plasters cost €11. Shoes and book cost €23.",
  "s7instr": "You have 5 € to spend. What do you put in the basket?",
  "s7pista": "Just the essentials.",
  "s7expl": "Bread + water: the minimum.",
  "s8instr": "You have 25 € to spend. What do you put in the basket?",
  "s8pista": "Add each pair and check which one fits.",
  "s8expl": "Plasters + bread adds up to 4 € and is the only pair that fits.",
  "pistaSigue": "Think: what do you really need with that money?",
  "presupuesto": "Budget:",
  "shopFamilia": "Your family",
  "shopMercadona": "Supermarket",
  "shopFarmacia": "Pharmacy",
  "shopBus": "Bus",
  "shopBanco": "Bank",
  "shopTienda": "Clothes shop",
  "completado": "Well done! You can make a small purchase.",
  "reiniciar": "↻ Try it again",
  "fallo": "Almost. Think again.",
  "yaCompletada": "You have already tried this situation. You can try it again.",
  "reviewScene1": "Budget: 3 €. 🥖 2 €   🍎 1 €   🧃 1.50 €   🎮 20 €",
  "reviewScene2": "Budget: 10 €. 🩹 3 €   🍜 4 €   📚 8 €   🎮 25 €",
  "reviewScene3": "Budget: 8 €. 🚌 1.50 €   🧥 30 €   🍞 2 €   💧 1 €",
  "reviewScene4": "Budget: 13 €. 🎧 25 €   💊 4 €   🍎 5 €   📚 9 €",
  "reviewScene5": "Budget: 12 €. 🧥 30 €   🍜 5 €   🩹 2 €   ☂️ 8 €",
  "reviewScene6": "Budget: 20 €. 🎮 25 €   👟 15 €   📚 8 €   🩹 3 €",
  "reviewScene7": "Budget: 5 €. 📱 100 €   🍞 2 €   💧 1 €   🩹 2 €",
  "reviewScene8": "Budget: 25 €. 🧥 25 €   🎧 50 €   🩹 2 €   🍞 2 €"
}, 'en');
