(function () {
  'use strict';
  App.i18n.register({
    title: 'Ir a la tienda',
    metaDescription: 'Haz una compra pequeña con un presupuesto.',
    instruccion: 'Elige qué meter en el carro.',
    opPanManzana: '🥖 Pan + 🍎 Manzana',
    opPanJugo: '🥖 Pan + 🧃 Jugo',
    opFrutaJuego: '🍎 Manzana + 🎮 Juego',
    opTiritasLibro: '🩹 Tiritas + 📚 Libro',
    opComidaJuego: '🍜 Comida + 🎮 Juego',
    opComidaTiritas: '🍜 Comida + 🩹 Tiritas',
    opTransComida: '🚌 Bus + 🍞 Pan',
    opAguaAbrigo: '💧 Agua + 🧥 Abrigo',
    opAbrigoComida: '🧥 Abrigo + 🍞 Pan',
    opMediLibro: '💊 Medicina + 📚 Libro',
    opAuricularesFruta: '🎧 Auriculares + 🍎 Fruta',
    opFrutaLibro: '🍎 Fruta + 📚 Libro',
    opComidaTiritas2: '🍜 Comida + 🩹 Tiritas',
    opParaguasComida: '☂️ Paraguas + 🍜 Comida',
    opAbrigoTiritas: '🧥 Abrigo + 🩹 Tiritas',
    opZapatillasLibro: '👟 Zapatillas + 📚 Libro',
    opLibroTiritas2: '📚 Libro + 🩹 Tiritas',
    opJuegoZapatillas: '🎮 Juego + 👟 Zapatillas',
    opComidaAgua: '🍞 Pan + 💧 Agua',
    opMovilTiritas: '📱 Móvil + 🩹 Tiritas',
    opPanMovil: '🍞 Pan + 📱 Móvil',
    opAbrigoTiritas2: '🧥 Abrigo + 🩹 Tiritas',
    opPanAuriculares: '🍞 Pan + 🎧 Auriculares',
    opTiritasPan: '🩹 Tiritas + 🍞 Pan',
    s1instr: 'Vas a comprar con 6 €. ¿Qué metes en el carro?', s1pista: 'Solo te cabe lo que necesitas.', s1expl: 'Pan + manzana es lo más básico.',
    s2instr: 'Vas a comprar con 10 €. ¿Qué metes en el carro?', s2pista: 'Cuidado y comida, primero.', s2expl: 'Comida + tiritas: lo necesario.',
    s3instr: 'Vas a comprar con 8 €. ¿Qué metes en el carro?', s3pista: 'Necesitas volver a casa y comer.', s3expl: 'Bus + pan te permite volver y comer.',
    s4instr: 'Vas a comprar con 15 €. ¿Qué metes en el carro?', s4pista: 'Salud y estudio.', s4expl: 'Medicina + libro: cuidarte y aprender.',
    s5instr: 'Vas a comprar con 12 €. ¿Qué metes en el carro?', s5pista: 'Comida y salud.', s5expl: 'Comida + tiritas: lo indispensable.',
    s6instr: 'Vas a comprar con 20 €. ¿Qué metes en el carro?', s6pista: 'Algo útil y algo que aprendes.', s6expl: 'Zapatillas + libro.',
    s7instr: 'Vas a comprar con 5 €. ¿Qué metes en el carro?', s7pista: 'Imprescindible.', s7expl: 'Pan + agua: lo mínimo.',
    s8instr: 'Vas a comprar con 30 €. ¿Qué metes en el carro?', s8pista: 'Protección y cuidado.', s8expl: 'Abrigo + tiritas.',
    pistaSigue: 'Piénsalo: ¿qué necesitas de verdad con ese dinero?',
    presupuesto: 'Presupuesto:',
    shopFamilia: 'Tu familia', shopMercadona: 'El supermercado', shopFarmacia: 'La farmacia', shopBus: 'El bus', shopBanco: 'El banco', shopTienda: 'La tienda de ropa',
    completado: '¡Muy bien! Ya sabes hacer una compra pequeña.',
    reiniciar: '↻ Jugar otra vez',
    fallo: 'Casi. Vuelve a pensarlo.',
    yaCompletada: 'Ya has terminado esta actividad.'
  }, 'es');
})();
