App.i18n.register({
  "title": "Haz tu compra",
  "metaDescription": "Haz una compra pequeña con un presupuesto.",
  "objetivo": "En la tienda, elige una cesta que quepa en tu presupuesto.",
  "instruccion": "Elige qué meter en el carro.",
  "didacticTitle": "Suma antes de llenar el carro",
  "didacticBody": "Suma los precios. Compara el total con tu dinero.",
  "didacticExampleLabel": "Ejemplo",
  "didacticExample": "Con 10 €, una compra de 7 € sí cabe.",
  "didacticContinue": "Probar situaciones",
  "opPanManzana": "🥖 Pan + 🍎 Manzana",
  "opPanJugo": "🥖 Pan + 🧃 Jugo",
  "opFrutaJuego": "🍎 Manzana + 🎮 Juego",
  "opTiritasLibro": "🩹 Tiritas + 📚 Libro",
  "opComidaJuego": "🍜 Comida + 🎮 Juego",
  "opComidaTiritas": "🍜 Comida + 🩹 Tiritas",
  "opTransComida": "🚌 Bus + 🍞 Pan",
  "opAguaAbrigo": "💧 Agua + 🧥 Abrigo",
  "opAbrigoComida": "🧥 Abrigo + 🍞 Pan",
  "opMediLibro": "💊 Medicina + 📚 Libro",
  "opAuricularesFruta": "🎧 Auriculares + 🍎 Fruta",
  "opFrutaLibro": "🍎 Fruta + 📚 Libro",
  "opComidaTiritas2": "🍜 Comida + 🩹 Tiritas",
  "opParaguasComida": "☂️ Paraguas + 🍜 Comida",
  "opAbrigoTiritas": "🧥 Abrigo + 🩹 Tiritas",
  "opZapatillasLibro": "👟 Zapatillas + 📚 Libro",
  "opLibroTiritas2": "📚 Libro + 🩹 Tiritas",
  "opJuegoZapatillas": "🎮 Juego + 👟 Zapatillas",
  "opComidaAgua": "🍞 Pan + 💧 Agua",
  "opMovilTiritas": "📱 Móvil + 🩹 Tiritas",
  "opPanMovil": "🍞 Pan + 📱 Móvil",
  "opAbrigoTiritas2": "🧥 Abrigo + 🩹 Tiritas",
  "opPanAuriculares": "🍞 Pan + 🎧 Auriculares",
  "opTiritasPan": "🩹 Tiritas + 🍞 Pan",
  "s1instr": "Vas a comprar con 3 €. ¿Qué metes en el carro?",
  "s1pista": "Comprueba el total: solo una combinación cabe.",
  "s1expl": "Pan + manzana suma justo 3 € y cabe en el presupuesto.",
  "s2instr": "Vas a comprar con 10 €. ¿Qué metes en el carro?",
  "s2pista": "Cuidado y comida, primero.",
  "s2expl": "Comida + tiritas: lo necesario.",
  "s3instr": "Vas a comprar con 8 €. ¿Qué metes en el carro?",
  "s3pista": "Necesitas volver a casa y comer.",
  "s3expl": "Bus + pan te permite volver y comer.",
  "s4instr": "Vas a comprar con 13 €. ¿Qué metes en el carro?",
  "s4pista": "Salud y estudio: suma los dos precios.",
  "s4expl": "Medicina + libro suma 13 €.",
  "s5instr": "Vas a comprar con 12 €. ¿Qué metes en el carro?",
  "s5pista": "Comida y salud.",
  "s5expl": "Comida + tiritas: lo necesario.",
  "s6instr": "Vas a comprar con 20 €. ¿Qué metes en el carro?",
  "s6pista": "Suma los dos precios. Tienes 20 €.",
  "s6expl": "Libro y tiritas cuestan 11 €. Zapatillas y libro cuestan 23 €.",
  "s7instr": "Vas a comprar con 5 €. ¿Qué metes en el carro?",
  "s7pista": "Lo que necesitas.",
  "s7expl": "Pan + agua: lo mínimo.",
  "s8instr": "Vas a comprar con 25 €. ¿Qué metes en el carro?",
  "s8pista": "Suma cada pareja y comprueba cuál cabe.",
  "s8expl": "Tiritas + pan suma 4 € y es la única pareja que cabe.",
  "pistaSigue": "Piénsalo: ¿qué necesitas de verdad con ese dinero?",
  "presupuesto": "Presupuesto:",
  "shopFamilia": "Tu familia",
  "shopMercadona": "El supermercado",
  "shopFarmacia": "La farmacia",
  "shopBus": "El bus",
  "shopBanco": "El banco",
  "shopTienda": "La tienda de ropa",
  "completado": "¡Muy bien! Ya sabes hacer una compra pequeña.",
  "reiniciar": "↻ Volver a hacerlo",
  "fallo": "Casi. Vuelve a pensarlo.",
  "yaCompletada": "Ya has hecho esta situación. Puedes volver a hacerla.",
  "reviewScene1": "Presupuesto: 3 €. 🥖 2 €   🍎 1 €   🧃 1,50 €   🎮 20 €",
  "reviewScene2": "Presupuesto: 10 €. 🩹 3 €   🍜 4 €   📚 8 €   🎮 25 €",
  "reviewScene3": "Presupuesto: 8 €. 🚌 1,50 €   🧥 30 €   🍞 2 €   💧 1 €",
  "reviewScene4": "Presupuesto: 13 €. 🎧 25 €   💊 4 €   🍎 5 €   📚 9 €",
  "reviewScene5": "Presupuesto: 12 €. 🧥 30 €   🍜 5 €   🩹 2 €   ☂️ 8 €",
  "reviewScene6": "Presupuesto: 20 €. 🎮 25 €   👟 15 €   📚 8 €   🩹 3 €",
  "reviewScene7": "Presupuesto: 5 €. 📱 100 €   🍞 2 €   💧 1 €   🩹 2 €",
  "reviewScene8": "Presupuesto: 25 €. 🧥 25 €   🎧 50 €   🩹 2 €   🍞 2 €"
}, 'es');
