(function () {
  'use strict';
  App.i18n.register({
    title: 'Make your purchase',
    metaDescription: 'Make a small purchase with a budget.',
    instruccion: 'Choose what to put in the basket.',
    opPanManzana: '🥖 Bread + 🍎 Apple',
    opPanJugo: '🥖 Bread + 🧃 Juice',
    opFrutaJuego: '🍎 Apple + 🎮 Game',
    opTiritasLibro: '🩹 Plasters + 📚 Book',
    opComidaJuego: '🍜 Food + 🎮 Game',
    opComidaTiritas: '🍜 Food + 🩹 Plasters',
    opTransComida: '🚌 Bus + 🍞 Bread',
    opAguaAbrigo: '💧 Water + 🧥 Coat',
    opAbrigoComida: '🧥 Coat + 🍞 Bread',
    opMediLibro: '💊 Medicine + 📚 Book',
    opAuricularesFruta: '🎧 Headphones + 🍎 Fruit',
    opFrutaLibro: '🍎 Fruit + 📚 Book',
    opComidaTiritas2: '🍜 Food + 🩹 Plasters',
    opParaguasComida: '☂️ Umbrella + 🍜 Food',
    opAbrigoTiritas: '🧥 Coat + 🩹 Plasters',
    opZapatillasLibro: '👟 Shoes + 📚 Book',
    opLibroTiritas2: '📚 Book + 🩹 Plasters',
    opJuegoZapatillas: '🎮 Game + 👟 Shoes',
    opComidaAgua: '🍞 Bread + 💧 Water',
    opMovilTiritas: '📱 Phone + 🩹 Plasters',
    opPanMovil: '🍞 Bread + 📱 Phone',
    opAbrigoTiritas2: '🧥 Coat + 🩹 Plasters',
    opPanAuriculares: '🍞 Bread + 🎧 Headphones',
    opTiritasPan: '🩹 Plasters + 🍞 Bread',
    s1instr: 'You have 6 € to spend. What do you put in the basket?', s1pista: 'You can only fit what you need.', s1expl: 'Bread + apple: the basics.',
    s2instr: 'You have 10 € to spend.', s2pista: 'Care and food first.', s2expl: 'Food + plasters: what is needed.',
    s3instr: 'You have 8 € to spend.', s3pista: 'You need to get home and eat.', s3expl: 'Bus + bread lets you travel and eat.',
    s4instr: 'You have 15 € to spend.', s4pista: 'Health and study.', s4expl: 'Medicine + book: self-care and learning.',
    s5instr: 'You have 12 € to spend.', s5pista: 'Food and health.', s5expl: 'Food + plasters: the essentials.',
    s6instr: 'You have 20 € to spend.', s6pista: 'Something useful and something you learn.', s6expl: 'Shoes + book.',
    s7instr: 'You have 5 € to spend.', s7pista: 'Just the essentials.', s7expl: 'Bread + water: the minimum.',
    s8instr: 'You have 30 € to spend.', s8pista: 'Protection and care.', s8expl: 'Coat + plasters.',
    pistaSigue: 'Think: what do you really need with that money?',
    presupuesto: 'Budget:',
    shopFamilia: 'Your family', shopMercadona: 'Supermarket', shopFarmacia: 'Pharmacy', shopBus: 'Bus', shopBanco: 'Bank', shopTienda: 'Clothes shop',
    completado: 'Well done! You can make a small purchase.',
    reiniciar: '↻ Play again',
    fallo: 'Almost. Think again.',
    yaCompletada: 'You already finished this activity.'
  }, 'en');
})();
