/* tools/budget-first — ¿Qué compro first?
   Each case: budget X €, three things to buy, decide which to buy FIRST.
   3 options, socratic, +12 tokens on completion. */
(function () {
  'use strict';
  App.activity.run({
    slug: 'budget-first',
    rewardCents: 1200,
    cases: [
      { id: 'b1',
        instructionKey: 'b1instr',
        sceneKey: 'reviewScene1',
        options: ['opPan', 'opJuego', 'opRegalo'],
        correctIndex: 0,
        hintKey: 'b1pista', explanationKey: 'b1expl' },
      { id: 'b2',
        instructionKey: 'b2instr',
        sceneKey: 'reviewScene2',
        options: ['opFruta', 'opMedi', 'opTele'],
        correctIndex: 1,
        hintKey: 'b2pista', explanationKey: 'b2expl' },
      { id: 'b3',
        instructionKey: 'b3instr',
        sceneKey: 'reviewScene3',
        options: ['opBus', 'opRegalo', 'opParaguas'],
        correctIndex: 0,
        hintKey: 'b3pista', explanationKey: 'b3expl' },
      { id: 'b4',
        instructionKey: 'b4instr',
        sceneKey: 'reviewScene4',
        options: ['opAbrigo', 'opJuego2', 'opMovil'],
        correctIndex: 0,
        hintKey: 'b4pista', explanationKey: 'b4expl' },
      { id: 'b5',
        instructionKey: 'b5instr',
        sceneKey: 'reviewScene5',
        options: ['opJugo', 'opJuego2', 'opTiritas'],
        correctIndex: 2,
        hintKey: 'b5pista', explanationKey: 'b5expl' },
      { id: 'b6',
        instructionKey: 'b6instr',
        sceneKey: 'reviewScene6',
        options: ['opLibro', 'opAuriculares', 'opTransporte'],
        correctIndex: 2,
        hintKey: 'b6pista', explanationKey: 'b6expl' },
      { id: 'b7',
        instructionKey: 'b7instr',
        sceneKey: 'reviewScene7',
        options: ['opAlquiler', 'opCine', 'opBus'],
        correctIndex: 0,
        hintKey: 'b7pista', explanationKey: 'b7expl' },
      { id: 'b8',
        instructionKey: 'b8instr',
        sceneKey: 'reviewScene8',
        options: ['opMedicamento', 'opComida', 'opJuego'],
        correctIndex: 2,
        hintKey: 'b8pista', explanationKey: 'b8expl' }
    ]
  });
})();
