/* tools/budget-first — ¿Qué compro primero?
   Each case: budget X €, three things to buy, decide which to buy FIRST.
   3 options, socratic, +12 tokens on completion. */
(function () {
  'use strict';
  App.activity.run({
    slug: 'budget-first',
    rewardCents: 1200,
    casos: [
      { id: 'b1',
        instruccionKey: 'b1instr',
        sceneKey: 'reviewScene1',
        opciones: ['opPan', 'opJuego', 'opRegalo'],
        correctaIndex: 0,
        pistaKey: 'b1pista', explicacionKey: 'b1expl' },
      { id: 'b2',
        instruccionKey: 'b2instr',
        sceneKey: 'reviewScene2',
        opciones: ['opFruta', 'opMedi', 'opTele'],
        correctaIndex: 1,
        pistaKey: 'b2pista', explicacionKey: 'b2expl' },
      { id: 'b3',
        instruccionKey: 'b3instr',
        sceneKey: 'reviewScene3',
        opciones: ['opBus', 'opRegalo', 'opParaguas'],
        correctaIndex: 0,
        pistaKey: 'b3pista', explicacionKey: 'b3expl' },
      { id: 'b4',
        instruccionKey: 'b4instr',
        sceneKey: 'reviewScene4',
        opciones: ['opAbrigo', 'opJuego2', 'opMovil'],
        correctaIndex: 0,
        pistaKey: 'b4pista', explicacionKey: 'b4expl' },
      { id: 'b5',
        instruccionKey: 'b5instr',
        sceneKey: 'reviewScene5',
        opciones: ['opJugo', 'opJuego2', 'opTiritas'],
        correctaIndex: 2,
        pistaKey: 'b5pista', explicacionKey: 'b5expl' },
      { id: 'b6',
        instruccionKey: 'b6instr',
        sceneKey: 'reviewScene6',
        opciones: ['opLibro', 'opAuriculares', 'opTransporte'],
        correctaIndex: 2,
        pistaKey: 'b6pista', explicacionKey: 'b6expl' },
      { id: 'b7',
        instruccionKey: 'b7instr',
        sceneKey: 'reviewScene7',
        opciones: ['opAlquiler', 'opCine', 'opBus'],
        correctaIndex: 0,
        pistaKey: 'b7pista', explicacionKey: 'b7expl' },
      { id: 'b8',
        instruccionKey: 'b8instr',
        sceneKey: 'reviewScene8',
        opciones: ['opMedicamento', 'opComida', 'opJuego'],
        correctaIndex: 2,
        pistaKey: 'b8pista', explicacionKey: 'b8expl' }
    ]
  });
})();
