App.i18n.register({
  "title": "¿Qué te conviene comprar primero?",
  "metaDescription": "Decide qué comprar primero cuando el dinero es limitado.",
  "objetivo": "Cuando no llega para todo, pon primero lo necesario.",
  "instruccion": "Elige qué comprar primero.",
  "didacticTitle": "Paga primero lo necesario",
  "didacticBody": "Cubre primero vivienda, comida, salud y transporte.",
  "didacticExampleLabel": "Ejemplo",
  "didacticExample": "Un juego puede esperar si antes necesitas pagar la comida.",
  "didacticContinue": "Probar situaciones",
  "opAgua": "💧 El agua (1 €)",
  "opPan": "🍞 El pan (2 €)",
  "opJuego": "🎮 El juego (30 €)",
  "opFruta": "🍎 La fruta (3 €)",
  "opMedi": "💊 La medicina (8 €)",
  "opTele": "📺 La tele (200 €)",
  "opBus": "🚌 El bus (1,50 €)",
  "opRegalo": "🎁 El regalo (25 €)",
  "opParaguas": "☂️ El paraguas (5 €)",
  "opComida2": "🍜 La comida (6 €)",
  "opAbrigo": "🧥 El abrigo (40 €)",
  "opMovil": "📱 El móvil (300 €)",
  "opJugo": "🧃 El jugo (2 €)",
  "opJuego2": "🎮 El juego (30 €)",
  "opTiritas": "🩹 Las tiritas (4 €)",
  "opLibro": "📚 El libro (12 €)",
  "opAuriculares": "🎧 Los auriculares (50 €)",
  "opTransporte": "🚌 El transporte (1,50 €)",
  "shopFamilia": "Tu familia",
  "shopFarmacia": "La farmacia",
  "shopBus": "El bus",
  "shopBanco": "El banco",
  "b1instr": "Tienes 3 €. ¿Qué compras primero?",
  "b1pista": "Piensa: ¿qué necesitas sí o sí?",
  "b1expl": "El pan es lo más básico: comes todos los días.",
  "b2instr": "Tienes 10 €. ¿Qué compras primero?",
  "b2pista": "La salud va antes que el ocio.",
  "b2expl": "La medicina es una necesidad urgente.",
  "b3instr": "Tienes 5 €. ¿Qué compras primero?",
  "b3pista": "¿Cómo vas a volver a casa?",
  "b3expl": "El bus es lo primero: sin él no te mueves.",
  "b4instr": "Tienes 50 €. ¿Qué compras primero?",
  "b4pista": "El abrigo no espera, pero el móvil sí.",
  "b4expl": "El abrigo protege del frío; el juego y el móvil pueden esperar.",
  "b5instr": "Tienes 5 €. ¿Qué compras primero?",
  "b5pista": "Una herida se cura; un juego no.",
  "b5expl": "Las tiritas son para cuidarte: lo primero es la salud.",
  "b6instr": "Tienes 12 €. ¿Qué compras primero?",
  "b6pista": "Piensa en lo urgente.",
  "b6expl": "El transporte te lleva a donde necesitas ir.",
  "opAlquiler": "🏠 La habitación (300 €)",
  "opCine": "🍿 El cine (8 €)",
  "opMedicamento": "💊 La medicina (7 €)",
  "opComida": "🥦 La comida (6 €)",
  "b7instr": "¿Qué pago se repite cada mes?",
  "b7pista": "Se repite con regularidad, aunque ese mes no compres nada más.",
  "b7expl": "El alquiler suele repetirse cada mes: es un gasto fijo.",
  "b8instr": "Tienes 20 €. ¿Cuál es un gasto que puede esperar?",
  "b8pista": "Piensa en lo que puedes aplazar.",
  "b8expl": "El juego puede esperar; primero cubre lo que necesitas.",
  "presupuesto": "Presupuesto:",
  "completado": "¡Muy bien! Sabes priorizar las compras.",
  "reiniciar": "↻ Volver a hacerlo",
  "fallo": "Casi. Vuelve a pensarlo.",
  "yaCompletada": "Ya has hecho esta situación. Puedes volver a hacerla.",
  "reviewScene1": "No queda pan para comer: 🍞 2 € · 🎮 30 € · 🎁 25 €",
  "reviewScene2": "Necesitas tu medicina hoy: 💊 8 € · 📺 200 € · 🍎 3 €",
  "reviewScene3": "Necesitas el bus para volver: 🚌 1,50 € · 🎁 25 € · ☂️ 5 €",
  "reviewScene4": "Hace frío y no tienes abrigo: 🧥 40 € · 🎮 30 € · 📱 300 €",
  "reviewScene5": "Necesitas cubrir una herida: 🩹 4 € · 🎮 30 € · 🧃 2 €",
  "reviewScene6": "Necesitas llegar al trabajo en bus: 📚 12 € · 🎧 50 € · 🚌 1,50 €",
  "reviewScene7": "Pagas una habitación cada mes: 🏠 300 € · 🍿 8 € · 🚌 1,50 €",
  "reviewScene8": "Tienes comida y medicina pendientes: 💊 7 € · 🥦 6 € · 🎮 30 €"
}, 'es');
