App.i18n.register({
  "title": "What is best to buy first?",
  "metaDescription": "Decide what to buy first when money is limited.",
  "objetivo": "When money cannot cover everything, put essentials first.",
  "instruccion": "Choose what to buy first.",
  "didacticTitle": "Pay for essentials first",
  "didacticBody": "Cover housing, food, health and transport first.",
  "didacticExampleLabel": "Example",
  "didacticExample": "A game can wait if you need to pay for food first.",
  "didacticContinue": "Try situations",
  "opAgua": "💧 Water (1 €)",
  "opPan": "🍞 Bread (2 €)",
  "opJuego": "🎮 Game (30 €)",
  "opFruta": "🍎 Fruit (3 €)",
  "opMedi": "💊 Medicine (8 €)",
  "opTele": "📺 TV (200 €)",
  "opBus": "🚌 Bus (1.50 €)",
  "opRegalo": "🎁 Gift (25 €)",
  "opParaguas": "☂️ Umbrella (5 €)",
  "opComida2": "🍜 Food (6 €)",
  "opAbrigo": "🧥 Coat (40 €)",
  "opMovil": "📱 Phone (300 €)",
  "opJugo": "🧃 Juice (2 €)",
  "opJuego2": "🎮 Game (30 €)",
  "opTiritas": "🩹 Plasters (4 €)",
  "opLibro": "📚 Book (12 €)",
  "opAuriculares": "🎧 Headphones (50 €)",
  "opTransporte": "🚌 Transport (1.50 €)",
  "shopFamilia": "Your family",
  "shopFarmacia": "Pharmacy",
  "shopBus": "Bus",
  "shopBanco": "Bank",
  "b1instr": "You have 3 €. What do you buy first?",
  "b1pista": "Think: what do you definitely need?",
  "b1expl": "Bread is the most basic: you eat every day.",
  "b2instr": "You have 10 €. What do you buy first?",
  "b2pista": "Health comes before fun.",
  "b2expl": "Medicine is an urgent need.",
  "b3instr": "You have 5 €. What do you buy first?",
  "b3pista": "How will you get home?",
  "b3expl": "The bus comes first: without it you cannot move.",
  "b4instr": "You have 50 €. What do you buy first?",
  "b4pista": "The coat cannot wait, but the phone can.",
  "b4expl": "A coat protects from cold; the game and phone can wait.",
  "b5instr": "You have 5 €. What do you buy first?",
  "b5pista": "A cut heals; a game does not.",
  "b5expl": "Plasters are for self-care: health comes first.",
  "b6instr": "You have 12 €. What do you buy first?",
  "b6pista": "Think of what is urgent.",
  "b6expl": "Transport takes you where you need to go.",
  "opAlquiler": "🏠 The room (€300)",
  "opCine": "🍿 Cinema (8 €)",
  "opMedicamento": "💊 Medicine (7 €)",
  "opComida": "🥦 Food (6 €)",
  "b7instr": "Which payment repeats each month?",
  "b7pista": "It repeats regularly, even if you buy nothing else that month.",
  "b7expl": "Rent usually repeats each month: it is a fixed expense.",
  "b8instr": "You have 20 €. Which expense is optional?",
  "b8pista": "Think about what you can postpone.",
  "b8expl": "The game can wait; cover what you need first.",
  "presupuesto": "Budget:",
  "completado": "Well done! You know how to prioritise purchases.",
  "reiniciar": "↻ Try it again",
  "fallo": "Almost. Think again.",
  "yaCompletada": "You have already tried this situation. You can try it again.",
  "reviewScene1": "There is no bread for your meal: 🍞 €2 · 🎮 €30 · 🎁 €25",
  "reviewScene2": "You need your medicine today: 💊 €8 · 📺 €200 · 🍎 €3",
  "reviewScene3": "You need the bus home: 🚌 €1.50 · 🎁 €25 · ☂️ €5",
  "reviewScene4": "It is cold. You have no coat: 🧥 40 € · 🎮 30 € · 📱 300 €",
  "reviewScene5": "You need to cover a cut: 🩹 €4 · 🎮 €30 · 🧃 €2",
  "reviewScene6": "You need the bus to work: 📚 €12 · 🎧 €50 · 🚌 €1.50",
  "reviewScene7": "You pay for a room each month: 🏠 €300 · 🍿 €8 · 🚌 €1.50",
  "reviewScene8": "You still need food and medicine: 💊 €7 · 🥦 €6 · 🎮 €30"
}, 'en');
