(function () {
  'use strict';
  App.i18n.register({
    title: 'Mi compra del día',
    metaDescription: 'Practica todo junto en una compra completa: pensar, priorizar, comprar, calcular la vuelta y ahorrar.',
    instruccion: 'Cinco pasos para una compra completa.',
    shopTu: 'Tú', shopMercadona: 'El supermercado', shopFarmacia: 'La farmacia', shopBanco: 'El banco',
    opLlevar: 'Hago una lista y llevo dinero justo',
    opSalirYa: 'Salgo ya y compro lo que me apetezca',
    opMando: 'Pido a alguien que compre por mí',
    opTransJugo: '🚌 Bus + 🧃 Jugo',
    opJuegoTiritas: '🎮 Juego + 🩹 Tiritas',
    opJugoJuego: '🧃 Jugo + 🎮 Juego',
    opComidaTiritas: '🍜 Comida + 🩹 Tiritas',
    opComidaJuego: '🍜 Comida + 🎮 Juego',
    opTiritasLibro: '🩹 Tiritas + 📚 Libro',
    op550: '5,50 €',
    op650: '6,50 €',
    op450: '4,50 €',
    op1e: '1 €',
    op5e: '5 €',
    op10e: '10 €',
    opNecesito: 'Lo necesito',
    opQuiero: 'Lo quiero',
    opJuego: '🎮 Juego',
    opTiritasPan: '🩹 Tiritas + 🍞 Pan',
    op2e70: '2,70 €',
    op3e70: '3,70 €',
    op1e30: '1,30 €',
    opGuardar0: 'No guardo nada',
    opGuardar2: 'Guardo 2 €',
    opGuardar10: 'Guardo los 10 €',
    d1instr: 'Vas a salir a comprar. ¿Qué haces primero?', d1pista: 'Piensa antes de gastar.', d1expl: 'Lista + dinero justo: así no te pasas.',
    d2instr: 'Tienes 8 €. ¿Qué compras primero?', d2pista: 'Transporte y bebida.', d2expl: 'Bus + jugo: vuelves a casa y bebes.',
    d3instr: 'Tienes 10 €. ¿Qué compras primero?', d3pista: 'Salud y comida.', d3expl: 'Comida + tiritas: lo indispensable.',
    d4instr: 'Pagas con 20 € y la compra vale 14,50 €. ¿Cuánto te devuelven?', d4pista: 'Resta: 20 − 14,50.', d4expl: '20,00 − 14,50 = 5,50 €.',
    d5instr: 'Tienes 10 €. ¿Qué haces para acercarte a tu meta?', d5pista: 'Puedes guardar un poco y seguir teniendo dinero.', d5expl: 'Guardar 2 € te acerca a la meta sin quedarte sin dinero.',
    pistaSigue: 'Piénsalo con calma.',
    presupuesto: 'Presupuesto:',
    completado: '¡Enhorabuena! Has hecho una compra completa.',
    reiniciar: '↻ Jugar otra vez',
    fallo: 'Casi. Vuelve a pensarlo.',
    yaCompletada: 'Ya has terminado esta actividad.'
  }, 'es');
})();
