App.i18n.register({
  "title": "Organiza tu compra del día",
  "metaDescription": "Prepara una compra, elige lo necesario y comprueba la vuelta.",
  "objetivo": "Prepara tu compra y comprueba la vuelta.",
  "instruccion": "Organiza tu compra antes de pagar.",
  "didacticTitle": "Prepara tu compra",
  "didacticBody": "Haz una lista. Lleva solo el dinero que puedes gastar.",
  "didacticExampleLabel": "Ejemplo",
  "didacticExample": "Si tienes 10 €, el total no puede pasar de 10 €.",
  "didacticContinue": "Probar situaciones",
  "shopTu": "Tú",
  "shopMercadona": "El supermercado",
  "shopFarmacia": "La farmacia",
  "shopBanco": "El banco",
  "opLlevar": "Hago una lista y llevo dinero justo",
  "opSalirYa": "Salgo ya y compro lo que me apetezca",
  "opMando": "Pido a alguien que compre por mí",
  "opTransJugo": "🚌 Bus + 🧃 Jugo",
  "opJuegoTiritas": "🎮 Juego + 🩹 Tiritas",
  "opJugoJuego": "🧃 Jugo + 🎮 Juego",
  "opComidaTiritas": "🍜 Comida + 🩹 Tiritas",
  "opComidaJuego": "🍜 Comida + 🎮 Juego",
  "opTiritasLibro": "🩹 Tiritas + 📚 Libro",
  "op550": "5,50 €",
  "op650": "6,50 €",
  "op450": "4,50 €",
  "op1e": "1 €",
  "op5e": "5 €",
  "op10e": "10 €",
  "opNecesito": "Lo necesito",
  "opQuiero": "Lo quiero",
  "opJuego": "🎮 Juego",
  "opTiritasPan": "🩹 Tiritas + 🍞 Pan",
  "op2e70": "2,70 €",
  "op3e70": "3,70 €",
  "op1e30": "1,30 €",
  "opGuardar0": "No guardo nada",
  "opGuardar2": "Guardo 2 €",
  "opGuardar10": "Guardo los 10 €",
  "d1instr": "¿Cuánto vale este billete?",
  "d1pista": "Mira el número del billete.",
  "d1expl": "Es un billete de 10 €.",
  "d2instr": "No tienes pan para comer. ¿Lo necesitas?",
  "d2pista": "Piensa en la comida de hoy.",
  "d2expl": "El pan cubre la comida que te falta.",
  "d3instr": "Necesitas pan y tiritas. Tienes 4 €. ¿Qué eliges?",
  "d3pista": "Suma el pan y las tiritas.",
  "d3expl": "Pan y tiritas cuestan 4 €. Cubres ambas necesidades.",
  "d4instr": "Pagas 5 €. La compra cuesta 2,30 €. ¿Qué vuelta recibes?",
  "d4pista": "Resta 2,30 a 5.",
  "d4expl": "5 € menos 2,30 € son 2,70 €.",
  "d5instr": "¿Cuánto puedes ahorrar sin tocar el dinero para comida?",
  "d5pista": "Aparta primero los 8 € para comer.",
  "d5expl": "Puedes ahorrar 2 €. Quedan 8 € para comida.",
  "pistaSigue": "Piénsalo con calma.",
  "presupuesto": "Presupuesto:",
  "completado": "¡Enhorabuena! Has hecho una compra completa.",
  "reiniciar": "↻ Volver a hacerlo",
  "fallo": "Casi. Vuelve a pensarlo.",
  "yaCompletada": "Ya has hecho esta situación. Puedes volver a hacerla.",
  "reviewScene1": "🥖 2 €   🎮 30 €",
  "reviewScene2": "Tienes 4 €: 🎮 20 €   🩹 2 €   🍞 2 €",
  "reviewScene3": "Pagas con 5 € y la compra vale 2,30 €",
  "reviewScene4": "Tienes 10 € y quieres ahorrar para unos auriculares.",
  "reviewScene5": "Tienes 10 €. Necesitas reservar 8 € para comida."
}, 'es');
