App.i18n.register({
  "title": "Plan your shopping day",
  "metaDescription": "Plan a shop, choose what you need and check the change.",
  "objetivo": "Plan your shop and check the change.",
  "instruccion": "Plan your shop before you pay.",
  "didacticTitle": "Plan your shop",
  "didacticBody": "Make a list. Take only what you can spend.",
  "didacticExampleLabel": "Example",
  "didacticExample": "If you have €10, the total must not go over €10.",
  "didacticContinue": "Try situations",
  "shopTu": "You",
  "shopMercadona": "Supermarket",
  "shopFarmacia": "Pharmacy",
  "shopBanco": "Bank",
  "opLlevar": "I make a list and bring just enough money",
  "opSalirYa": "I just go out and buy what I feel like",
  "opMando": "I ask someone else to buy for me",
  "opTransJugo": "🚌 Bus + 🧃 Juice",
  "opJuegoTiritas": "🎮 Game + 🩹 Plasters",
  "opJugoJuego": "🧃 Juice + 🎮 Game",
  "opComidaTiritas": "🍜 Food + 🩹 Plasters",
  "opComidaJuego": "🍜 Food + 🎮 Game",
  "opTiritasLibro": "🩹 Plasters + 📚 Book",
  "op550": "€5.50",
  "op650": "€6.50",
  "op450": "€4.50",
  "op1e": "€1",
  "op5e": "€5",
  "op10e": "€10",
  "opNecesito": "I need it",
  "opQuiero": "I want it",
  "opJuego": "🎮 Game",
  "opTiritasPan": "🩹 Plasters + 🍞 Bread",
  "op2e70": "€2.70",
  "op3e70": "€3.70",
  "op1e30": "€1.30",
  "opGuardar0": "I save nothing",
  "opGuardar2": "I save €2",
  "opGuardar10": "I save all €10",
  "d1instr": "How much is this banknote worth?",
  "d1pista": "Look at the number on the banknote.",
  "d1expl": "It is a €10 banknote.",
  "d2instr": "You have no bread for your meal. Do you need it?",
  "d2pista": "Think about your meal today.",
  "d2expl": "Bread provides the food you are missing.",
  "d3instr": "You need bread and plasters. You have €4. What fits?",
  "d3pista": "Add the bread and plasters.",
  "d3expl": "Bread and plasters cost €4. Both needs are covered.",
  "d4instr": "You pay €5. The purchase costs €2.30. What is the change?",
  "d4pista": "Subtract 2.30 from 5.",
  "d4expl": "€5 minus €2.30 is €2.70.",
  "d5instr": "How much can you save while keeping the food money?",
  "d5pista": "Set aside the €8 for food first.",
  "d5expl": "You can save €2. That leaves €8 for food.",
  "pistaSigue": "Think calmly.",
  "presupuesto": "Budget:",
  "completado": "Well done! You did a full shop.",
  "reiniciar": "↻ Try it again",
  "fallo": "Almost. Think again.",
  "yaCompletada": "You have already tried this situation. You can try it again.",
  "reviewScene1": "🥖 2 €   🎮 30 €",
  "reviewScene2": "You have €4: 🎮 20 €   🩹 2 €   🍞 2 €",
  "reviewScene3": "You pay with €5. The purchase costs €2.30.",
  "reviewScene4": "You have €10 and want to save for headphones.",
  "reviewScene5": "You have €10. You need to keep €8 for food."
}, 'en');
