(function () {
  'use strict';
  App.i18n.register({
    title: 'My shopping day',
    metaDescription: 'Practise everything together in a full shop: think, prioritise, buy, work out change and save.',
    instruccion: 'Five steps for a full shop.',
    shopTu: 'You', shopMercadona: 'Supermarket', shopFarmacia: 'Pharmacy', shopBanco: 'Bank',
    opLlevar: 'I make a list and bring just enough money',
    opSalirYa: 'I just go out and buy what I feel like',
    opMando: 'I ask someone else to buy for me',
    opTransJugo: '🚌 Bus + 🧃 Juice',
    opJuegoTiritas: '🎮 Game + 🩹 Plasters',
    opJugoJuego: '🧃 Juice + 🎮 Game',
    opComidaTiritas: '🍜 Food + 🩹 Plasters',
    opComidaJuego: '🍜 Food + 🎮 Game',
    opTiritasLibro: '🩹 Plasters + 📚 Book',
    op550: '€5.50',
    op650: '€6.50',
    op450: '€4.50',
    op1e: '€1',
    op5e: '€5',
    op10e: '€10',
    opNecesito: 'I need it',
    opQuiero: 'I want it',
    opJuego: '🎮 Game',
    opTiritasPan: '🩹 Plasters + 🍞 Bread',
    op2e70: '€2.70',
    op3e70: '€3.70',
    op1e30: '€1.30',
    opGuardar0: 'I save nothing',
    opGuardar2: 'I save €2',
    opGuardar10: 'I save all €10',
    d1instr: 'You are going shopping. What do you do first?', d1pista: 'Think before you spend.', d1expl: 'List + just enough money: no overspend.',
    d2instr: 'You have 8 €. What do you buy first?', d2pista: 'Transport and drink.', d2expl: 'Bus + juice: get home and hydrate.',
    d3instr: 'You have 10 €. What do you buy first?', d3pista: 'Health and food.', d3expl: 'Food + plasters: the essentials.',
    d4instr: 'You pay with 20 € and the shop costs 14.50 €. How much change?', d4pista: 'Subtract: 20 − 14.50.', d4expl: '20.00 − 14.50 = 5.50 €.',
    d5instr: 'You have €10. What helps you move towards your goal?', d5pista: 'You can save a little and still have money.', d5expl: 'Saving €2 moves you towards the goal without leaving you with nothing.',
    pistaSigue: 'Think calmly.',
    presupuesto: 'Budget:',
    completado: 'Well done! You did a full shop.',
    reiniciar: '↻ Play again',
    fallo: 'Almost. Think again.',
    yaCompletada: 'You already finished this activity.'
  }, 'en');
})();
