/* tools/needs-vs-wants — Activity: ¿Es una necesidad o un deseo?
   Each case shows a scenario and asks the person to classify it.
   3 options, socratic help, +8 tokens on completion. The cases cover
   essentials, optional spending, and purchases that combine a need with
   a personal preference. */
(function () {
  'use strict';
  App.activity.run({
    slug: 'needs-vs-wants',
    rewardCents: 800,
    casos: [
      { id: 'w1', sceneKey: 'scenes.w1',
        opciones: ['opNecesito', 'opQuiero', 'opAmbos'], correctaIndex: 0,
        pistaKey: 'pistaNecesidad', explicacionKey: 'explNecesidad' },
      { id: 'w2', sceneKey: 'scenes.w2',
        opciones: ['opNecesito', 'opQuiero', 'opAmbos'], correctaIndex: 0,
        pistaKey: 'pistaNecesidad', explicacionKey: 'explNecesidad' },
      { id: 'w3', sceneKey: 'scenes.w3',
        opciones: ['opNecesito', 'opQuiero', 'opAmbos'], correctaIndex: 0,
        pistaKey: 'pistaNecesidad', explicacionKey: 'explNecesidad' },
      { id: 'w4', sceneKey: 'scenes.w4',
        opciones: ['opNecesito', 'opQuiero', 'opAmbos'], correctaIndex: 0,
        pistaKey: 'pistaNecesidad', explicacionKey: 'explNecesidad' },
      { id: 'w5', sceneKey: 'scenes.w5',
        opciones: ['opNecesito', 'opQuiero', 'opAmbos'], correctaIndex: 0,
        pistaKey: 'pistaNecesidad', explicacionKey: 'explNecesidad' },
      { id: 'w6', sceneKey: 'scenes.w6',
        opciones: ['opNecesito', 'opQuiero', 'opAmbos'], correctaIndex: 0,
        pistaKey: 'pistaNecesidad', explicacionKey: 'explNecesidad' },
      { id: 'w7', sceneKey: 'scenes.w7',
        opciones: ['opNecesito', 'opQuiero', 'opAmbos'], correctaIndex: 1,
        pistaKey: 'pistaDeseo', explicacionKey: 'explDeseo' },
      { id: 'w8', sceneKey: 'scenes.w8',
        opciones: ['opNecesito', 'opQuiero', 'opAmbos'], correctaIndex: 1,
        pistaKey: 'pistaDeseo', explicacionKey: 'explDeseo' },
      { id: 'w9', sceneKey: 'scenes.w9',
        opciones: ['opNecesito', 'opQuiero', 'opAmbos'], correctaIndex: 1,
        pistaKey: 'pistaDeseo', explicacionKey: 'explDeseo' },
      { id: 'w10', sceneKey: 'scenes.w10',
        opciones: ['opNecesito', 'opQuiero', 'opAmbos'], correctaIndex: 1,
        pistaKey: 'pistaDeseo', explicacionKey: 'explDeseo' },
      { id: 'w11', sceneKey: 'scenes.w11',
        opciones: ['opNecesito', 'opQuiero', 'opAmbos'], correctaIndex: 1,
        pistaKey: 'pistaDeseo', explicacionKey: 'explDeseo' },
      { id: 'w12', sceneKey: 'scenes.w12',
        opciones: ['opNecesito', 'opQuiero', 'opAmbos'], correctaIndex: 1,
        pistaKey: 'pistaDeseo', explicacionKey: 'explDeseo' },
      { id: 'w13', sceneKey: 'scenes.w13',
        opciones: ['opNecesito', 'opQuiero', 'opAmbos'], correctaIndex: 2,
        pistaKey: 'pistaAmbas', explicacionKey: 'explAmbas' },
      { id: 'w14', sceneKey: 'scenes.w14',
        opciones: ['opNecesito', 'opQuiero', 'opAmbos'], correctaIndex: 2,
        pistaKey: 'pistaAmbas', explicacionKey: 'explAmbas' },
      { id: 'w15', sceneKey: 'scenes.w15',
        opciones: ['opNecesito', 'opQuiero', 'opAmbos'], correctaIndex: 2,
        pistaKey: 'pistaAmbas', explicacionKey: 'explAmbas' },
      { id: 'w16', sceneKey: 'scenes.w16',
        opciones: ['opNecesito', 'opQuiero', 'opAmbos'], correctaIndex: 2,
        pistaKey: 'pistaAmbas', explicacionKey: 'explAmbas' },
      { id: 'w17', sceneKey: 'scenes.w17',
        opciones: ['opNecesito', 'opQuiero', 'opAmbos'], correctaIndex: 2,
        pistaKey: 'pistaAmbas', explicacionKey: 'explAmbas' },
      { id: 'w18', sceneKey: 'scenes.w18',
        opciones: ['opNecesito', 'opQuiero', 'opAmbos'], correctaIndex: 2,
        pistaKey: 'pistaAmbas', explicacionKey: 'explAmbas' },
      { id: 'w19', sceneKey: 'scenes.w19',
        opciones: ['opNecesito', 'opQuiero', 'opAmbos'], correctaIndex: 0,
        pistaKey: 'pistaNecesidad', explicacionKey: 'explNecesidad' },
      { id: 'w20', sceneKey: 'scenes.w20',
        opciones: ['opNecesito', 'opQuiero', 'opAmbos'], correctaIndex: 0,
        pistaKey: 'pistaNecesidad', explicacionKey: 'explNecesidad' },
      { id: 'w21', sceneKey: 'scenes.w21',
        opciones: ['opNecesito', 'opQuiero', 'opAmbos'], correctaIndex: 0,
        pistaKey: 'pistaNecesidad', explicacionKey: 'explNecesidad' },
      { id: 'w22', sceneKey: 'scenes.w22',
        opciones: ['opNecesito', 'opQuiero', 'opAmbos'], correctaIndex: 0,
        pistaKey: 'pistaNecesidad', explicacionKey: 'explNecesidad' },
      { id: 'w23', sceneKey: 'scenes.w23',
        opciones: ['opNecesito', 'opQuiero', 'opAmbos'], correctaIndex: 1,
        pistaKey: 'pistaDeseo', explicacionKey: 'explDeseo' },
      { id: 'w24', sceneKey: 'scenes.w24',
        opciones: ['opNecesito', 'opQuiero', 'opAmbos'], correctaIndex: 1,
        pistaKey: 'pistaDeseo', explicacionKey: 'explDeseo' },
      { id: 'w25', sceneKey: 'scenes.w25',
        opciones: ['opNecesito', 'opQuiero', 'opAmbos'], correctaIndex: 1,
        pistaKey: 'pistaDeseo', explicacionKey: 'explDeseo' },
      { id: 'w26', sceneKey: 'scenes.w26',
        opciones: ['opNecesito', 'opQuiero', 'opAmbos'], correctaIndex: 1,
        pistaKey: 'pistaDeseo', explicacionKey: 'explDeseo' },
      { id: 'w27', sceneKey: 'scenes.w27',
        opciones: ['opNecesito', 'opQuiero', 'opAmbos'], correctaIndex: 2,
        pistaKey: 'pistaAmbas', explicacionKey: 'explAmbas' },
      { id: 'w28', sceneKey: 'scenes.w28',
        opciones: ['opNecesito', 'opQuiero', 'opAmbos'], correctaIndex: 2,
        pistaKey: 'pistaAmbas', explicacionKey: 'explAmbas' },
      { id: 'w29', sceneKey: 'scenes.w29',
        opciones: ['opNecesito', 'opQuiero', 'opAmbos'], correctaIndex: 2,
        pistaKey: 'pistaAmbas', explicacionKey: 'explAmbas' },
      { id: 'w30', sceneKey: 'scenes.w30',
        opciones: ['opNecesito', 'opQuiero', 'opAmbos'], correctaIndex: 2,
        pistaKey: 'pistaAmbas', explicacionKey: 'explAmbas' }
    ]
  });
})();
