/* tools/needs-vs-wants — Activity: ¿Es una necesidad o un deseo?
   Each case shows a scenario and asks the person to classify it.
   3 options, socratic help, +8 tokens on completion. The cases cover
   essentials, optional spending, and purchases that combine a need with
   a personal preference. */
(function () {
  'use strict';
  App.activity.run({
    slug: 'needs-vs-wants',
    rewardCents: 800,
    cases: [
      { id: 'w1', sceneKey: 'scenes.w1',
        options: ['opNecesito', 'opQuiero', 'opAmbos'], correctIndex: 0,
        hintKey: 'pistaNecesidad', explanationKey: 'explNecesidad' },
      { id: 'w2', sceneKey: 'scenes.w2',
        options: ['opNecesito', 'opQuiero', 'opAmbos'], correctIndex: 0,
        hintKey: 'pistaNecesidad', explanationKey: 'explNecesidad' },
      { id: 'w3', sceneKey: 'scenes.w3',
        options: ['opNecesito', 'opQuiero', 'opAmbos'], correctIndex: 0,
        hintKey: 'pistaNecesidad', explanationKey: 'explNecesidad' },
      { id: 'w4', sceneKey: 'scenes.w4',
        options: ['opNecesito', 'opQuiero', 'opAmbos'], correctIndex: 0,
        hintKey: 'pistaNecesidad', explanationKey: 'explNecesidad' },
      { id: 'w5', sceneKey: 'scenes.w5',
        options: ['opNecesito', 'opQuiero', 'opAmbos'], correctIndex: 0,
        hintKey: 'pistaNecesidad', explanationKey: 'explNecesidad' },
      { id: 'w6', sceneKey: 'scenes.w6',
        options: ['opNecesito', 'opQuiero', 'opAmbos'], correctIndex: 0,
        hintKey: 'pistaNecesidad', explanationKey: 'explNecesidad' },
      { id: 'w7', sceneKey: 'scenes.w7',
        options: ['opNecesito', 'opQuiero', 'opAmbos'], correctIndex: 1,
        hintKey: 'pistaDeseo', explanationKey: 'explDeseo' },
      { id: 'w8', sceneKey: 'scenes.w8',
        options: ['opNecesito', 'opQuiero', 'opAmbos'], correctIndex: 1,
        hintKey: 'pistaDeseo', explanationKey: 'explDeseo' },
      { id: 'w9', sceneKey: 'scenes.w9',
        options: ['opNecesito', 'opQuiero', 'opAmbos'], correctIndex: 1,
        hintKey: 'pistaDeseo', explanationKey: 'explDeseo' },
      { id: 'w10', sceneKey: 'scenes.w10',
        options: ['opNecesito', 'opQuiero', 'opAmbos'], correctIndex: 1,
        hintKey: 'pistaDeseo', explanationKey: 'explDeseo' },
      { id: 'w11', sceneKey: 'scenes.w11',
        options: ['opNecesito', 'opQuiero', 'opAmbos'], correctIndex: 1,
        hintKey: 'pistaDeseo', explanationKey: 'explDeseo' },
      { id: 'w12', sceneKey: 'scenes.w12',
        options: ['opNecesito', 'opQuiero', 'opAmbos'], correctIndex: 1,
        hintKey: 'pistaDeseo', explanationKey: 'explDeseo' },
      { id: 'w13', sceneKey: 'scenes.w13',
        options: ['opNecesito', 'opQuiero', 'opAmbos'], correctIndex: 2,
        hintKey: 'pistaAmbas', explanationKey: 'explAmbas' },
      { id: 'w14', sceneKey: 'scenes.w14',
        options: ['opNecesito', 'opQuiero', 'opAmbos'], correctIndex: 2,
        hintKey: 'pistaAmbas', explanationKey: 'explAmbas' },
      { id: 'w15', sceneKey: 'scenes.w15',
        options: ['opNecesito', 'opQuiero', 'opAmbos'], correctIndex: 2,
        hintKey: 'pistaAmbas', explanationKey: 'explAmbas' },
      { id: 'w16', sceneKey: 'scenes.w16',
        options: ['opNecesito', 'opQuiero', 'opAmbos'], correctIndex: 2,
        hintKey: 'pistaAmbas', explanationKey: 'explAmbas' },
      { id: 'w17', sceneKey: 'scenes.w17',
        options: ['opNecesito', 'opQuiero', 'opAmbos'], correctIndex: 2,
        hintKey: 'pistaAmbas', explanationKey: 'explAmbas' },
      { id: 'w18', sceneKey: 'scenes.w18',
        options: ['opNecesito', 'opQuiero', 'opAmbos'], correctIndex: 2,
        hintKey: 'pistaAmbas', explanationKey: 'explAmbas' },
      { id: 'w19', sceneKey: 'scenes.w19',
        options: ['opNecesito', 'opQuiero', 'opAmbos'], correctIndex: 0,
        hintKey: 'pistaNecesidad', explanationKey: 'explNecesidad' },
      { id: 'w20', sceneKey: 'scenes.w20',
        options: ['opNecesito', 'opQuiero', 'opAmbos'], correctIndex: 0,
        hintKey: 'pistaNecesidad', explanationKey: 'explNecesidad' },
      { id: 'w21', sceneKey: 'scenes.w21',
        options: ['opNecesito', 'opQuiero', 'opAmbos'], correctIndex: 0,
        hintKey: 'pistaNecesidad', explanationKey: 'explNecesidad' },
      { id: 'w22', sceneKey: 'scenes.w22',
        options: ['opNecesito', 'opQuiero', 'opAmbos'], correctIndex: 0,
        hintKey: 'pistaNecesidad', explanationKey: 'explNecesidad' },
      { id: 'w23', sceneKey: 'scenes.w23',
        options: ['opNecesito', 'opQuiero', 'opAmbos'], correctIndex: 1,
        hintKey: 'pistaDeseo', explanationKey: 'explDeseo' },
      { id: 'w24', sceneKey: 'scenes.w24',
        options: ['opNecesito', 'opQuiero', 'opAmbos'], correctIndex: 1,
        hintKey: 'pistaDeseo', explanationKey: 'explDeseo' },
      { id: 'w25', sceneKey: 'scenes.w25',
        options: ['opNecesito', 'opQuiero', 'opAmbos'], correctIndex: 1,
        hintKey: 'pistaDeseo', explanationKey: 'explDeseo' },
      { id: 'w26', sceneKey: 'scenes.w26',
        options: ['opNecesito', 'opQuiero', 'opAmbos'], correctIndex: 1,
        hintKey: 'pistaDeseo', explanationKey: 'explDeseo' },
      { id: 'w27', sceneKey: 'scenes.w27',
        options: ['opNecesito', 'opQuiero', 'opAmbos'], correctIndex: 2,
        hintKey: 'pistaAmbas', explanationKey: 'explAmbas' },
      { id: 'w28', sceneKey: 'scenes.w28',
        options: ['opNecesito', 'opQuiero', 'opAmbos'], correctIndex: 2,
        hintKey: 'pistaAmbas', explanationKey: 'explAmbas' },
      { id: 'w29', sceneKey: 'scenes.w29',
        options: ['opNecesito', 'opQuiero', 'opAmbos'], correctIndex: 2,
        hintKey: 'pistaAmbas', explanationKey: 'explAmbas' },
      { id: 'w30', sceneKey: 'scenes.w30',
        options: ['opNecesito', 'opQuiero', 'opAmbos'], correctIndex: 2,
        hintKey: 'pistaAmbas', explanationKey: 'explAmbas' }
    ]
  });
})();
