(function () {
  'use strict';
  App.i18n.register({
    title: 'Do you need it or want it?',
    metaDescription: 'Tell apart what you need from what you want.',
    objetivo: 'Tell what you need from what you want before you spend.',
    instruccion: 'What is the purchase for?',
    didacticTitle: 'A need and a want are different',
    didacticBody: 'You need something when not having it causes an important problem. You want something when it can wait.',
    didacticExampleLabel: 'Example',
    didacticExample: 'You need to pay the electricity bill: without paying, you may have no electricity. You want to buy a T-shirt from your favourite brand: it can wait. If your coat no longer keeps you warm, you need another one. Choosing the colour is a choice.',
    didacticContinue: 'Try situations',
    scenes: {
      w1: '🛒 At the shop, you buy the basic food for the week.',
      w2: '🏠 You pay the rent for your home.',
      w3: '💊 You buy the medicine the doctor prescribed.',
      w4: '💡 You pay the electricity bill so you can keep using electricity.',
      w5: '🚌 You buy a ticket to go to a medical appointment.',
      w6: '🧼 You buy soap and toothpaste because they have run out.',
      w7: '📺 Your TV works. You buy another because you want a bigger one.',
      w8: '🎟️ You buy a ticket for a concert this weekend.',
      w9: '🍫 You already have a snack at home. You buy a chocolate bar because you feel like it.',
      w10: '📺 You can watch shows for free. You pay each month for a service to watch a new show.',
      w11: '🍕 You have food at home. You order pizza for a special dinner.',
      w12: '📚 You have a book you have not read. You buy another because it interests you.',
      w13: '🧥 It is cold and your coat no longer keeps you warm. You buy another. Two coats keep you warm. You choose your favourite colour.',
      w14: '📱 Your phone no longer works and you need another one to call people. A basic model works. You choose a more expensive one because it has more features.',
      w15: '👟 Your shoes are broken and you need new ones. A cheaper brand also works. You choose one particular brand.',
      w16: '🎒 Your backpack zip is broken. You need another one to carry your things. A simple backpack works. You choose your favourite colour.',
      w17: '👓 You need glasses to see well. A simple frame works. You choose a designer frame.',
      w18: '🛒 You need to buy food. The shop is nearby. You ask for it to be delivered.',
      w19: '🚰 You pay the water bill.',
      w20: '💡 You buy a light bulb because the one at home has blown.',
      w21: '🪟 You repair a broken window so cold air does not come in.',
      w22: '🚌 You buy a travel pass to go to work.',
      w23: '☕ You can make coffee at home. You buy a coffee outside.',
      w24: '🕯️ You buy candles to decorate your room.',
      w25: '👟 Your shoes still work. You buy new ones because they are fashionable.',
      w26: '🏖️ You book a holiday because you want to go.',
      w27: '👔 You start a new job and need suitable clothes. A simple jacket works. You choose a more expensive branded one.',
      w28: '🌐 You need internet to talk to the doctor from home. The basic plan works. You choose a more expensive plan to watch shows.',
      w29: '🪑 Your chair is broken and you need another one to sit on. A simple chair works. You choose a particular design.',
      w30: '🍲 You need to buy food. Two brands have similar products. You choose the more expensive brand.'
    },
    opNecesito: 'I need it',
    opQuiero: 'I want it',
    opAmbos: 'I need it and choose an extra',
    pistaNecesidad: 'If you do not buy it now, what important problem appears? Is it about food, health, home, transport or a bill?',
    pistaDeseo: 'If you wait until next week, what important problem appears? If none appears, it can wait.',
    pistaAmbas: 'What do you really need? Which part is only your choice: the brand, model, colour or service?',
    pistaSigue: 'Look at what happens if you wait. If an important problem appears, it is a need. If not, it is a want.',
    explNecesidad: 'It is a need if it solves an important problem: food, health, home, transport or a bill.',
    explDeseo: 'It is a want if you feel like having it, but it can wait without causing an important problem.',
    explAmbas: 'The purchase meets a need. The chosen brand, model, colour or service is a want.',
    shopTu: 'You', shopFamilia: 'Your family',
    completado: 'Well done! You can tell needs and wants apart.',
    reiniciar: '↻ Try it again',
    fallo: 'Almost. Think again.',
    yaCompletada: 'You have already tried this situation. You can try it again.'
  }, 'en');
})();
