(function () {
  'use strict';
  App.i18n.register({
    title: '¿Lo necesitas o lo quieres?',
    metaDescription: 'Distingue lo que necesitas de lo que quieres.',
    objetivo: 'Distingue lo que necesitas de lo que quieres antes de gastar.',
    instruccion: '¿Para qué sirve lo que vas a comprar?',
    didacticTitle: 'Necesitar y querer no es lo mismo',
    didacticBody: 'Necesitas algo cuando, si no lo tienes, aparece un problema importante. Quieres algo cuando puedes esperar.',
    didacticExampleLabel: 'Ejemplo',
    didacticExample: 'Necesitas pagar la luz: si no la pagas, puedes quedarte sin luz. Quieres comprar una camiseta de tu marca favorita: puedes esperar. Si tu abrigo ya no abriga, necesitas otro. Elegir el color es una elección.',
    didacticContinue: 'Probar situaciones',
    scenes: {
      w1: '🛒 En la tienda compras la comida básica de la semana.',
      w2: '🏠 Pagas el alquiler de tu casa.',
      w3: '💊 Compras el medicamento que te ha recetado el médico.',
      w4: '💡 Pagas la factura de la luz para seguir teniendo electricidad.',
      w5: '🚌 Compras un billete para ir a una cita médica.',
      w6: '🧼 Compras jabón y pasta de dientes porque se han terminado.',
      w7: '📺 Tu tele funciona. Compras otra porque quieres una más grande.',
      w8: '🎟️ Compras una entrada para un concierto del fin de semana.',
      w9: '🍫 Ya tienes merienda en casa. Compras una tableta de chocolate porque te apetece.',
      w10: '📺 Puedes ver series sin pagar. Pagas cada mes por una plataforma para ver una serie nueva.',
      w11: '🍕 Tienes comida en casa. Pides una pizza para una cena especial.',
      w12: '📚 Tienes un libro sin leer. Compras otro porque te interesa.',
      w13: '🧥 Hace frío y tu abrigo ya no abriga. Compras otro. Entre dos abrigos que abrigan igual, eliges tu color favorito.',
      w14: '📱 Tu móvil ya no funciona y necesitas otro para llamar. Un modelo básico sirve. Eliges uno más caro porque tiene más funciones.',
      w15: '👟 Tus zapatillas están rotas y necesitas otras. Otra marca más barata también sirve. Eliges una marca concreta.',
      w16: '🎒 La cremallera de tu mochila está rota. Necesitas otra para llevar tus cosas. Una mochila sencilla sirve. Eliges tu color favorito.',
      w17: '👓 Necesitas gafas para ver bien. Una montura sencilla sirve. Eliges una montura de diseño.',
      w18: '🛒 Necesitas comprar comida. La tienda está cerca. Pides que te la lleven a casa.',
      w19: '🚰 Pagas la factura del agua.',
      w20: '💡 Compras una bombilla porque la de casa se ha fundido.',
      w21: '🪟 Reparas una ventana rota para que no entre frío.',
      w22: '🚌 Compras un abono de transporte para ir al trabajo.',
      w23: '☕ Puedes hacer café en casa. Compras un café fuera.',
      w24: '🕯️ Compras velas para decorar tu habitación.',
      w25: '👟 Tus zapatillas todavía sirven. Compras otras porque están de moda.',
      w26: '🏖️ Reservas un viaje de vacaciones porque quieres ir.',
      w27: '👔 Empiezas un trabajo y necesitas ropa adecuada. Una chaqueta sencilla sirve. Eliges una de marca más cara.',
      w28: '🌐 Necesitas internet para hablar con el médico desde casa. El plan básico sirve. Eliges un plan más caro para ver series.',
      w29: '🪑 Tu silla está rota y necesitas otra para sentarte. Una silla sencilla sirve. Eliges un diseño concreto.',
      w30: '🍲 Necesitas comprar comida. Dos marcas tienen productos parecidos. Eliges la marca más cara.'
    },
    opNecesito: 'Lo necesito',
    opQuiero: 'Lo quiero',
    opAmbos: 'Lo necesito y elijo algo extra',
    pistaNecesidad: 'Si no lo compras ahora, ¿qué problema importante aparece? ¿Tiene que ver con comer, cuidarte, vivir, moverte o pagar?',
    pistaDeseo: 'Si esperas hasta la semana que viene, ¿qué problema importante aparece? Si no aparece, puede esperar.',
    pistaAmbas: '¿Qué necesitas de verdad? ¿Qué parte es solo tu elección: la marca, el modelo, el color o el servicio?',
    pistaSigue: 'Mira qué pasa si esperas. Si aparece un problema importante, es una necesidad. Si no, es un deseo.',
    explNecesidad: 'Es una necesidad si resuelve algo importante: comer, cuidarte, vivir en casa, moverte o pagar un recibo.',
    explDeseo: 'Es un deseo si te apetece, pero puedes esperar sin que aparezca un problema importante.',
    explAmbas: 'La compra cubre una necesidad. La marca, el modelo, el color o el servicio elegido es un deseo.',
    shopTu: 'Tú', shopFamilia: 'Tu familia',
    completado: '¡Muy bien! Ya distingues necesidades de deseos.',
    reiniciar: '↻ Volver a hacerlo',
    fallo: 'Casi. Vuelve a pensarlo.',
    yaCompletada: 'Ya has hecho esta situación. Puedes volver a hacerla.'
  }, 'es');
})();
